// d10Clips.ts — nya klipp i D10. Läggs in i figureClips.ts. Tider i sekunder vid normal takt.
export const D10_CLIPS = {
  'truck.serveLidded':   { dur: 1.9, who: 'staff', note: 'Som truck.serve, men locket stängs vid u 0,36 innan tråget räcks ut.' },
  'staff.liftTable':     { dur: 1.0, who: 'staff', note: 'Vänder sig mot bordet, tar tag med båda händerna, lyfter vid u 0,55.' },
  'staff.carryTable':    { dur: 3.2, who: 'staff', speed: 0.7, note: 'Bordet 0,48 m framför, korta steg.' },
  'staff.setTable':      { dur: 0.9, who: 'staff' },
  'guest.huddle':        { loop: true, who: 'guest', note: 'Under markisen: armarna in, lätt framåtlutad.' },
  'wasp.fly':            { loop: true, who: 'wasp', note: 'Öglor kring ett mål, radie 0,14–0,17 m, kort spår efter sig.' },
  'guest.freeze':        { dur: 0.7, who: 'guest', note: 'Armarna in mot kroppen, lutar bakåt, blicken på getingen.' },
  'guest.backAway':      { dur: 1.9, who: 'guest', dist: 0.75, note: 'Baklänges, blicken kvar på getingen. Slappnar av 2,2 s efter.' },
  'staff.capSauces':     { dur: 2.4, who: 'staff', note: 'Ett lock var 0,8 s: ketchup, senap, mild senap.' },
  'guest.tapCard':       { dur: 1.5, who: 'guest' },
  'guest.tryAgain':      { dur: 1.7, who: 'guest', note: 'Två försök till.' },
  'staff.checkTerminal': { dur: 2.0, who: 'staff', note: 'Lutar sig ut genom luckan och trycker.' },
  'staff.pointSwish':    { dur: 1.3, who: 'staff' },
  'guest.takePhone':     { dur: 1.2, who: 'guest' },
  'guest.scanSwish':     { dur: 1.8, who: 'guest', note: 'Telefonen över skylten, sedan 1,2 s med skärmen i guld.' },
  'guest.putAwayPhone':  { dur: 0.8, who: 'guest' },
  'staff.takeFromBox':   { dur: 1.4, who: 'staff', note: 'Grillaren tar en korv ur lådan. Följs av 1,0 s när den läggs på grillen.' },
  'staff.switchTongs':   { dur: 0.8, who: 'staff', note: 'Lägger ned den vanliga tången och tar vegotången, och tillbaka.' },
  'staff.turnVeg':       { dur: 2.8, who: 'staff', note: 'Vänder de två vegokorvarna.' },
  'dog.sit':             { loop: true, who: 'dog' },
  'dog.sniff':           { dur: 1.5, who: 'dog', note: 'Reser sig och nosar mot gästen bredvid, högst kopplets längd.' },
  'dog.drink':           { dur: 3.5, who: 'dog' },
  'dog.lie':             { loop: true, who: 'dog' },
  'guest.stepAside':     { dur: 1.0, who: 'guest', dist: 0.5, note: 'Ett steg bort från hunden, blicken på hunden.' },
  'fika.sipCup':         { from: 'fikaClips.ts', note: 'Stamgästen vid vår vagn, 1,6 s var 6 s.' },
  'guest.toastCup':      { dur: 2.2, who: 'guest', note: 'Vänder sig mot Grillvagnens skylt och sträcker fram koppen (höger hand 0,5 m fram), 1,0 s efter klunken.' }
} as const;
