// vagnenStrings.ts — D10, order 320. { sv, en }, brittisk engelska. Slås in i luckanStrings.ts. Inga speltal: {price} kommer från balance.ts.
export const VG_STRINGS: Record<string, { sv: string; en: string }> = {
  'ui.title': { sv: 'D10 · Det som syns vid vagnen', en: 'D10 · What you see at the truck' },
  'sc.rain': { sv: 'Regnet', en: 'The rain' },
  'sc.wasp': { sv: 'Getingen', en: 'The wasp' },
  'sc.card': { sv: 'Kortläsaren', en: 'The card reader' },
  'sc.sausage': { sv: 'Korven tar slut', en: 'Running out of sausages' },
  'sc.dog': { sv: 'Hunden', en: 'The dog' },
  'sc.rival': { sv: 'Grillvagnen', en: 'Grillvagnen' },
  'sc.menu': { sv: 'Menyn', en: 'The menu' },
  'sc.props': { sv: 'Föremålen', en: 'The props' },
  'ctl.step': { sv: 'Steg', en: 'Step' },
  'cam': { sv: 'kamera {m} m', en: 'camera {m} m' },

  'sit.rain.lid': { sv: 'Tråg med lock', en: 'Trays with lids' },
  'sit.rain.table': { sv: 'Ett bord flyttas in under markisen', en: 'A table is moved under the awning' },
  'sit.rain.tight': { sv: 'Tätt under markisen', en: 'Close together under the awning' },
  'sit.wasp.wasps': { sv: 'Getingar vid ketchupen och burken', en: 'Wasps at the ketchup and the can' },
  'sit.wasp.freeze': { sv: 'Gästen stelnar till och backar', en: 'The guest freezes and backs away' },
  'sit.wasp.lids': { sv: 'Lock på såserna', en: 'Lids on the sauces' },
  'sit.card.error': { sv: 'Fel på kortläsaren', en: 'The card reader fails' },
  'sit.card.swish': { sv: 'Swish i stället', en: 'Swish instead' },
  'sit.sausage.box': { sv: 'Få korvar kvar i lådan', en: 'Few sausages left in the box' },
  'sit.sausage.veg': { sv: 'Vegokorven har egen del och egen tång', en: 'The veggie sausage has its own section and tongs' },
  'sit.dog.leash': { sv: 'Hunden vid ståbordet', en: 'The dog at the standing table' },
  'sit.dog.bowl': { sv: 'Vattenskålen vid bordet längst bort', en: 'The water bowl at the far table' },
  'sit.rival.wide': { sv: 'Grillvagnens nya skylt', en: "Grillvagnen's new sign" },
  'sit.rival.close': { sv: 'Stamgästen skålar mot Grillvagnen', en: 'The regular raises a cup to Grillvagnen' },
  'clip.guest.toastCup': { sv: 'Skålar', en: 'Raises a cup' },
  'sit.menu.after': { sv: 'Den nya skylten', en: 'The new board' },
  'sit.menu.before': { sv: 'Skylten före', en: 'The board before' },

  // ----- i HUD:en, aldrig i bilden -----
  'pin.terminal.who': { sv: 'Kortläsaren', en: 'Card reader' },
  'pin.terminal.text': { sv: 'Ingen kontakt. Försök igen.', en: 'No connection. Try again.' },
  'pin.swish.who': { sv: 'Skylten vid luckan', en: 'Sign at the hatch' },
  'pin.swish.text': { sv: 'Swish', en: 'Swish' },
  'pin.rival.who': { sv: 'Grillvagnen', en: 'Grillvagnen' },
  'pin.rival.text': { sv: 'Halv special {price}', en: 'Half special {price}' },
  'menu.kicker': { sv: 'Skylten vid kön', en: 'The board by the queue' },
  'menu.new': { sv: 'Nytt', en: 'New' },
  'menu.veg': { sv: 'Vegokorv {price}', en: 'Veggie sausage {price}' },
  'menu.mildMustard': { sv: 'Mild senap', en: 'Mild mustard' },
  'menu.soda': { sv: 'Läsk {price}', en: 'Fizzy drink {price}' },
  'menu.coffee': { sv: 'Kaffe {price}', en: 'Coffee {price}' },

  // ----- föremålen -----
  'props10.title': { sv: 'Föremålen i D10', en: 'The props in D10' },
  'props10.sub': { sv: 'Uppifrån till vänster, från sidan till höger, i meter. Strecket: 0,5 m för möbler och hund, 0,1 m för det som ritas × 1,5 (streckat är verklig storlek), 1 cm för getingen (× 7).', en: 'Top view left, side view right, in metres. Bar: 0.5 m for furniture and the dog, 0.1 m for things drawn × 1.5 (dashed is real size), 1 cm for the wasp (× 7).' },
  'prop10.trayLid': { sv: 'Tråg med lock', en: 'Lidded tray' },
  'prop10.trayLid.dim': { sv: '0,22 × 0,10 × 0,07 m · × 1,5', en: '0.22 × 0.10 × 0.07 m · × 1.5' },
  'prop10.trayLid.note': { sv: 'Kartong med lock som viks över. I regn stänger medhjälparen locket innan tråget räcks ut.', en: 'Card tray with a fold-over lid. In the rain the assistant closes it before handing it out.' },
  'prop10.terminal': { sv: 'Kortläsare', en: 'Card reader' },
  'prop10.terminal.dim': { sv: '0,08 × 0,17 m · × 1,5 · betalhylla 0,70 × 0,32 m, 1,05 m upp', en: '0.08 × 0.17 m · × 1.5 · pay shelf 0.70 × 0.32 m, 1.05 m up' },
  'prop10.terminal.note': { sv: 'På en utfällbar hylla under luckan. Vid fel blinkar en bruten ring i mässing. Meddelandet står i HUD:en.', en: 'On a fold-out shelf below the hatch. On a fault a broken ring blinks in brass. The message is in the HUD.' },
  'prop10.swish': { sv: 'Swish-skylt', en: 'Swish sign' },
  'prop10.swish.dim': { sv: '0,15 × 0,21 m · bordsställ · × 1,5', en: '0.15 × 0.21 m · table stand · × 1.5' },
  'prop10.swish.note': { sv: 'Telefonen och QR-rutan som tecken, bredvid kortläsaren.', en: 'Phone and QR square as symbols, next to the card reader.' },
  'prop10.box': { sv: 'Låda med korv', en: 'Box of sausages' },
  'prop10.box.dim': { sv: '0,50 × 0,43 × 0,12 m · 20 platser', en: '0.50 × 0.43 × 0.12 m · 20 places' },
  'prop10.box.note': { sv: 'Kyld låda bredvid grillen, med locket uppfällt. Tomma platser syns som papper.', en: 'Chilled box beside the grill, lid up. Empty places show as paper.' },
  'prop10.vegGrill': { sv: 'Grillens vegodel', en: "The grill's veggie section" },
  'prop10.vegGrill.dim': { sv: '0,35 × 0,60 m · list 0,03 m · egen tång', en: '0.35 × 0.60 m · divider 0.03 m · own tongs' },
  'prop10.vegGrill.note': { sv: 'Västra delen av grillen, avskild med en list. Tången har mässingshandtag och ligger på vegodelen.', en: 'West end of the grill, behind a divider. The tongs have brass handles and rest on the veggie section.' },
  'prop10.wasp': { sv: 'Geting', en: 'Wasp' },
  'prop10.wasp.dim': { sv: '0,015 m · ritas × 7', en: '0.015 m · drawn × 7' },
  'prop10.wasp.note': { sv: 'Flyger i öglor kring ketchupen och den öppna burken, med ett kort spår efter sig.', en: 'Flies in loops round the ketchup and the open can, with a short trail.' },
  'prop10.sauceLids': { sv: 'Såser med lock', en: 'Sauces with lids' },
  'prop10.sauceLids.dim': { sv: 'Ø 0,06 × 0,20 m · lock Ø 0,068 m · × 1,5', en: 'Ø 0.06 × 0.20 m · lid Ø 0.068 m · × 1.5' },
  'prop10.sauceLids.note': { sv: 'Ketchup, senap och mild senap på hyllan. Locket fälls ned när getingarna kommer.', en: 'Ketchup, mustard and mild mustard on the shelf. The lid comes down when the wasps arrive.' },
  'prop10.dog': { sv: 'Hund i koppel', en: 'Dog on a lead' },
  'prop10.dog.dim': { sv: '0,80 × 0,30 m · 0,55 m hög · koppel 1,2 m', en: '0.80 × 0.30 m · 0.55 m high · lead 1.2 m' },
  'prop10.dog.note': { sv: 'Sitter, nosar, dricker och lägger sig. Kopplet går till ägarens hand.', en: "Sits, sniffs, drinks and lies down. The lead runs to the owner's hand." },
  'prop10.bowl': { sv: 'Vattenskål', en: 'Water bowl' },
  'prop10.bowl.dim': { sv: 'Ø 0,22 × 0,06 m', en: 'Ø 0.22 × 0.06 m' },
  'prop10.bowl.note': { sv: 'Vid bord B, längst bort från luckan.', en: 'By table B, furthest from the hatch.' },
  'prop10.rivalSign': { sv: 'Grillvagnens skylt', en: "Grillvagnen's sign" },
  'prop10.rivalSign.dim': { sv: '0,60 × 0,95 m · gatupratare', en: '0.60 × 0.95 m · A-board' },
  'prop10.rivalSign.note': { sv: 'Med en gul lapp i Grillvagnens färg. Texten står i HUD:en.', en: "With a yellow notice in Grillvagnen's colour. The text is in the HUD." },
  'prop10.coffeeCup': { sv: 'Kaffe att ta med', en: 'Takeaway coffee' },
  'prop10.coffeeCup.dim': { sv: 'Ø 0,08 × 0,11 m · lock · × 1,5', en: 'Ø 0.08 × 0.11 m · lid · × 1.5' },
  'prop10.coffeeCup.note': { sv: 'Pappmugg med lock och manschett i mässing.', en: 'Paper cup with a lid and a brass sleeve.' },
  'prop10.menu10': { sv: 'Vagnens skylt', en: "The truck's board" },
  'prop10.menu10.dim': { sv: '0,60 × 0,95 m · åtta rader', en: '0.60 × 0.95 m · eight lines' },
  'prop10.menu10.note': { sv: 'Nytt: vegokorv (blad), mild senap (droppe) och kaffe (kopp).', en: 'New: veggie sausage (leaf), mild mustard (drop) and coffee (cup).' },

  // ----- om skärmarna -----
  'vg.why.rain': { sv: 'Regn på 8–10 m. Tråg med lock: medhjälparen stänger locket innan tråget räcks ut, och den som går tar det under paraplyet. Bordet: medhjälparen bär ståbord A från däcket in under markisen. Luckan står tom så länge. Tätt: kön står 0,55 m isär under markisen, med armarna in, och tre äter vid det flyttade bordet.', en: 'Rain at 8–10 m. Lidded trays: the assistant closes the lid before handing the tray out, and those leaving carry it under the umbrella. The table: the assistant carries standing table A from the deck in under the awning, leaving the hatch empty meanwhile. Close together: the queue stands 0.55 m apart under the awning with arms in, and three eat at the moved table.' },
  'vg.why.wasp': { sv: 'En varm dag på 6 m. Getingar flyger kring ketchupen på hyllan och den öppna burken på bord A. En geting kommer till gästens ansikte, gästen stelnar till och backar 0,75 m. Sedan sätter medhjälparen lock på de tre såserna, och getingarna vid hyllan flyger i väg.', en: 'A warm day at 6 m. Wasps fly round the ketchup on the shelf and the open can on table A. One reaches the guest’s face; the guest freezes and backs away 0.75 m. Then the assistant puts lids on the three sauces, and the wasps at the shelf fly off.' },
  'vg.why.card': { sv: 'Vid luckan på 6 m. Gästen håller kortet mot läsaren, den väntar och visar fel. Gästen försöker igen, och medhjälparen lutar sig ut och trycker. Sedan pekar medhjälparen på Swish-skylten, och gästen betalar med telefonen. Kön står still så länge. Läsarens meddelande står i HUD:en.', en: 'At the hatch at 6 m. The guest holds the card to the reader; it waits, then fails. The guest tries again, and the assistant leans out and presses. Then the assistant points to the Swish sign and the guest pays by phone. The queue stands still meanwhile. The reader’s message is in the HUD.' },
  'vg.why.sausage': { sv: 'Inne i vagnen på 5 m. Lådan bredvid grillen har tre korvar kvar av 20. Grillaren tar en och lägger den på grillen. Vegokorven har grillens västra del bakom en list och en egen tång med mässingshandtag: grillaren lägger ned den vanliga tången, tar vegotången, vänder vegokorven och byter tillbaka.', en: 'Inside the truck at 5 m. The box beside the grill has three of 20 sausages left. The griller takes one and puts it on the grill. The veggie sausage has the west end of the grill behind a divider and its own brass-handled tongs: the griller puts down the usual tongs, takes the veggie tongs, turns the veggie sausages and swaps back.' },
  'vg.why.dog': { sv: 'Däcket på 7 m. En hund i koppel sitter vid ståbord A, reser sig och nosar mot gästen bredvid, som tar ett steg åt sidan. Vattenskålen står vid bord B, längst bort från luckan. Där dricker hunden och lägger sig.', en: 'The deck at 7 m. A dog on a lead sits by standing table A, gets up and sniffs at the guest beside it, who steps aside. The water bowl is by table B, furthest from the hatch. There the dog drinks and lies down.' },
  'vg.why.rival': { sv: 'Grillvagnen på torget, på 20 och 13 m. Den har en ny skylt med en gul lapp, och texten (Halv special {price}, i prototypen 25 kr) står i HUD:en. Stamgästen står vid vår vagn med en kaffekopp som spelaren har bjudit på. Hen dricker och skålar mot Grillvagnens skylt på andra sidan torget.', en: 'Grillvagnen on the square, at 20 and 13 m. It has a new sign with a yellow notice; the text (Half special {price}, 25 kr in the prototype) is in the HUD. The regular stands at our truck with a coffee the player has stood them. They drink and raise the cup to Grillvagnen’s sign across the square.' },
  'vg.why.menu': { sv: 'Vagnens skylt på 4 m, med texten i HUD:en. Tre nya rader: vegokorv, mild senap och kaffe, var och en med ett tecken i kritan. Läsk och kaffe är nu två rader. Priserna kommer från balance.ts.', en: 'The truck’s board at 4 m, with the text in the HUD. Three new lines: veggie sausage, mild mustard and coffee, each with a chalk symbol. Fizzy drinks and coffee are now two lines. Prices come from balance.ts.' },
  'vg.why.props': { sv: 'De tolv nya föremålen i meter, uppifrån och från sidan. Mått och platser står i truckProps.d10.ts.', en: 'The twelve new props in metres, from above and from the side. Sizes and positions are in truckProps.d10.ts.' }
};
