// eventVideoStrings.ts — prototypen för händelsernas video. 59 nycklar, { sv, en }. Visas bara i prototypen, inte i spelet.

export const EVENT_VIDEO_STRINGS = {
  "evv.kicker": { sv: "Leverans 3 · händelserna i vinbaren", en: "Delivery 3 · the wine bar events" },
  "evv.title": { sv: "Händelserna från spelets kamera", en: "The events from the game camera" },
  "evv.event.bday": { sv: "Födelsedagen", en: "The birthday" },
  "evv.event.vase": { sv: "Vasen på pulten", en: "The vase on the host stand" },
  "evv.ch.vbuild": { sv: "Uppbyggnaden. Gästen i rullstol välkomnas och svänger runt pulten.", en: "The build-up. The guest in a wheelchair is welcomed and turns round the stand." },
  "evv.ch.vend1": { sv: "Steg 1 rätt: Sara stannar före skärvorna, Per håller dörren.", en: "Step 1 right: Sara stops short of the shards, Per holds the door." },
  "evv.ch.vfail1": { sv: "Steg 1 fel: en gäst går över vattnet och halkar.", en: "Step 1 wrong: a guest walks through the water and slips." },
  "evv.ch.vfail2": { sv: "Steg 2 fel: Sara plockar en skärva med handen och skär sig. Per tar över med borsten.", en: "Step 2 wrong: Sara picks up a shard by hand and cuts herself. Per takes over with the broom." },
  "evv.ch.vfail3": { sv: "Steg 3 fel: pulten står kvar, och sällskapet vänder och går.", en: "Step 3 wrong: the stand stays put, and the party turns and leaves." },
  "evv.ch.vend2": { sv: "Steg 2 rätt: Sara frågar gästen först, sedan sopar och torkar hon.", en: "Step 2 right: Sara asks the guest first, then sweeps and wipes." },
  "evv.ch.vend3": { sv: "Steg 3 rätt: Per visar vägen och följer med till bordet.", en: "Step 3 right: Per shows the way and walks them to the table." },
  "evv.event.falls": { sv: "Vasen och ljuset som faller", en: "The vase and the candle falling" },
  "evv.variant.right": { sv: "Rätt svar", en: "Right answers" },
  "evv.variant.wrong1": { sv: "Fel i steg 1", en: "Wrong at step 1" },
  "evv.variant.wrong2": { sv: "Fel i steg 2", en: "Wrong at step 2" },
  "evv.variant.wrong3": { sv: "Fel i steg 3", en: "Wrong at step 3" },
  "evv.play": { sv: "Spela", en: "Play" },
  "evv.pause": { sv: "Pausa", en: "Pause" },
  "evv.record": { sv: "Spela in WebM", en: "Record WebM" },
  "evv.recording": { sv: "Spelar in …", en: "Recording …" },
  "evv.size": { sv: "Skärmen", en: "Screen" },
  "evv.ch.build": { sv: "Uppbyggnaden. Kameran glider in till 12 m.", en: "The build-up. The camera glides in to 12 m." },
  "evv.ch.ask": { sv: "Frågeögonblicket. Kortet öppnas med steg 1.", en: "The question. The card opens at step 1." },
  "evv.ch.end1": { sv: "Steg 1 rätt: Per går till passluckan.", en: "Step 1 right: Per goes to the pass." },
  "evv.ch.end2": { sv: "Steg 2 rätt: ljusen tänds vid luckan och tårtan bärs lugnt.", en: "Step 2 right: candles lit at the pass, the cake carried slowly." },
  "evv.ch.fail2": { sv: "Steg 2 fel: Sara bär fort, ett ljus faller, Per kväver det.", en: "Step 2 wrong: Sara hurries, a candle falls, Per smothers it." },
  "evv.ch.end3": { sv: "Steg 3 rätt: en vers, och grannarna bjuds.", en: "Step 3 right: one verse, and the neighbours are treated." },
  "evv.ch.back": { sv: "Kameran går tillbaka till 24 m.", en: "The camera returns to 24 m." },
  "evv.ch.vase": { sv: "Vasen faller från värdpulten: vatten, skärvor och blommor.", en: "The vase falls from the host stand: water, shards and flowers." },
  "evv.ch.candle": { sv: "Ett ljus faller från tårtan på loungebordet och brinner tills det kvävs.", en: "A candle falls from the cake onto the lounge table and burns until smothered." },
  "evv.event.drunk": { sv: "Gästen som vinglar", en: "The guest who sways" },
  "evv.event.inspection": { sv: "Tillsynen", en: "The inspection" },
  "evv.event.kitchen": { sv: "Gästen vid passet", en: "The guest at the pass" },
  "evv.variant.rightB": { sv: "Rätt, variant B", en: "Right, variant B" },
  "evv.variant.rightC": { sv: "Rätt, variant C", en: "Right, variant C" },
  "evv.ch.iaskB": { sv: "Variant B: två unga gäster i lounge B beställer vin av Sara.", en: "Variant B: two young guests in lounge B order wine from Sara." },
  "evv.ch.iendB": { sv: "Steg 3 rätt: Sara ber om legitimation innan hon häller, och båda visar den.", en: "Step 3 right: Sara asks for ID before she pours, and both show it." },
  "evv.ch.iaskC": { sv: "Variant C: handläggaren bläddrar i egenkontrollen och frågar hur personalen vet vad som står i den.", en: "Variant C: the licensing officer leafs through the self-check and asks how the staff know what is in it." },
  "evv.ch.iendC": { sv: "Steg 3 rätt: Per vinkar till sig Mira, som visar i pärmen att hon kan den.", en: "Step 3 right: Per calls Mira over, and she shows in the folder that she knows it." },
  "evv.variant.rightD": { sv: "Rätt, variant D", en: "Right, variant D" },
  "evv.ch.dbuild": { sv: "Uppbyggnaden. Gästen kliver ned från barstolen, rakt in i Saras bricka, och svajar.", en: "The build-up. The guest steps down from the stool, straight into Sara's tray, and sways." },
  "evv.ch.dend1": { sv: "Steg 1 rätt: Mira lutar sig fram över disken. Sara går vidare med brickan.", en: "Step 1 right: Mira leans across the bar. Sara carries on with the tray." },
  "evv.ch.dend2": { sv: "Steg 2 rätt: han sätter sig igen och Mira häller upp vatten.", en: "Step 2 right: he sits back down and Mira pours him water." },
  "evv.ch.dend3": { sv: "Steg 3 rätt: vännen vinkar, Mira säger nej och skriver upp tiden.", en: "Step 3 right: his friend waves, Mira says no and notes the time." },
  "evv.ch.dfail1": { sv: "Steg 1 fel: Mira häller upp vin och han dricker. Per kommer från pulten.", en: "Step 1 wrong: Mira pours wine and he drinks. Per comes over from the stand." },
  "evv.ch.dfail2": { sv: "Steg 2 fel: vännerna hör, skrattar och klappar honom. Han blir högljudd. Per kommer.", en: "Step 2 wrong: the friends overhear, laugh and pat him. He gets loud. Per comes over." },
  "evv.ch.dfail3": { sv: "Steg 3 fel: vännen får ett glas och skjuter det till honom. Per kommer.", en: "Step 3 wrong: his friend gets a glass and slides it over to him. Per comes over." },
  "evv.ch.ibuild": { sv: "Uppbyggnaden. Två gäster beställer vatten vid kortänden och iakttar rummet. När Per kommer visar de legitimation.", en: "The build-up. Two guests order water at the end of the bar and watch the room. When Per arrives they show their ID." },
  "evv.ch.iend1": { sv: "Steg 1 rätt: Per visar att det är han som är serveringsansvarig.", en: "Step 1 right: Per shows that he is the responsible person." },
  "evv.ch.iend2": { sv: "Steg 2 rätt: Per hämtar pärmen i pulten och lägger den öppen på disken.", en: "Step 2 right: Per fetches the folder from the stand and lays it open on the bar." },
  "evv.ch.iaskA": { sv: "Variant A: polisen nickar mot gästen som nekades, med vattenglaset.", en: "Variant A: the officer nods towards the refused guest with his glass of water." },
  "evv.ch.iaskD": { sv: "Variant D: kocken har sagt att maten är slut, och handläggaren vill beställa.", en: "Variant D: the chef has said the food has run out, and the licensing officer wants to order." },
  "evv.ch.iend3": { sv: "Steg 3 rätt: Mira visar blocket med tiden.", en: "Step 3 right: Mira shows the pad with the time." },
  "evv.ch.iendD": { sv: "Steg 3 rätt: kocken lagar något enkelt, och Sara bär det till kortänden.", en: "Step 3 right: the chef makes something simple, and Sara brings it to the end of the bar." },
  "evv.ch.ifail1": { sv: "Steg 1 fel: Per pekar på Mira. Handläggaren skriver.", en: "Step 1 wrong: Per points at Mira. The officer takes notes." },
  "evv.ch.ifail2": { sv: "Steg 2 fel: egenkontrollen saknas i det Per visar. Handläggaren skriver.", en: "Step 2 wrong: the self-check is missing from what Per shows. The officer takes notes." },
  "evv.ch.ifail3": { sv: "Steg 3 fel: polisen har sett honom vingla och skakar på huvudet. Handläggaren skriver.", en: "Step 3 wrong: the police officer saw him sway and shakes his head. The officer takes notes." },
  "evv.ch.iexit": { sv: "Rapporten skrivs, och de går mot dörren.", en: "The report is written, and they head for the door." },
  "evv.ch.kbuild": { sv: "Uppbyggnaden. Gästen reser sig i rusningen och går till passluckan. Sara kliver åt sidan.", en: "The build-up. The guest gets up mid-rush and walks to the pass. Sara steps aside." },
  "evv.ch.kend1": { sv: "Steg 1 rätt: kocken håller upp en hand och nickar.", en: "Step 1 right: the chef raises a hand and nods." },
  "evv.ch.kend2": { sv: "Steg 2 rätt: kocken håller köksdörren, gästen får förklädet och tittar in.", en: "Step 2 right: the chef holds the kitchen door, the guest gets the apron and looks in." },
  "evv.ch.kend3": { sv: "Steg 3 rätt: hon sätter sig, och Sara bär ut en smakbit.", en: "Step 3 right: she sits back down, and Sara brings out a taste." },
  "evv.ch.kfail1": { sv: "Steg 1 fel: hon går in utan förkläde. Kocken följer ut henne.", en: "Step 1 wrong: she walks in without an apron. The chef walks her out." },
  "evv.ch.kfail2": { sv: "Steg 2 fel: hon tas in direkt, och kocken måste kliva undan. Per följer ut henne.", en: "Step 2 wrong: she is taken straight in, and the chef has to step aside. Per walks her out." },
  "evv.ch.kfail3": { sv: "Steg 3 fel: en lugnare kväll. Hon nickar och betalar.", en: "Step 3 wrong: a quieter evening. She nods and pays." },
} as const;
