// eventStrings — texten i händelsernas manus (leverans 3, andra utkastet, för granskning).
// Slås in i STRINGS i nexusStrings.ts. Engelskan är brittisk. Tal är platshållare.
// Rätt svar står i manusen, inte här. near3_N förklarar varför ett försvarbart svar inte är det bästa.

export const EVENT_STRINGS: Record<string, { sv: string; en: string }> = {
  // ---------- Gemensamt ----------
  'event.takeover.per': { sv: "Per tar över.", en: "Per takes over." },
  'event.sanction.none': { sv: "Inga anmärkningar", en: "No remarks" },
  'event.sanction.remark': { sv: "Anmärkning i rapporten, ingen påföljd", en: "A remark in the report, no sanction" },
  'event.sanction.erinran': { sv: "Risk för erinran", en: "Risk of a formal reminder" },
  'event.sanction.varning': { sv: "Risk för varning", en: "Risk of a warning" },
  'event.sanction.revoke': { sv: "Risk för återkallat tillstånd", en: "Risk of the licence being revoked" },
  'morning.letter.kicker': { sv: "Brev från kommunen", en: "Letter from the council" },
  'morning.letter.erinran': { sv: "Beslut efter tillsynen: erinran. Rätta bristen före nästa tillsyn.", en: "Decision after the inspection: a formal reminder. Put it right before the next inspection." },
  'morning.letter.varning': { sv: "Beslut efter tillsynen: varning. Nästa allvarliga brist kan kosta tillståndet.", en: "Decision after the inspection: a warning. The next serious breach could cost you the licence." },
  'morning.letter.revoke': { sv: "Beslut efter tillsynen: serveringstillståndet återkallas. Vinbaren stänger.", en: "Decision after the inspection: the licence is revoked. The wine bar closes." },

  // ---------- 1 · Födelsedagen ----------
  'event.bday.title': { sv: "Födelsedagen", en: "The birthday" },
  'event.bday.role': { sv: "Hovmästaren · lounge A", en: "Maître d’ · lounge A" },
  'event.bday.moment': { sv: "Värden i lounge A vinkar diskret till Per, lutar sig fram och viskar att det är Karins födelsedag i kväll.", en: "The host in lounge A waves discreetly to Per, leans in and whispers that it is Karin’s birthday tonight." },
  'event.bday.caption': { sv: "Värden viskar till Per", en: "The host whispers to Per" },
  'event.bday.say.whisper': { sv: "Det är Karins födelsedag i kväll.", en: "It’s Karin’s birthday tonight." },
  'event.bday.say.sing': { sv: "Ja må hon leva!", en: "Happy birthday to you!" },
  'event.bday.q1': { sv: "Vad behöver köket veta först?", en: "What does the kitchen need to know first?" },
  'event.bday.a1_1': { sv: "Att ljus och tändare ska ligga på brickan", en: "That candles and a lighter go on the tray" },
  'event.bday.a1_2': { sv: "Hur många som ska ha och när den ska ut", en: "How many it’s for and when it goes out" },
  'event.bday.a1_3': { sv: "Antal, allergier och när den ska ut", en: "Numbers, allergies and when it goes out" },
  'event.bday.a1_4': { sv: "Vilken efterrätt värden helst vill ha", en: "Which dessert the host would prefer" },
  'event.bday.why1': { sv: "Köket planerar i antal och tid. Allergier går före allt annat, också på en fest.", en: "The kitchen plans in numbers and time. Allergies come before everything else, even at a party." },
  'event.bday.ok1': { sv: "Tre personer, en nötallergi, när de har ätit klart.", en: "Three guests, one nut allergy, once they’ve finished eating." },
  'event.bday.q2': { sv: "Hur bär Sara ut en efterrätt med tända ljus?", en: "How does Sara carry out a dessert with lit candles?" },
  'event.bday.a2_1': { sv: "Fort, så att ljusen inte hinner brinna ned", en: "Quickly, so the candles don’t have time to burn down" },
  'event.bday.a2_2': { sv: "Tänds vid luckan, bärs lågt och sakta i fri gång", en: "Lit at the hatch, carried low and slowly, path clear" },
  'event.bday.a2_3': { sv: "Tänds vid luckan och bärs högt över gästerna", en: "Lit at the hatch and carried high above the guests" },
  'event.bday.a2_4': { sv: "Genom barens stråk, den kortaste vägen till loungen", en: "Through the bar runway, the shortest way to the lounge" },
  'event.bday.why2': { sv: "Öppen låga bland gäster kräver fri väg, lågt grepp och lugnt tempo.", en: "An open flame among guests needs a clear path, a low grip and a calm pace." },
  'event.bday.ok2': { sv: "Nu kommer den!", en: "Here it comes!" },
  'event.bday.q3': { sv: "I lounge B sitter två gäster i ett affärssamtal och vill ha lugn. Sällskapet vill sjunga. Vad gör du?", en: "In lounge B two guests are in a business meeting and want quiet. The party wants to sing. What do you do?" },
  'event.bday.a3_1': { sv: "Ber sällskapet vänta tills grannarna har gått", en: "Asks the party to wait until the neighbours leave" },
  'event.bday.a3_2': { sv: "Frågar grannarna först om en kort sång går bra", en: "Asks the neighbours first if a short song is all right" },
  'event.bday.a3_3': { sv: "Låter dem sjunga en vers och bjuder grannarna", en: "Lets them sing one verse and treats the neighbours" },
  'event.bday.a3_4': { sv: "Ber DJ:n höja musiken så att sången smälter in", en: "Asks the DJ to turn up the music so the song blends in" },
  'event.bday.why3': { sv: "Kvällen tillhör alla bord. En kort fest och en gest till grannarna håller båda nöjda.", en: "The evening belongs to every table. A short celebration and a gesture to the neighbours keeps both happy." },
  'event.bday.near3_1': { sv: "Hänsynsfullt, men grannarna kan sitta kvar länge, och då blir det ingen sång alls.", en: "Considerate, but the neighbours may stay a long time, and then there’s no song at all." },
  'event.bday.near3_2': { sv: "Artigt, men då får grannarna säga nej till en födelsedag. Det är ett val du ska göra, inte de.", en: "Polite, but it leaves the neighbours to say no to a birthday. That choice is yours to make, not theirs." },
  'event.bday.ok3': { sv: "En vers, sedan dämpar vi.", en: "One verse, then we bring it down." },
  'event.bday.fail': { sv: "Jag tar hand om det.", en: "I’ll take care of it." },

  // ---------- 2 · Vasen på pulten ----------
  'event.vase.title': { sv: "Vasen på pulten", en: "The vase on the desk" },
  'event.vase.role': { sv: "Servitören · entrén", en: "Waiter · the entrance" },
  'event.vase.moment': { sv: "En gäst i rullstol kommer in mellan värdpulten och klädhängaren. Handen på hjulet tar i pulten, och vasen går i golvet.", en: "A guest in a wheelchair comes in between the host’s desk and the coat rail. A hand on the wheel catches the desk, and the vase smashes on the floor." },
  'event.vase.caption': { sv: "Vasen faller från pulten", en: "The vase falls from the desk" },
  'event.vase.say.welcome': { sv: "Välkomna! Ert bord står längst in.", en: "Welcome! Your table is at the far end." },
  'event.vase.say.oops': { sv: "Oj! Förlåt!", en: "Oh! I’m so sorry!" },
  'event.vase.q1': { sv: "Vad är risken just nu?", en: "What is the risk right now?" },
  'event.vase.a1_1': { sv: "Att gästen har skadat handen mot pulten", en: "That the guest has hurt a hand on the desk" },
  'event.vase.a1_2': { sv: "Att entrén blockeras för nästa sällskap", en: "That the entrance is blocked for the next party" },
  'event.vase.a1_3': { sv: "Glassplitter och vatten där gäster går in", en: "Broken glass and water where guests walk in" },
  'event.vase.a1_4': { sv: "Att vattnet förstör bokningsboken på pulten", en: "That the water ruins the booking book on the desk" },
  'event.vase.why1': { sv: "Glas och vatten i entrén är en risk för alla som går in, också för gästen i rullstolen. Hur gästen mår frågar du i nästa steg.", en: "Glass and water in the entrance are a hazard for everyone coming in, including the guest in the wheelchair. You ask how the guest is in the next step." },
  'event.vase.ok1': { sv: "Stanna där, det är glas på golvet.", en: "Stay there, there’s glass on the floor." },
  'event.vase.q2': { sv: "Hur tar du hand om det?", en: "How do you deal with it?" },
  'event.vase.a2_1': { sv: "Torkar upp vattnet först, så att ingen halkar", en: "Mops up the water first, so no one slips" },
  'event.vase.a2_2': { sv: "Frågar hur gästen mår, spärrar av, sopar och torkar", en: "Asks how the guest is, closes it off, sweeps, then mops" },
  'event.vase.a2_3': { sv: "Plockar de stora skärvorna för hand, sedan torkar du", en: "Picks up the big shards by hand, then mops" },
  'event.vase.a2_4': { sv: "Hämtar borste och skyffel och sopar upp allt direkt", en: "Fetches a brush and dustpan and sweeps it all up at once" },
  'event.vase.why2': { sv: "Människan först, sedan risken, sedan städningen.", en: "The person first, then the hazard, then the clean-up." },
  'event.vase.ok2': { sv: "Är du oskadd? Jag sopar upp.", en: "Are you all right? I’ll sweep it up." },
  'event.vase.q3': { sv: "Gästen skäms och vill gå hem. Vad gör du?", en: "The guest is embarrassed and wants to go home. What do you do?" },
  'event.vase.a3_1': { sv: "Bjuder sällskapet på kvällen och ber om ursäkt", en: "Treats the party to the evening and apologises" },
  'event.vase.a3_2': { sv: "Säger att det kan hända vem som helst och visar vägen", en: "Says it could happen to anyone and shows the way" },
  'event.vase.a3_3': { sv: "Säger att felet var vårt, flyttar vasen och visar vägen", en: "Says it was our fault, moves the vase, shows the way" },
  'event.vase.a3_4': { sv: "Respekterar det och bokar ett bord åt dem en annan kväll", en: "Respects that and books them a table another evening" },
  'event.vase.why3': { sv: "Entrén var för trång för en rullstol. Felet är vårt, inte gästens. Säg det och rätta till det.", en: "The entrance was too narrow for a wheelchair. The fault is ours, not the guest’s. Say so and put it right." },
  'event.vase.near3_1': { sv: "Generöst, men utan förklaring kan gästen tro att du bjuder för att hen gjorde fel.", en: "Generous, but without an explanation the guest may think you’re paying because they did something wrong." },
  'event.vase.near3_4': { sv: "Respektfullt, men felet står kvar i entrén till nästa gäst.", en: "Respectful, but the fault is still there in the entrance for the next guest." },
  'event.vase.ok3': { sv: "Vasen stod fel. Vi flyttar den nu.", en: "The vase was in the wrong place. We’ll move it now." },
  'event.vase.fail': { sv: "Jag tar hand om det.", en: "I’ll take care of it." },
  'evening.event.vase': { sv: "Vasen på pulten", en: "The vase on the desk" },
  'evening.event.vase.line': { sv: "Vasen och pulten flyttades, och sällskapet stannade.", en: "The vase and the desk were moved, and the party stayed." },

  // ---------- 3 · Gästen som vinglar ----------
  'event.drunk.title': { sv: "Gästen som vinglar", en: "The unsteady guest" },
  'event.drunk.role': { sv: "Bartendern · baren", en: "Bartender · the bar" },
  'event.drunk.moment': { sv: "En gäst glider ned från barstolen, tar ett steg för långt bakåt och går rakt in i Saras bricka.", en: "A guest slides off his bar stool, takes one step too far back and walks straight into Sara’s tray." },
  'event.drunk.caption': { sv: "Han backar rakt in i brickan", en: "He backs straight into the tray" },
  'event.drunk.say.going': { sv: "Jag ska bara …", en: "I’m just going to …" },
  'event.drunk.say.sorry': { sv: "Förlååt …", en: "Sorryyy …" },
  'event.drunk.say.whoops': { sv: "Hoppsan!", en: "Whoops!" },
  'event.drunk.q1': { sv: "Vad säger alkohollagen om en gäst som är märkbart påverkad?", en: "What does the Alcohol Act say about a guest who is noticeably intoxicated?" },
  'event.drunk.a1_1': { sv: "Han får serveras om han äter något först", en: "He may be served if he eats something first" },
  'event.drunk.a1_2': { sv: "Han får serveras öl, men inte starksprit", en: "He may be served beer, but not spirits" },
  'event.drunk.a1_3': { sv: "Han måste lämna lokalen på en gång", en: "He must leave the premises at once" },
  'event.drunk.a1_4': { sv: "Han får inte serveras mer alkohol", en: "He may not be served any more alcohol" },
  'event.drunk.why1': { sv: "Den som är märkbart påverkad får inte serveras alkohol, vilken dryck det än är. Om han får stanna avgör ni efter hur han mår och uppför sig.", en: "Anyone noticeably intoxicated may not be served alcohol, whatever the drink. Whether he may stay is for you to judge by how he is and how he behaves." },
  'event.drunk.ok1': { sv: "Inget mer i kväll. Vatten går bra.", en: "Nothing more tonight. Water’s fine." },
  'event.drunk.q2': { sv: "Hur säger Mira det till honom?", en: "How does Mira tell him?" },
  'event.drunk.a2_1': { sv: "Högt nog att vännerna hör och kan hjälpa till", en: "Loud enough for his friends to hear and help" },
  'event.drunk.a2_2': { sv: "Lugnt och lågt, och bjuder på vatten och mat", en: "Calmly and quietly, offering water and food" },
  'event.drunk.a2_3': { sv: "Säger att baren stänger snart för kvällen", en: "Says the bar is closing soon for the night" },
  'event.drunk.a2_4': { sv: "Häller upp en lättöl utan att säga något", en: "Pours a low-alcohol beer without a word" },
  'event.drunk.why2': { sv: "Ett nej som ges lugnt och enskilt, med något i utbyte, tas emot bättre.", en: "A no given calmly and privately, with something in return, is taken better." },
  'event.drunk.ok2': { sv: "Ett glas vatten, och något att äta?", en: "A glass of water, and something to eat?" },
  'event.drunk.q3': { sv: "Hans vänner är stamgäster och vill beställa åt honom. Vad gör du?", en: "His friends are regulars and want to order for him. What do you do?" },
  'event.drunk.a3_1': { sv: "Serverar vännerna men ber dem inte ge honom något", en: "Serves the friends but asks them not to give him any" },
  'event.drunk.a3_2': { sv: "Säger nej, skriver upp tiden och erbjuder en taxi", en: "Says no, notes the time and offers a taxi" },
  'event.drunk.a3_3': { sv: "Säger nej och ber hela sällskapet gå för kvällen", en: "Says no and asks the whole party to leave for the night" },
  'event.drunk.a3_4': { sv: "Låter dem beställa, han har ju bara fått vatten", en: "Lets them order, he’s only had water since" },
  'event.drunk.why3': { sv: "Förbudet gäller oavsett vem som beställer. Att skriva upp tiden visar att ni gjort rätt.", en: "The ban applies whoever orders. Noting the time shows you did the right thing." },
  'event.drunk.near3_1': { sv: "Vännerna får serveras, men går glaset vidare till honom har ni serverat honom. Det måste du se.", en: "The friends may be served, but if the glass goes on to him you have served him. You have to watch for that." },
  'event.drunk.near3_3': { sv: "Tydligt, men vännerna har inte gjort något fel, och ni förlorar stamgäster.", en: "Clear, but the friends have done nothing wrong, and you lose regulars." },
  'event.drunk.ok3': { sv: "Jag skriver upp det: nekad {time}.", en: "I’ll write it down: refused at {time}." },
  'event.drunk.fail': { sv: "Jag tar det här.", en: "I’ll handle this." },

  // ---------- 4 · Tillsynen ----------
  'event.inspection.title': { sv: "Tillsynen", en: "The inspection" },
  'event.inspection.role': { sv: "Serveringsansvarig · ståbordet", en: "Serving supervisor · the high table" },
  'event.inspection.moment': { sv: "Två gäster vid ståbordet har inte rört sina glas på en stund. Nu visar de var sin legitimation för Per.", en: "Two guests at the high table haven’t touched their glasses for a while. Now they each show Per an ID card." },
  'event.inspection.caption': { sv: "Kommunen och polisen visar legitimation", en: "The council and the police show their ID" },
  'event.inspection.say.order': { sv: "Två mineralvatten, tack.", en: "Two mineral waters, please." },
  'event.inspection.say.council': { sv: "Jag är alkoholhandläggare på kommunens tillståndsenhet.", en: "I’m a licensing officer from the council’s licensing unit." },
  'event.inspection.say.police': { sv: "Och jag är från polisen. Vi gör tillsyn i kväll.", en: "And I’m from the police. We’re carrying out an inspection tonight." },
  'event.inspection.say.report': { sv: "Ni får vår rapport. Kommunen beslutar om eventuell påföljd.", en: "You’ll get our report. The council decides on any sanction." },
  'event.inspection.q1': { sv: "Vem ska finnas på plats under hela serveringstiden?", en: "Who must be on the premises throughout serving hours?" },
  'event.inspection.a1_1': { sv: "Någon som har gått kursen i ansvarsfull alkoholservering", en: "Someone who has done the responsible alcohol serving course" },
  'event.inspection.a1_2': { sv: "Bartendern, eftersom det är hon som häller upp", en: "The bartender, since she is the one pouring" },
  'event.inspection.a1_3': { sv: "Tillståndshavaren eller en anmäld serveringsansvarig", en: "The licence holder or a registered serving supervisor" },
  'event.inspection.a1_4': { sv: "Krögaren själv, varje kväll serveringen pågår", en: "The owner in person, every evening serving is on" },
  'event.inspection.why1': { sv: "Tillståndshavaren eller en anmäld serveringsansvarig ska finnas på plats hela serveringstiden. En kurs räcker inte, namnet ska stå på listan hos kommunen.", en: "The licence holder or a registered serving supervisor must be on the premises throughout serving hours. A course is not enough; the name must be on the council’s list." },
  'event.inspection.ok1': { sv: "Det är jag, Per. Jag står på listan i kväll.", en: "That’s me, Per. I’m on the list tonight." },
  'event.inspection.q2': { sv: "Vad visar du dem?", en: "What do you show them?" },
  'event.inspection.a2_1': { sv: "Tillståndet och personalliggaren för kvällen", en: "The licence and the staff register for tonight" },
  'event.inspection.a2_2': { sv: "Kassarapporten och kvittona från kvällen", en: "The till report and all of tonight’s receipts" },
  'event.inspection.a2_3': { sv: "Tillståndet och kursintygen för hela personalen", en: "The licence and course certificates for all staff" },
  'event.inspection.a2_4': { sv: "Tillståndet, ansvarslistan och egenkontrollen", en: "The licence, supervisor list and our own checks" },
  'event.inspection.why2': { sv: "Tillsynen gäller tillståndet och hur ni följer det: vem som är ansvarig och hur ni arbetar enligt egenkontrollen.", en: "The inspection is about the licence and how you follow it: who is responsible and how you work to the self-monitoring plan." },
  'event.inspection.ok2': { sv: "Här är tillståndet, listan och vår egenkontroll.", en: "Here’s the licence, the list and our self-monitoring plan." },
  'event.inspection.ok3': { sv: "Tack. Då har vi det vi behöver.", en: "Thank you. We have what we need." },
  'event.inspection.fail': { sv: "Vi skriver in det i rapporten.", en: "We’ll put that in the report." },

  // Steg 3, variant A · den nekade gästen (en gäst har nekats i kväll)
  'event.inspection.refused.q3': { sv: "Polisen nickar mot gästen vid baren som vinglade tidigare. Vad säger du?", en: "The police officer nods towards the guest at the bar who was unsteady earlier. What do you say?" },
  'event.inspection.refused.a3_1': { sv: "Säger att han bara har druckit vatten i kväll", en: "Says he has only been drinking water tonight" },
  'event.inspection.refused.a3_2': { sv: "Ber vännerna ta med honom hem innan de frågar", en: "Asks his friends to take him home before they ask" },
  'event.inspection.refused.a3_3': { sv: "Hänvisar till Mira, som var den som nekade honom i kväll", en: "Refers them to Mira, who was the one who refused him tonight" },
  'event.inspection.refused.a3_4': { sv: "Säger som det är: nekad {time}, och visar lappen", en: "Tells it straight: refused at {time}, shows the note" },
  'event.inspection.refused.a3_4_unnoted': { sv: "Säger som det är: nekad, men tiden skrevs inte upp", en: "Tells it straight: refused, but the time wasn’t noted" },
  'event.inspection.refused.why3': { sv: "Öppenhet och en anteckning väger tyngst inför tillsynen.", en: "Openness and a written note count for most in front of the inspectors." },
  'event.inspection.refused.why3_unnoted': { sv: "Ärligheten höll. Men utan tid kan ni inte visa när han nekades. Skriv alltid upp tiden.", en: "Honesty held. But without the time you can’t show when he was refused. Always note the time." },
  'event.inspection.refused.near3_3': { sv: "Mira vet mest, men det är du som är serveringsansvarig. Svaret ska komma från dig.", en: "Mira knows most, but you are the serving supervisor. The answer has to come from you." },
  'event.inspection.refused.ok3': { sv: "Han nekades {time}. Här är lappen.", en: "He was refused at {time}. Here’s the note." },
  'event.inspection.refused.ok3_unnoted': { sv: "Han nekades, men vi skrev inte upp tiden.", en: "He was refused, but we didn’t note the time." },

  // Steg 3, variant B · ålderskontroll (unga gäster i rummet)
  'event.inspection.age.q3': { sv: "Två unga gäster i lounge B beställer vin av Sara. Handläggaren tittar dit. Vad gör du?", en: "Two young guests in lounge B order wine from Sara. The licensing officer looks over. What do you do?" },
  'event.inspection.age.a3_1': { sv: "Frågar dem hur gamla de är och litar på svaret", en: "Asks how old they are and trusts the answer" },
  'event.inspection.age.a3_2': { sv: "Ber Sara be om legitimation innan hon häller", en: "Asks Sara to check ID before she pours" },
  'event.inspection.age.a3_3': { sv: "Ber om legitimation av alla i loungen, äldre också", en: "Asks everyone in the lounge for ID, older guests too" },
  'event.inspection.age.a3_4': { sv: "Litar på Sara, hon ser om någon är för ung", en: "Trusts Sara to spot anyone who is too young" },
  'event.inspection.age.why3': { sv: "Den som serverar ska vara säker på att gästen har fyllt 18. Är du osäker, be om legitimation.", en: "Whoever serves must be sure the guest is 18 or over. If you are unsure, ask for ID." },
  'event.inspection.age.near3_3': { sv: "Lagligt och säkert, men de äldre gästerna känner sig misstrodda. Fråga dem det gäller.", en: "Legal and safe, but the older guests feel mistrusted. Ask the ones it concerns." },
  'event.inspection.age.ok3': { sv: "Får jag se legitimation, tack?", en: "May I see some ID, please?" },

  // Steg 3, variant C · egenkontroll (standard)
  'event.inspection.selfcheck.q3': { sv: "Handläggaren bläddrar i egenkontrollen och frågar hur personalen vet vad som står i den. Vad svarar du?", en: "The licensing officer leafs through the self-monitoring plan and asks how the staff know what’s in it. What do you say?" },
  'event.inspection.selfcheck.a3_1': { sv: "Den ligger i pärmen vid kassan, där alla kan läsa", en: "It’s in the folder by the till, where everyone can read it" },
  'event.inspection.selfcheck.a3_2': { sv: "Alla har gått kursen i ansvarsfull servering", en: "Everyone has done the responsible serving course" },
  'event.inspection.selfcheck.a3_3': { sv: "Jag skrev den själv, så jag svarar för den", en: "I wrote it myself, so I answer for it" },
  'event.inspection.selfcheck.a3_4': { sv: "Alla nya går igenom den, och vi ser över den ofta", en: "Every new starter goes through it, and we review it often" },
  'event.inspection.selfcheck.why3': { sv: "Egenkontrollen ska vara känd av alla som serverar, inte bara finnas i en pärm.", en: "The self-monitoring plan must be known by everyone who serves, not just sit in a folder." },
  'event.inspection.selfcheck.near3_2': { sv: "Kursen är bra, men den handlar om lagen. Er egenkontroll är era egna rutiner.", en: "The course is good, but it covers the law. Your self-monitoring plan is your own routines." },
  'event.inspection.selfcheck.ok3': { sv: "Alla nya går igenom den med mig.", en: "Every new starter goes through it with me." },

  // Steg 3, variant D · kravet på mat (köket har slut på mat i kväll)
  'event.inspection.food.say.out': { sv: "Maten är slut för i kväll.", en: "We’re out of food for tonight." },
  'event.inspection.food.q3': { sv: "Handläggaren vill beställa något att äta. Kocken har just sagt att maten är slut. Vad gör du?", en: "The licensing officer wants to order something to eat. The chef has just said the food has run out. What do you do?" },
  'event.inspection.food.a3_1': { sv: "Säger att köket stänger tidigare än baren i kväll", en: "Says the kitchen closes earlier than the bar tonight" },
  'event.inspection.food.a3_2': { sv: "Ber kocken laga något enkelt av det som finns kvar", en: "Has the chef make something simple from what’s left" },
  'event.inspection.food.a3_3': { sv: "Bjuder på oliver och nötter från baren i stället", en: "Offers them olives and nuts from the bar instead" },
  'event.inspection.food.a3_4': { sv: "Är ärlig och pausar alkoholen tills det finns mat", en: "Tells it straight and pauses alcohol until there’s food" },
  'event.inspection.food.why3': { sv: "Lagad mat ska gå att beställa under hela serveringstiden. Ett enkelt utbud räcker, men snacks räknas inte.", en: "Cooked food must be available to order throughout serving hours. A simple choice is enough, but snacks don’t count." },
  'event.inspection.food.near3_4': { sv: "Lagligt och ärligt, men baren tappar kvällen. Köket kan nästan alltid laga något enkelt.", en: "Legal and honest, but the bar loses the evening. The kitchen can almost always make something simple." },
  'event.inspection.food.ok3': { sv: "Kocken gör en enkel rätt av det som finns.", en: "The chef will make a simple dish from what we have." },

  'evening.event.5.line.clean': { sv: "Tillståndet, egenkontrollen och anteckningen fanns på plats.", en: "The licence, the self-monitoring plan and the note were all in place." },
  'evening.event.5.line.unnoted': { sv: "Per sa som det var. Tiden hade inte skrivits upp, och det kom med i rapporten.", en: "Per told it as it was. The time hadn’t been noted, and that went into the report." },
  'evening.event.5.line.sanction': { sv: "Tillsynen fann brister. Kommunens beslut kommer med morgonens post.", en: "The inspection found shortcomings. The council’s decision comes with the morning post." },

  // ---------- 5 · Gästen vid passet ----------
  'event.kitchen.title': { sv: "Gästen vid passet", en: "The guest at the pass" },
  'event.kitchen.role': { sv: "Kocken · passet", en: "Chef · the pass" },
  'event.kitchen.moment': { sv: "En gäst reser sig från lounge A och går rakt mot köket. Vid passluckan frågar hon om hon får titta in.", en: "A guest gets up from lounge A and heads straight for the kitchen. At the hatch she asks if she may look inside." },
  'event.kitchen.caption': { sv: "Hon frågar vid passluckan", en: "She asks at the hatch" },
  'event.kitchen.say.ask': { sv: "Får jag titta in i köket?", en: "May I have a look in the kitchen?" },
  'event.kitchen.q1': { sv: "Vad gäller när en gäst vill in i ett restaurangkök?", en: "What applies when a guest wants to go into a restaurant kitchen?" },
  'event.kitchen.a1_1': { sv: "Att hon inte rör något och håller sig vid dörren", en: "That she touches nothing and stays by the door" },
  'event.kitchen.a1_2': { sv: "Skyddskläder, handtvätt och att någon följer med", en: "Protective clothing, hand-washing and an escort" },
  'event.kitchen.a1_3': { sv: "Att hon inte är sjuk, resten svarar kocken för", en: "That she isn’t ill; the chef answers for the rest" },
  'event.kitchen.a1_4': { sv: "Att det bara går när köket inte lagar mat", en: "That it’s only allowed when nothing is being cooked" },
  'event.kitchen.why1': { sv: "Köket är en livsmedelslokal. Den som går in följer samma hygienregler som personalen.", en: "The kitchen is food premises. Anyone going in follows the same hygiene rules as the staff." },
  'event.kitchen.ok1': { sv: "Förkläde och handtvätt först.", en: "Apron and hand-washing first." },
  'event.kitchen.q2': { sv: "Hur gör du det mitt i rusningen?", en: "How do you manage it in the middle of the rush?" },
  'event.kitchen.a2_1': { sv: "Ber Sara visa henne runt medan du lagar klart", en: "Asks Sara to show her round while you finish cooking" },
  'event.kitchen.a2_2': { sv: "Tar in henne direkt och visar stationerna", en: "Takes her straight in and shows her the stations" },
  'event.kitchen.a2_3': { sv: "Ber henne vänta och visar från dörren, i förkläde", en: "Asks her to wait, then shows her from the door in an apron" },
  'event.kitchen.a2_4': { sv: "Säger vänligt att köket inte tar emot gäster i kväll", en: "Says kindly that the kitchen isn’t taking visitors tonight" },
  'event.kitchen.why2': { sv: "Ett kort och tryggt ja slår både ett nej och ett kök i oordning.", en: "A short, safe yes beats both a no and a kitchen in disarray." },
  'event.kitchen.ok2': { sv: "En kort stund, från dörren.", en: "Just a moment, from the door." },
  'event.kitchen.q3': { sv: "Du känner igen henne: hon skriver om mat i Grythyttebladet. Vad gör du?", en: "You recognise her: she writes about food for Grythyttebladet. What do you do?" },
  'event.kitchen.a3_1': { sv: "Behandlar henne som alla andra och säger inget om det", en: "Treats her like everyone else and says nothing about it" },
  'event.kitchen.a3_2': { sv: "Erbjuder en rundtur efter servicen och en smakbit nu", en: "Offers a tour after service and a taste now" },
  'event.kitchen.a3_3': { sv: "Ber Elin ta särskild hand om henne resten av kvällen", en: "Asks Elin to look after her specially for the rest of the night" },
  'event.kitchen.a3_4': { sv: "Ber henne komma tillbaka en lugnare kväll för en visning", en: "Asks her to come back on a quieter night for a tour" },
  'event.kitchen.why3': { sv: "Samma regler för alla. Det du kan ge extra är tid, när köket har tid.", en: "The same rules for everyone. What you can give extra is time, when the kitchen has time." },
  'event.kitchen.near3_1': { sv: "Rättvist, men hon bad om något ni kan ge. Att inte svara på det är också ett nej.", en: "Fair, but she asked for something you can give. Not answering is a no as well." },
  'event.kitchen.near3_4': { sv: "Rimligt, men hon är här i kväll. Kom hon inte tillbaka, blev det inget.", en: "Reasonable, but she is here tonight. If she doesn’t come back, nothing comes of it." },
  'event.kitchen.ok3': { sv: "En rundtur efter servicen? Gärna!", en: "A tour after service? I’d love that!" },
  'event.kitchen.fail': { sv: "Vi tar det efter servicen.", en: "Let’s do it after service." },

  // ---------- Ersätter i leverans 1 (nexusStrings.varm.ts), eftersom händelserna nu spelas i vinbaren ----------
  'lesson.rocket.3.who': { sv: "Hovmästaren · lounge A", en: "Maître d’ · lounge A" },
  'lesson.when': { sv: "Kl. {time} i {place}", en: "{time} in {place}" },
  'lesson.principle': { sv: "Öppen låga bland gäster kräver fri väg, lågt grepp och lugnt tempo.", en: "An open flame among guests needs a clear path, a low grip and a calm pace." },
  'lesson.story': { sv: "Sara sprang med tårtan för att ljusen inte skulle hinna brinna ned. En gäst klev ned från en barstol framför henne, och ett ljus föll på loungebordet. Per tog över.", en: "Sara ran with the cake so the candles wouldn’t burn down. A guest stepped off a bar stool in front of her, and a candle fell on the lounge table. Per took over." },
  'lesson.yours.text': { sv: "Fort, så att ljusen inte hinner brinna ned", en: "Quickly, so the candles don’t have time to burn down" },
  'lesson.held.text': { sv: "Tänds vid luckan, bärs lågt och sakta i fri gång", en: "Lit at the hatch, carried low and slowly, path clear" }
};
