// d11Strings.ts — D11 ansiktsuttryck och gester. Alla texter som nycklar { sv, en } (brittisk engelska).
// ORDER 325: Designs fil (documentation/leveranser/nexus-leverans-2026-10-10-d11-ansikten-och-gester/), oförändrad.
// Situationernas namn (gm.sit.<id>) och varför (gm.why.<id>) hör till kartan, scene/gestureMap.ts.
export const D11_STRINGS: Record<string, { sv: string; en: string }> = {
  'ui.kicker': { sv: 'D11 · Ansikten och gester', en: 'D11 · Faces and gestures' },
  'ui.title': { sv: 'Läsa gästerna utan symboler', en: 'Reading the guests without symbols' },
  'ui.scenes': { sv: 'Skärmar', en: 'Screens' },
  'ui.cam': { sv: 'Kameran', en: 'Camera' }, 'ui.cam.script': { sv: 'Manus', en: 'Script' }, 'ui.cam.game': { sv: 'Spelets, 24 m', en: 'Game, 24 m' },
  'ui.tempo': { sv: 'Tempo (styrkan)', en: 'Tempo (strength)' }, 'ui.tempo.calm': { sv: 'Lugn', en: 'Calm' }, 'ui.tempo.normal': { sv: 'Normal', en: 'Normal' }, 'ui.tempo.stressed': { sv: 'Stressad', en: 'Stressed' },
  'ui.symbols': { sv: 'Symbolerna', en: 'Symbols' }, 'ui.symbols.off': { sv: 'Av', en: 'Off' }, 'ui.symbols.on': { sv: 'På', en: 'On' },
  'ui.lupe': { sv: 'Luppen', en: 'Loupe' }, 'ui.lupe.why': { sv: 'Huvudena i skärmens egna pixlar, fem gånger förstorade utan utjämning. Det är det spelaren ser.', en: 'The heads in the screen’s own pixels, enlarged five times without smoothing. This is what the player sees.' },
  'ui.play': { sv: 'Spela', en: 'Play' }, 'ui.pause': { sv: 'Paus', en: 'Pause' },
  'ui.size': { sv: 'Skärmstorlek', en: 'Screen size' },
  'ui.distance': { sv: 'Kameran', en: 'Camera' }, 'ui.head': { sv: 'huvudet', en: 'head' },
  'ui.lod': { sv: 'Ansiktet', en: 'Face' }, 'ui.lod.near': { sv: 'nära', en: 'near' }, 'ui.lod.far': { sv: 'långt', en: 'far' }, 'ui.lod.none': { sv: 'inget', en: 'none' },
  'ui.faces': { sv: 'De fem ansiktena', en: 'The five faces' },
  'ui.faces.why': { sv: 'Överst nära (under 12 m), under långt (9–42 m). Samma uttryck, raka streck och fyrkantiga ögon. Det långa sitter högre på huvudet så att det syns från 50°.', en: 'Top: near (under 12 m). Below: far (9–42 m). The same expressions, straight strokes and square eyes. The far face sits higher on the head so that it shows from 50°.' },
  'ui.map': { sv: 'Kartan: stämning och situation', en: 'The map: mood and situation' },
  'ui.map.mood': { sv: 'Stämningens egna gester', en: 'The mood’s own gestures' },
  'ui.map.sit': { sv: 'Situationerna', en: 'Situations' },
  'ui.map.seated': { sv: 'Sittande', en: 'Seated' }, 'ui.map.standing': { sv: 'Stående', en: 'Standing' },
  'ui.record': { sv: 'Spela in video', en: 'Record video' }, 'ui.recording': { sv: 'Spelar in …', en: 'Recording …' },

  'scene.faces': { sv: 'Ansiktena på krogens nivå', en: 'Faces at venue level' },
  'scene.guests': { sv: 'Gästernas gester', en: 'Guest gestures' },
  'scene.staff': { sv: 'Personalen', en: 'Staff' },
  'scene.truck': { sv: 'Vid vagnen', en: 'At the truck' },
  'scene.street': { sv: 'Gatan', en: 'The street' },
  'scene.map': { sv: 'Kartan i rummet', en: 'The map in the room' },
  'group.winebar': { sv: 'Vinbaren', en: 'The wine bar' }, 'group.truck': { sv: 'Foodtrucken', en: 'The food truck' },

  'mood.delighted': { sv: 'Glad', en: 'Delighted' }, 'mood.content': { sv: 'Nöjd', en: 'Content' }, 'mood.waiting': { sv: 'Väntar', en: 'Waiting' }, 'mood.impatient': { sv: 'Otålig', en: 'Impatient' }, 'mood.displeased': { sv: 'Missnöjd', en: 'Displeased' },

  'ch.face.24': { sv: '24 m, krogens nivå', en: '24 m, venue level' },
  'why.face.24': { sv: 'Huvudet är 9 px (1280) och 12 px (1440). Öppen mun, mörka bryn och munnens riktning syns. Nöjd och väntar skiljs på kroppen.', en: 'The head is 9 px (1280) and 12 px (1440). An open mouth, dark brows and the mouth’s direction show. Content and waiting are told apart by the body.' },
  'ch.face.14': { sv: '14 m, raketens avstånd', en: '14 m, rocket distance' },
  'why.face.14': { sv: 'Det långa ansiktet fullt. Alla fem går att skilja åt.', en: 'The far face at full strength. All five can be told apart.' },
  'ch.face.9': { sv: '9 m, skalen byter', en: '9 m, the shells swap' },
  'why.face.9': { sv: 'Mellan 12 och 9 m tonar det långa ansiktet över i det nära. Samma uttryck, så inget hoppar.', en: 'Between 12 and 9 m the far face fades into the near one. The same expression, so nothing jumps.' },
  'ch.face.7': { sv: '7 m, konsekvensögonblicket', en: '7 m, the consequence moment' },
  'why.face.7': { sv: 'Det nära ansiktet, som i D1, men kantigt.', en: 'The near face, as in D1, but angular.' },

  'ch.all.game': { sv: 'Alla från spelets kamera', en: 'Everyone from the game camera' },
  'why.all.game': { sv: '24 m, utan symboler. Gesterna är förstorade så att de läses härifrån.', en: '24 m, without symbols. The gestures are enlarged so they read from here.' },
  'ch.g.wave': { sv: 'Vinka till servitören', en: 'Wave to the server' }, 'why.g.wave': { sv: 'Nöjd. Ett finger och handen upp: vi vill beställa. Otålig har en egen, större vinkning.', en: 'Content. A finger and the hand up: we would like to order. Impatient has its own, bigger wave.' },
  'ch.g.watch': { sv: 'Titta på klockan', en: 'Check the watch' }, 'why.g.watch': { sv: 'Väntar. Handleden upp, blicken ned och sedan ut efter personalen.', en: 'Waiting. Wrist up, eyes down, then out towards the staff.' },
  'ch.g.leanTalk': { sv: 'Luta sig fram och prata', en: 'Lean in and talk' }, 'why.g.leanTalk': { sv: 'Nöjd. Fram över bordet, handen ritar i luften, huvudet lite på sned.', en: 'Content. Over the table, the hand drawing in the air, head slightly tilted.' },
  'ch.g.laugh': { sv: 'Skratta', en: 'Laugh' }, 'why.g.laugh': { sv: 'Glad. Huvudet bakåt, axlarna studsar, sedan framåt.', en: 'Delighted. Head back, shoulders bouncing, then forwards.' },
  'ch.g.cheers': { sv: 'Skåla', en: 'Raise a glass' }, 'why.g.cheers': { sv: 'Glad. Glaset över huvudhöjd mot bordets mitt.', en: 'Delighted. The glass above head height towards the middle of the table.' },
  'ch.g.smell': { sv: 'Lukta på vinet', en: 'Smell the wine' }, 'why.g.smell': { sv: 'Nöjd. Snurra, näsan i glaset, sedan en klunk. Ändrar inte stämningen.', en: 'Content. Swirl, nose in the glass, then a sip. Does not change the mood.' },
  'ch.g.menu': { sv: 'Peka i menyn', en: 'Point at the menu' }, 'why.g.menu': { sv: 'Nöjd. Menyn i ena handen, pekfingret på raden, blicken på den som tar beställningen.', en: 'Content. The menu in one hand, a finger on the line, eyes on whoever takes the order.' },
  'ch.g.push': { sv: 'Knuffa undan tallriken', en: 'Push the plate away' }, 'why.g.push': { sv: 'Missnöjd. En raksträckt arm, sedan armarna i kors.', en: 'Displeased. A straight arm, then arms crossed.' },
  'ch.g.shrug': { sv: 'Rycka på axlarna', en: 'Shrug' }, 'why.g.shrug': { sv: 'Väntar. Handflatorna upp, kroppen lyfts, huvudet på sned. Halvt grepp och det som är slut.', en: 'Waiting. Palms up, the body lifts, head tilted. A half grip, and things that have run out.' },
  'ch.g.arms': { sv: 'Korsa armarna', en: 'Cross the arms' }, 'why.g.arms': { sv: 'Missnöjd. Bålen tillbaka från bordet, blicken bort, en suck per varv.', en: 'Displeased. Body back from the table, eyes away, a sigh each cycle.' },
  'ch.g.bite': { sv: 'Nicka efter första smaken', en: 'Nod after the first taste' }, 'why.g.bite': { sv: 'Nöjd: gaffeln till munnen, tugga, två nickar. Glad (stressat tempo): tre nickar och ett lyft.', en: 'Content: fork to the mouth, chew, two nods. Delighted (stressed tempo): three nods and a lift.' },

  'ch.s.tray': { sv: 'Bära bricka', en: 'Carry a tray' }, 'why.s.tray': { sv: 'Brickan i axelhöjd på vänster hand, glasen på. Två eller fler till samma bord.', en: 'The tray at shoulder height on the left hand, glasses on it. Two or more for the same table.' },
  'ch.s.pour': { sv: 'Hälla upp', en: 'Pour' }, 'why.s.pour': { sv: 'Flaskan tippas 1,9 rad, etiketten mot gästen.', en: 'The bottle tips 1.9 rad, label towards the guest.' },
  'ch.s.wipe': { sv: 'Torka av', en: 'Wipe down' }, 'why.s.wipe': { sv: 'Fram över bordet, två breda svep per varv. Efter att sällskapet gått.', en: 'Over the table, two wide sweeps per cycle. After the party has left.' },
  'ch.s.listen': { sv: 'Lyssna med lutat huvud', en: 'Listen with the head tilted' }, 'why.s.listen': { sv: 'Huvudet på sned mot gästen och bålen fram. Ny i riggen: huvudets lutning.', en: 'Head tilted towards the guest, body forwards. New in the rig: head tilt.' },
  'ch.s.point': { sv: 'Peka mot ett bord', en: 'Point to a table' }, 'why.s.point': { sv: 'Armen i axelhöjd, bålen och huvudet med.', en: 'The arm at shoulder height, body and head with it.' },

  'ch.tr.game': { sv: 'Vagnen från 16 m', en: 'The truck from 16 m' }, 'why.tr.game': { sv: 'Kön, ståborden och luckan. Stående varianter av vinbarens gester.', en: 'The queue, the high tables and the hatch. Standing versions of the wine bar gestures.' },
  'ch.tr.hatch': { sv: 'Vinka vid luckan', en: 'Wave at the hatch' }, 'why.tr.hatch': { sv: 'Handen över huvudet, två korta vinkningar, sedan fram och prata.', en: 'Hand above the head, two short waves, then lean in and talk.' },
  'ch.tr.listen': { sv: 'Grillaren lyssnar', en: 'The griller listens' }, 'why.tr.listen': { sv: 'Huvudet på sned i luckan. Syns ovanför disken.', en: 'Head tilted in the hatch. Shows above the counter.' },
  'ch.tr.watch': { sv: 'Klockan i kön', en: 'The watch in the queue' }, 'why.tr.watch': { sv: 'Väntar. Ersätter D9:s guest.checkWatch i kön (samma namn som det sittande).', en: 'Waiting. Replaces D9’s guest.checkWatch in the queue (same name as the seated one).' },
  'ch.tr.arms': { sv: 'Armarna i kors i kön', en: 'Arms crossed in the queue' }, 'why.tr.arms': { sv: 'Missnöjd. Bålen bakåt, blicken bort från luckan.', en: 'Displeased. Body back, eyes away from the hatch.' },
  'ch.tr.shrug': { sv: 'Rycka på axlarna i kön', en: 'Shrug in the queue' }, 'why.tr.shrug': { sv: 'Väntar. Korven är slut, eller nästan på frågekortet.', en: 'Waiting. The sausages have run out, or close on the question card.' },
  'ch.tr.talk': { sv: 'Prata vid ståbordet', en: 'Talk at the high table' }, 'why.tr.talk': { sv: 'Nöjd. Underarmen på bordet, handen ritar.', en: 'Content. Forearm on the table, the hand drawing.' },
  'ch.tr.laugh': { sv: 'Skratta vid ståbordet', en: 'Laugh at the high table' }, 'why.tr.laugh': { sv: 'Glad, stressat tempo: tydligt från 24 m.', en: 'Delighted, stressed tempo: clear from 24 m.' },
  'ch.tr.bite': { sv: 'Första tuggan', en: 'The first bite' }, 'why.tr.bite': { sv: 'Nöjd. Handen till munnen, tugga, två nickar.', en: 'Content. Hand to the mouth, chew, two nods.' },
  'ch.tr.wipe': { sv: 'Nils torkar ståbordet', en: 'Nils wipes the high table' }, 'why.tr.wipe': { sv: 'Samma klipp som i vinbaren, för ståbordets 1,05 m.', en: 'The same clip as in the wine bar, for the high table’s 1.05 m.' },

  'ch.st.game': { sv: 'Gatan från 24 m', en: 'The street from 24 m' }, 'why.st.game': { sv: 'Sex som går förbi vagnen. Gångarten säger vem de är.', en: 'Six people passing the truck. The gait says who they are.' },
  'ch.st.street42': { sv: 'Gatans nivå, 42 m', en: 'Street level, 42 m' }, 'why.st.street42': { sv: 'Inga ansikten här. Farten, lutningen och sällskapet läses.', en: 'No faces here. Speed, lean and company read.' },
  'ch.st.calm': { sv: 'Promenera', en: 'Stroll' }, 'why.st.calm': { sv: 'Upprätt, korta armsvängar, blicken längs fasaderna.', en: 'Upright, short arm swings, eyes along the façades.' },
  'ch.st.hurry': { sv: 'Brådskande', en: 'In a hurry' }, 'why.st.hurry': { sv: 'Bålen fram, huvudet ned, pumpande armar, 1,45 gånger farten.', en: 'Body forwards, head down, pumping arms, 1.45 times the speed.' },
  'ch.st.child': { sv: 'Med barn', en: 'With a child' }, 'why.st.child': { sv: 'Hand i hand, korta steg, blicken ned mot barnet.', en: 'Hand in hand, short steps, eyes down to the child.' },
  'ch.st.dog': { sv: 'Med hund', en: 'With a dog' }, 'why.st.dog': { sv: 'Kopplet i höger hand, hunden 0,95 m före, ett ryck i kopplet ibland.', en: 'The lead in the right hand, the dog 0.95 m ahead, a tug on the lead now and then.' },
  'ch.st.look': { sv: 'Stanna och titta', en: 'Stop and look' }, 'why.st.look': { sv: 'Vid skylten: vänder sig, handen till hakan, pekar mot luckan, går vidare.', en: 'At the sign: turns, hand to the chin, points at the hatch, walks on.' },
  'ch.st.greet': { sv: 'Hälsa på någon', en: 'Greet someone' }, 'why.st.greet': { sv: 'Handen högt på håll, ett steg fram, handslag och nick.', en: 'Hand high from a distance, a step forwards, handshake and nod.' },

  'ch.map.delighted': { sv: 'Glad', en: 'Delighted' }, 'why.map.delighted': { sv: 'Skratt, skålar och prat. Öppna munnar.', en: 'Laughter, raised glasses and talk. Open mouths.' },
  'ch.map.content': { sv: 'Nöjd', en: 'Content' }, 'why.map.content': { sv: 'Prat och nickar. Lugnast att se på.', en: 'Talk and nods. The calmest to look at.' },
  'ch.map.waiting': { sv: 'Väntar', en: 'Waiting' }, 'why.map.waiting': { sv: 'Klockor och axelryckningar, blickar mot personalen.', en: 'Watches and shrugs, glances at the staff.' },
  'ch.map.impatient': { sv: 'Otålig', en: 'Impatient' }, 'why.map.impatient': { sv: 'Armar i luften. Syns från andra sidan rummet.', en: 'Arms in the air. Visible from across the room.' },
  'ch.map.displeased': { sv: 'Missnöjd', en: 'Displeased' }, 'why.map.displeased': { sv: 'Armar i kors och tallrikar som skjuts undan. Mörka bryn.', en: 'Crossed arms and plates pushed away. Dark brows.' },

  'gm.read.delighted': { sv: 'Från 24 m: armar över huvudet, öppen mun.', en: 'From 24 m: arms above the head, open mouth.' },
  'gm.read.content': { sv: 'Från 24 m: framåtlutad mot sällskapet, munnen uppåt.', en: 'From 24 m: leaning in towards the party, mouth up.' },
  'gm.read.waiting': { sv: 'Från 24 m: handleden upp, huvudet vänt mot personalen.', en: 'From 24 m: wrist up, head turned towards the staff.' },
  'gm.read.impatient': { sv: 'Från 24 m: en arm rakt upp, mörka bryn.', en: 'From 24 m: one arm straight up, dark brows.' },
  'gm.read.displeased': { sv: 'Från 24 m: armarna i kors, tillbakalutad, mörka bryn.', en: 'From 24 m: arms crossed, leaning back, dark brows.' },

  'gm.sit.readyToOrder': { sv: 'Redo att beställa, ingen personal i närheten', en: 'Ready to order, no staff nearby' },
  'gm.sit.ordering': { sv: 'Beställningen tas', en: 'The order is being taken' },
  'gm.sit.winePoured': { sv: 'Vinet är upphällt', en: 'The wine has been poured' },
  'gm.sit.firstBite': { sv: 'Första tuggan', en: 'The first bite' },
  'gm.sit.firstBiteGreat': { sv: 'Första tuggan, över förväntan', en: 'The first bite, beyond expectation' },
  'gm.sit.dishBelow': { sv: 'Rätten under förväntan', en: 'The dish below expectation' },
  'gm.sit.waitedLong': { sv: 'Väntat länge utan kontakt', en: 'Waited a long time with no contact' },
  'gm.sit.waitedTooLong': { sv: 'Väntat för länge, personalen syns', en: 'Waited too long, staff in sight' },
  'gm.sit.talking': { sv: 'Sällskapet pratar', en: 'The party is talking' },
  'gm.sit.joke': { sv: 'Någon skämtar', en: 'Someone tells a joke' },
  'gm.sit.drinksArrive': { sv: 'Glasen har kommit, eller något firas', en: 'The glasses have arrived, or something is being celebrated' },
  'gm.sit.halfGrip': { sv: 'Halvt grepp, eller nästan på kortet', en: 'Half grip, or close on the card' },
  'gm.sit.soldOut': { sv: 'Det gästen ville ha är slut', en: 'What the guest wanted has run out' },
  'gm.sit.wrongWitnessed': { sv: 'Såg ett fel svar, eller kylan i kön', en: 'Saw a wrong answer, or the cold in the queue' },
  'gm.sit.twoOrMore': { sv: 'Två eller fler till samma bord', en: 'Two or more for the same table' },
  'gm.sit.pour': { sv: 'Flaskan vid bordet, tomt glas', en: 'The bottle at the table, an empty glass' },
  'gm.sit.tableLeft': { sv: 'Sällskapet har gått', en: 'The party has left' },
  'gm.sit.guestSpeaks': { sv: 'En gäst pratar med personalen', en: 'A guest speaks to the staff' },
  'gm.sit.seatParty': { sv: 'Ett sällskap visas till bordet', en: 'A party is shown to the table' },
  'gm.sit.stroll': { sv: 'Går förbi utan ärende', en: 'Passing by with no errand' },
  'gm.sit.hurry': { sv: 'Regn, sent, eller bussen', en: 'Rain, late, or the bus' },
  'gm.sit.withChild': { sv: 'Par med barn', en: 'A couple with a child' },
  'gm.sit.withDog': { sv: 'Med hund', en: 'With a dog' },
  'gm.sit.lookAt': { sv: 'Nära en skylt eller ett upplyst fönster', en: 'Near a sign or a lit window' },
  'gm.sit.meetKnown': { sv: 'Två bekanta möts', en: 'Two acquaintances meet' },
  'gm.who.guest': { sv: 'Gäst', en: 'Guest' }, 'gm.who.staff': { sv: 'Personal', en: 'Staff' }, 'gm.who.passer': { sv: 'Förbipasserande', en: 'Passer-by' }
};
