// d6Strings.ts — D6 del 2: avsändarna, teckenförklaringen, kurskortet, Byn just nu och det låsta i början.
// { sv, en }, brittisk engelska. Inga speltal: {loan}, {delta}, {score}, {max}, {cost}, {have}, {missing} och {n}
// kommer från balance.ts eller sim-lagret. Talen i prototypen är exempel.
export const D6_STRINGS: Record<string, { sv: string; en: string }> = {
  // ----- avsändarna -----
  'sender.asa': { sv: 'Intendent Åsa', en: 'Curator Åsa' },
  'sender.asa.sub': { sv: 'Campus', en: 'Campus' },
  'sender.bank': { sv: 'Banken', en: 'The bank' },
  'sender.bank.sub': { sv: 'Lån och satsningar', en: 'Loans and investments' },
  'sender.per': { sv: 'Per', en: 'Per' },
  'sender.per.sub': { sv: 'Hovmästare', en: 'Head waiter' },
  'sender.village': { sv: 'Byn', en: 'The village' },
  'sender.village.sub': { sv: 'Recensionerna', en: 'The reviews' },
  'sender.house': { sv: 'Måltidens hus', en: 'Måltidens hus' },
  'sender.house.sub': { sv: 'Prov och kurser', en: 'Tests and courses' },
  'sender.staff': { sv: '{name}, {role}', en: '{name}, {role}' },
  'role.host': { sv: 'hovmästare', en: 'head waiter' },
  'role.waiter': { sv: 'servitör', en: 'waiter' },
  'role.sommelier': { sv: 'sommelier', en: 'sommelier' },
  'role.bartender': { sv: 'bartender', en: 'bartender' },
  'role.cook': { sv: 'kock', en: 'cook' },
  'role.dishwasher': { sv: 'diskare', en: 'kitchen porter' },
  'role.dj': { sv: 'DJ', en: 'DJ' },
  'msg.asa': { sv: 'Bra. Nu vet du hur ett prov går till. I morgon kan du pröva en riktig kväll.', en: 'Good. Now you know how a test works. Tomorrow you can try a real evening.' },
  'msg.bank': { sv: 'Vi har sett ditt första prov. Du kan nu låna upp till {loan} till din första satsning.', en: 'We have seen your first test. You can now borrow up to {loan} for your first investment.' },
  'msg.per': { sv: 'Lounge B har väntat länge på notan. Jag tar den om du vill.', en: 'Lounge B has been waiting a long time for the bill. I can take it if you like.' },
  'msg.village': { sv: 'Tre nya recensioner i morse. Ryktet på nivån Enkel {delta}.', en: 'Three new reviews this morning. Reputation at the Simple level {delta}.' },
  'msg.house': { sv: 'Ditt prov i Stensöta är rättat: {score} av {max}. Du har fått brons.', en: 'Your test in Stensöta has been marked: {score} out of {max}. You have earned bronze.' },
  'msg.staff': { sv: 'Bord fyra frågar efter vinlistan.', en: 'Table four is asking for the wine list.' },
  'msg.next': { sv: 'Vidare', en: 'Continue' },
  'msg.open': { sv: 'Öppna', en: 'Open' },
  'msg.later': { sv: 'Sedan', en: 'Later' },

  'asa.line.welcome': { sv: 'Välkommen till Grythyttan. Jag kommer från Campus och följer dig i dag. Banken lånar inte ut något förrän den har sett vad du kan, så vi börjar med att öva. Öppna Måltidens hus och öva i Stensöta, där sommelierna håller till. Inget står på spel.', en: 'Welcome to Grythyttan. I’m from Campus and I’ll be with you today. The bank won’t lend you anything until it has seen what you can do, so we start by practising. Open the House of the Meal and practise in Stensöta, where the sommeliers are. Nothing is at stake.' },
  'asa.line.unlock': { sv: 'Nu har du visat vad du kan. Banken lyssnar, och du kan börja satsa.', en: 'Now you’ve shown what you can do. The bank is listening, and you can start to invest.' },

  // ----- teckenförklaringen -----
  'legend.title': { sv: 'Symbolerna', en: 'The symbols' },
  'legend.staff': { sv: 'Personalen', en: 'The staff' },
  'legend.guests': { sv: 'Gästerna', en: 'The guests' },
  'legend.role': { sv: 'Rollen', en: 'Role' },
  'legend.role.why': { sv: 'Ringen under figuren. Färgen är rollen.', en: 'The ring under the figure. The colour is the role.' },
  'legend.stamina': { sv: 'Orken', en: 'Stamina' },
  'legend.stamina.why': { sv: 'Den mörka ringen utanför. Fyllda bågar är det som är kvar.', en: 'The dark ring outside. Filled arcs are what is left.' },
  'legend.wellbeing': { sv: 'Trivseln', en: 'Morale' },
  'legend.wellbeing.why': { sv: 'Den fyrkantiga plattan. Lågan visar hur hen trivs.', en: 'The square plate. The flame shows how they are getting on.' },
  'legend.mood': { sv: 'Stämningen', en: 'Mood' },
  'legend.mood.why': { sv: 'Den runda plattan över bordet. Ljus är bra, mörk är dåligt.', en: 'The round plate above the table. Light is good, dark is bad.' },
  'legend.fresh': { sv: 'Pigg', en: 'Fresh' },
  'legend.tired': { sv: 'Trött', en: 'Tired' },
  'legend.spent': { sv: 'Slut', en: 'Spent' },
  'legend.thriving': { sv: 'Trivs', en: 'Thriving' },
  'legend.okay': { sv: 'Lagom', en: 'Getting by' },
  'legend.low': { sv: 'Trivs inte', en: 'Unhappy' },
  'mood.delighted': { sv: 'Glad', en: 'Delighted' },
  'mood.content': { sv: 'Nöjd', en: 'Content' },
  'mood.waiting': { sv: 'Väntar', en: 'Waiting' },
  'mood.impatient': { sv: 'Otålig', en: 'Impatient' },
  'mood.displeased': { sv: 'Missnöjd', en: 'Displeased' },
  'legend.hint': { sv: 'S visar och döljer', en: 'S shows and hides' },
  'legend.fold': { sv: 'Dölj', en: 'Hide' },
  'rules.title': { sv: 'Spelets regler', en: 'Rules of the game' },
  'rules.tab.symbols': { sv: 'Symbolerna', en: 'The symbols' },
  'rules.tab.knowing': { sv: 'Tre sätt att kunna', en: 'Three ways of knowing' },
  'rules.tab.evening': { sv: 'Kvällen', en: 'The evening' },
  'rules.tab.path': { sv: 'Din väg', en: 'Your path' },
  'rules.close': { sv: 'Stäng', en: 'Close' },
  'rules.lead': { sv: 'Det här betyder ringarna och plattorna i rummet. I statusläget (S) syns de för alla.', en: 'This is what the rings and plates in the room mean. In status mode (S) they show for everyone.' },

  // ----- kurskortet -----
  'course.list': { sv: 'Kurser', en: 'Courses' },
  'course.kicker': { sv: 'Kurs i Måltidens hus', en: 'Course at Måltidens hus' },
  'course.title': { sv: 'Sommeliern säljer in en flaska', en: 'The sommelier sells a bottle' },
  'course.row.teaches': { sv: 'Lär ut', en: 'Teaches' },
  'course.row.gives': { sv: 'Ger', en: 'Gives' },
  'course.row.when': { sv: 'Gäller', en: 'Applies' },
  'course.row.needs': { sv: 'Kräver', en: 'Needs' },
  'course.teaches': { sv: 'Sommeliern lär sig sälja in en hel flaska.', en: 'The sommelier learns to sell a whole bottle.' },
  'course.gives': { sv: 'Vid loungerna säger fler ja till en flaska i stället för glas.', en: 'At the lounges, more guests say yes to a bottle instead of glasses.' },
  'course.when': { sv: 'Från i morgon kväll.', en: 'From tomorrow evening.' },
  'course.req.bronze': { sv: 'Brons i Stensöta', en: 'Bronze in Stensöta' },
  'course.req.bronze.inline': { sv: 'brons i Stensöta', en: 'bronze in Stensöta' },
  'course.req.silver': { sv: 'Silver i Stensöta', en: 'Silver in Stensöta' },
  'course.req.met': { sv: 'uppfyllt', en: 'met' },
  'course.req.missing': { sv: 'saknas', en: 'missing' },
  'course.cost': { sv: 'Kostar {cost} krediter · du har {have}', en: 'Costs {cost} credits · you have {have}' },
  'course.buy': { sv: 'Gå kursen', en: 'Take the course' },
  'course.short': { sv: 'Du behöver {missing} krediter till', en: 'You need {missing} more credits' },
  'course.needsMedal': { sv: 'Kräver {medal}', en: 'Needs {medal}' },
  'course.state.ok': { sv: 'Allt finns', en: 'All met' },
  'course.state.credits': { sv: 'Krediterna räcker inte', en: 'Not enough credits' },
  'course.state.medal': { sv: 'Medaljen saknas', en: 'Medal missing' },

  // ----- Byn just nu -----
  'now.title': { sv: 'Byn just nu', en: 'The village right now' },
  'now.time': { sv: 'kl. {time}', en: '{time}' },
  'now.guests': { sv: 'gäster', en: 'guests' },
  'now.you': { sv: 'Du', en: 'You' },
  'now.lead.other': { sv: '{leader} drar flest gäster i kväll. Du är {place}.', en: '{leader} has the most guests tonight. You are {place}.' },
  'now.lead.you': { sv: 'Du drar flest gäster i kväll. {second} är tvåa.', en: 'You have the most guests tonight. {second} is second.' },
  'now.up': { sv: 'fler än för en kvart sedan', en: 'more than a quarter of an hour ago' },
  'now.down': { sv: 'färre än för en kvart sedan', en: 'fewer than a quarter of an hour ago' },
  'now.strip': { sv: 'Du är {place} · {n} gäster', en: 'You are {place} · {n} guests' },
  'now.truck': { sv: 'vagn', en: 'truck' },
  'now.yours': { sv: 'din vinbar', en: 'your wine bar' },

  // ----- det låsta i början -----
  'start.kicker': { sv: 'Första morgonen', en: 'The first morning' },
  'start.kicker.after': { sv: 'Efter första provet', en: 'After the first test' },
  'start.today': { sv: 'I dag', en: 'Today' },
  'start.practise': { sv: 'Öva i Måltidens hus', en: 'Practise at Måltidens hus' },
  'start.practise.sub': { sv: 'Inget står på spel', en: 'Nothing is at stake' },
  'start.test': { sv: 'Gör ett prov', en: 'Take a test' },
  'start.test.sub': { sv: 'Ger kunskapskrediter', en: 'Earns knowledge credits' },
  'start.invest': { sv: 'Satsa', en: 'Invest' },
  'start.invest.sub': { sv: 'Banken lånar ut till kvällen', en: 'The bank lends for the evening' },
  'start.shop': { sv: 'Butiken', en: 'The shop' },
  'start.shop.sub': { sv: 'Förmågor till nästa kväll', en: 'Abilities for the next evening' },
  'start.stand': { sv: 'Stå för ditt svar', en: 'Stand by your answer' },
  'start.stand.sub': { sv: 'Kvitt eller dubbelt i kväll', en: 'Double or quits tonight' },
  'start.locked': { sv: 'Öppnas när du klarat ditt första prov', en: 'Opens when you have passed your first test' },
  'start.new': { sv: 'Öppet nu', en: 'Open now' },

};
