// dinVagStrings.ts — Designs D7 (nexus-leverans-2026-10-06-din-vag/dinVagStrings.ts) med tillägget
// 2026-10-07 (dinVagStrings.tillagg.ts) inslaget, och de fyra borttagna nycklarna (fika.right, fika.wrong,
// fika.held, fika.two) borta. { sv, en }, brittisk engelska. Prototypens ram (ui.*, sc.*, dv.why.*, klipp-
// och jämförelsereglagen) och exemplen (venue.truckName, venue.name, review.sample.q) är inte spelartext och
// är utelämnade, liksom fikats exempeldilemma (fika.q, fika.a*, fika.why.*; dilemmana är Codes, ORDER 316)
// och prototypens förklaringar av ombyggnaden (refit.c.*). asa.name står kvar som i D6 (Intendent Åsa).
// ORDER 315b del 2: asa.row.rep följer Anders beslut (BESLUT 2026-10-07 del 2, fråga 1: ryktet följer med
// oförändrat), inte D7:s "Ryktet börjar om till hälften".
export const DIN_VAG_STRINGS: Record<string, { sv: string; en: string }> = {
  'venue.kind.truck': { sv: 'Svensk grill', en: 'Swedish grill' },
  'truck.served': { sv: 'Serverade i kväll', en: 'Served tonight' },
  'path.title': { sv: 'Din väg', en: 'Your path' },
  'path.sub': { sv: 'Från vagnen på torget till stjärnan', en: 'From the truck on the square to the star' },
  'path.step.truck': { sv: 'Food truck', en: 'Food truck' },
  'path.step.winebar': { sv: 'Vinbar', en: 'Wine bar' },
  'path.step.bistro': { sv: 'Bistro', en: 'Bistro' },
  'path.step.brewpub': { sv: 'Ölkrog', en: 'Brewpub' },
  'path.step.restaurant': { sv: 'Restaurang', en: 'Restaurant' },
  'path.step.club': { sv: 'Nattklubb', en: 'Nightclub' },
  'path.step.inn': { sv: 'Gästgiveri', en: 'Coaching inn' },
  'path.step.star': { sv: 'Stjärnkrogen', en: 'The starred restaurant' },
  'path.here': { sv: 'Du är här', en: 'You are here' },
  'path.done': { sv: 'Klart', en: 'Done' },
  'path.later': { sv: 'Kommer senare', en: 'Coming later' },
  'path.next': { sv: 'Nästa steg', en: 'Next step' },
  'path.req.cash': { sv: 'Kassa', en: 'Cash' },
  'path.req.rep': { sv: 'Rykte', en: 'Reputation' },
  'path.req.medal': { sv: 'Medalj', en: 'Medal' },
  'path.req.of': { sv: '{have} av {need}', en: '{have} of {need}' },
  'path.req.met': { sv: 'Klart', en: 'Met' },
  'path.req.left': { sv: 'Inte klart', en: 'Not met yet' },
  'path.offer': { sv: 'När alla tre är klara kommer Åsa förbi med ett erbjudande.', en: 'When all three are met, Åsa comes by with an offer.' },
  'path.back': { sv: 'Tillbaka', en: 'Back' },
  'asa.kicker': { sv: 'Ett erbjudande', en: 'An offer' },
  'asa.role': { sv: 'Har nycklarna till huset vid torget', en: 'Holds the keys to the building on the square' },
  'asa.line': { sv: '”Jag har pratat med den som äger huset. Vinbaren har gått bra hela sommaren, och nu kan hela huset bli ditt. Vill du ta över och göra en bistro av det?”', en: '“I’ve spoken to the owner of the building. The wine bar has done well all summer, and now the whole building could be yours. Would you like to take it over and make it a bistro?”' },
  'asa.what': { sv: 'Det här betyder det', en: 'What it means' },
  'asa.row.closed': { sv: 'Stängt i {days} dagar medan ni bygger om', en: 'Closed for {days} days while you rebuild' },
  'asa.row.deposit': { sv: 'Kontantinsats {deposit}, resten lånar du', en: 'A deposit of {deposit}, the rest is a loan' },
  'asa.row.rep': { sv: 'Ryktet följer med, byn känner dig redan', en: 'Your reputation comes with you; the village already knows you' },
  'asa.row.keep': { sv: 'Personalen och allt du kan följer med', en: 'Your staff and everything you know come with you' },
  'asa.take': { sv: 'Ta över', en: 'Take over' },
  'asa.notyet': { sv: 'Inte än', en: 'Not yet' },
  'asa.reply.take': { sv: '”Då kommer jag i morgon med ritningarna och ägarens kontrakt.”', en: '“Then I’ll come by tomorrow with the drawings and the owner’s contract.”' },
  'asa.reply.notyet': { sv: '”Erbjudandet står kvar. Säg till när du är redo.”', en: '“The offer stands. Tell me when you’re ready.”' },
  'asa.toRefit': { sv: 'Till ombyggnaden', en: 'To the refit' },
  'refit.title': { sv: 'Ombyggnaden', en: 'The refit' },
  'refit.sub': { sv: 'Från vinbar till bistro', en: 'From wine bar to bistro' },
  'refit.p0': { sv: 'Vinbaren', en: 'The wine bar' },
  'refit.p1': { sv: 'Tömt', en: 'Cleared' },
  'refit.p2': { sv: 'Byggt', en: 'Built' },
  'refit.p3': { sv: 'Dukat', en: 'Laid' },
  'refit.p4': { sv: 'Tänt', en: 'Lit' },
  'refit.seats': { sv: '{n} platser', en: '{n} seats' },
  'fika.kicker': { sv: 'Fikat efter stängning', en: 'Coffee after closing' },
  'tier.title': { sv: 'Nivån', en: 'The level' },
  'tier.sub': { sv: 'Varukorgen avgör nivån. Steget är verksamheten, nivån är priset och gästerna.', en: 'Your basket sets the level. The step is the business; the level is the prices and the guests.' },
  'tier.simple': { sv: 'Enkel', en: 'Simple' },
  'tier.mid': { sv: 'Mellan', en: 'Mid-range' },
  'tier.fine': { sv: 'Exklusiv', en: 'Exclusive' },
  'tier.sign': { sv: 'Skylten', en: 'The sign' },
  'tier.morning': { sv: 'På morgonen', en: 'In the morning' },
  'tier.changed': { sv: 'Från i dag: {tier}', en: 'From today: {tier}' },
  'tier.guests.simple': { sv: 'Studenter och bybor', en: 'Students and villagers' },
  'tier.guests.mid': { sv: 'Bybor och turister', en: 'Villagers and tourists' },
  'tier.guests.fine': { sv: 'Turister, gourmeter och affärsfolk', en: 'Tourists, gourmets and business people' },
  'tier.price.simple': { sv: 'Låga priser', en: 'Low prices' },
  'tier.price.mid': { sv: 'Mellanpriser', en: 'Mid prices' },
  'tier.price.fine': { sv: 'Höga priser', en: 'High prices' },
  'review.fx.class': { sv: 'Ryktet på nivån {tier} {delta}', en: 'Reputation at the {tier} level {delta}' },
  'review.fx.venue': { sv: 'Krogens rykte {delta}', en: 'The venue’s reputation {delta}' },
  'fika.grade.well': { sv: 'Väl grundat', en: 'Well grounded' },
  'fika.grade.partly': { sv: 'Delvis grundat', en: 'Partly grounded' },
  'fika.grade.weak': { sv: 'Svagt grundat', en: 'Weakly grounded' },
  'fika.scale': { sv: 'Väl, delvis eller svagt grundat', en: 'Well, partly or weakly grounded' }
};
