// moodStrings.ts — gästernas stämning, leverans 2026-10-03. { sv, en }, brittisk engelska. Slås in i STRINGS.
// Samma nycklar som stamningStrings.js (prototypen). Inga speltal i texterna.

export const MOOD_STRINGS: Record<string, { sv: string; en: string }> = {
  'mood.delighted': { sv: 'Glad', en: 'Delighted' },
  'mood.content': { sv: 'Nöjd', en: 'Content' },
  'mood.waiting': { sv: 'Väntar', en: 'Waiting' },
  'mood.impatient': { sv: 'Otålig', en: 'Impatient' },
  'mood.displeased': { sv: 'Missnöjd', en: 'Displeased' },
  'hud.mood.title': { sv: 'Stämningen i rummet', en: 'Mood in the room' },
  'hud.mood.a11y': { sv: 'Stämningen i rummet: {mood}', en: 'Mood in the room: {mood}' },
  'hud.mood.up': { sv: 'Stämningen steg', en: 'The mood lifted' },
  'hud.mood.down': { sv: 'Stämningen sjönk', en: 'The mood dropped' },

  'clip.guest.leanCurious': { sv: 'Luta sig fram nyfiket', en: 'Lean in, curious' },
  'clip.guest.laugh': { sv: 'Skratta', en: 'Laugh' },
  'clip.guest.cheers': { sv: 'Skåla', en: 'Raise a toast' },
  'clip.guest.nodApprove': { sv: 'Nicka gillande', en: 'Nod in approval' },
  'clip.guest.armsCrossed': { sv: 'Lägga armarna i kors', en: 'Fold their arms' },
  'clip.guest.checkWatch': { sv: 'Titta på klockan', en: 'Check the time' },
  'clip.guest.waveWaiter': { sv: 'Vinka efter servitören', en: 'Wave for the waiter' },
  'clip.guest.pushPlate': { sv: 'Skjuta undan tallriken', en: 'Push the plate away' },

  'mood.kicker': { sv: 'Tillägg till vardagens koreografi · gästernas stämning', en: 'Addition to the everyday choreography · guest mood' },
  'mood.title': { sv: 'Gästernas stämning', en: 'Guest mood' },
  'mood.scene.bdayRight': { sv: 'Födelsedagen, steg 3 · rätt', en: 'The birthday, step 3 · right' },
  'mood.scene.bdayWrong': { sv: 'Födelsedagen, steg 3 · fel', en: 'The birthday, step 3 · wrong' },
  'mood.scene.drunkRight': { sv: 'Gästen som vinglar, steg 1 · rätt', en: 'The unsteady guest, step 1 · right' },
  'mood.scene.drunkWrong': { sv: 'Gästen som vinglar, steg 1 · fel', en: 'The unsteady guest, step 1 · wrong' },
  'mood.scene.gestures': { sv: 'De åtta gesterna', en: 'The eight gestures' },
  'mood.scene.faces': { sv: 'Ansiktena i närbild', en: 'Faces in close-up' },
  'mood.scene.symEvening': { sv: 'Symbolerna i kvällsljus', en: 'The symbols by evening light' },
  'mood.scene.symDay': { sv: 'Symbolerna i dagsljus', en: 'The symbols by daylight' },
  'mood.group.consequence': { sv: 'Konsekvensögonblicket', en: 'The consequence moment' },
  'mood.group.parts': { sv: 'Delarna', en: 'The parts' },
  'mood.cam': { sv: 'Kamera', en: 'Camera' },
  'mood.cam.script': { sv: 'Manusets', en: 'Scripted' },
  'mood.cam.game': { sv: 'Spelets, 24 m', en: 'Game, 24 m' },
  'mood.tempo': { sv: 'Tempo', en: 'Tempo' },
  'mood.tempo.calm': { sv: 'Lugn', en: 'Calm' },
  'mood.tempo.normal': { sv: 'Normal', en: 'Normal' },
  'mood.tempo.stressed': { sv: 'Stressad', en: 'Stressed' },
  'mood.size': { sv: 'Skärmstorlek', en: 'Screen size' },
  'mood.play': { sv: 'Spela', en: 'Play' },
  'mood.pause': { sv: 'Pausa', en: 'Pause' },
  'mood.record': { sv: 'Spela in WebM', en: 'Record WebM' },
  'mood.recording': { sv: 'Spelar in …', en: 'Recording …' },
  'mood.distance': { sv: 'Kamerans avstånd', en: 'Camera distance' },
  'mood.faces': { sv: 'Ansiktena', en: 'Faces' },
  'mood.legend': { sv: 'Symbolerna, 24 px', en: 'The symbols, 24 px' },
  'mood.faceRule': { sv: 'Ansiktena tonas in från 9 m och är fulla vid 7 m.', en: 'Faces fade in from 9 m and are full at 7 m.' },
  'mood.focusHint': { sv: 'Välj en gest för att gå nära.', en: 'Pick a gesture to move in close.' },

  'mood.ch.bday.ask': { sv: 'Frågan: sällskapet vill sjunga för Karin', en: 'The question: the party wants to sing for Karin' },
  'mood.why.bday.ask': { sv: 'Situationens kamera på 13 m. Grannarna i lounge B äter, lounge A väntar på svaret.', en: 'The situation camera at 13 m. The neighbours in lounge B are eating; lounge A waits for the answer.' },
  'mood.ch.drunk.ask': { sv: 'Frågan: gästen vill ha ett glas till', en: 'The question: the guest wants another glass' },
  'mood.why.drunk.ask': { sv: 'Södra vinkeln på 12 m, så att ansiktena vid baren och i lounge A syns när kameran går in.', en: 'The southern angle at 12 m, so the faces at the bar and in lounge A show when the camera moves in.' },
  'mood.ch.cq.right': { sv: 'Svaret låses: rätt', en: 'The answer locks: right' },
  'mood.why.cq.right': { sv: 'Kortet blir grönt och lyfter. Kameran står kvar medan spelaren ser det.', en: 'The card turns green and lifts. The camera holds while the player sees it.' },
  'mood.ch.cq.wrong': { sv: 'Svaret låses: fel', en: 'The answer locks: wrong' },
  'mood.why.cq.wrong': { sv: 'Kortet blir rött och skakar. Kameran står kvar lite längre.', en: 'The card turns red and shakes. The camera holds a little longer.' },
  'mood.ch.cq.inRight': { sv: 'Kameran går in i en båge till 7 m', en: 'The camera arcs in to 7 m' },
  'mood.why.cq.inRight': { sv: 'En mjuk båge och lite lägre, som lyftningen på kortet. Ansiktena tänds mellan 9 och 7 m.', en: 'A soft arc, slightly lower, like the card’s lift. Faces light up between 9 and 7 m.' },
  'mood.ch.cq.inWrong': { sv: 'Kameran går rakt in till 7 m', en: 'The camera moves straight in to 7 m' },
  'mood.why.cq.inWrong': { sv: 'Ingen båge och lite högre. Spelaren ser vad svaret ledde till.', en: 'No arc, slightly higher. The player sees what the answer led to.' },
  'mood.ch.bday.gestRight': { sv: 'Sällskapet skrattar och skålar, grannarna lutar sig fram', en: 'The party laughs and toasts; the neighbours lean in' },
  'mood.why.bday.gestRight': { sv: 'Elin bjuder grannarna på fördrinken, så de blir en del av festen i stället för att störas av den.', en: 'Elin treats the neighbours to an aperitif, so they join the celebration instead of being disturbed by it.' },
  'mood.ch.bday.gestWrong': { sv: 'Sällskapet sjunger, grannarna lägger armarna i kors', en: 'The party sings; the neighbours fold their arms' },
  'mood.why.bday.gestWrong': { sv: 'Musiken går upp. Ett bord blir gladare och två bord blir missnöjda, så rummet sjunker.', en: 'The music goes up. One table gets happier and two tables get unhappy, so the room drops.' },
  'mood.ch.drunk.gestRight': { sv: 'Grannarna vid baren nickar', en: 'The neighbours at the bar nod' },
  'mood.why.drunk.gestRight': { sv: 'Mira pratar lugnt med gästen. De som såg det blir lugna, och lounge A tittar nyfiket.', en: 'Mira talks calmly with the guest. Those who saw it relax, and lounge A looks on with interest.' },
  'mood.ch.drunk.gestWrong': { sv: 'Grannarna vid baren drar sig undan', en: 'The neighbours at the bar pull away' },
  'mood.why.drunk.gestWrong': { sv: 'Mira häller upp ett glas till. Gästen är glad, men grannen skjuter undan tallriken och lounge A vill betala.', en: 'Mira pours another glass. The guest is happy, but a neighbour pushes the plate away and lounge A wants to pay.' },
  'mood.ch.cq.symbol': { sv: 'Symbolerna över borden byts', en: 'The symbols over the tables change' },
  'mood.why.cq.symbol': { sv: 'Bättre lyfter, sämre skakar. Ingen symbol pulserar.', en: 'Better lifts, worse shakes. No symbol pulses.' },
  'mood.ch.cq.meter': { sv: 'Mätaren i HUD:en flyttar sig', en: 'The meter in the HUD moves' },
  'mood.why.cq.meter': { sv: 'Alltid efter symbolerna, så att spelaren ser orsaken först. Det som förloras står kvar streckat en stund.', en: 'Always after the symbols, so the player sees the cause first. What is lost stays dashed for a moment.' },
  'mood.ch.cq.close': { sv: 'Kameran går in till 5,5 m', en: 'The camera moves in to 5.5 m' },
  'mood.why.cq.close': { sv: 'De sista 1,5 sekunderna, långsamt. Ansiktena blir större utan att huvudena förstoras.', en: 'The last 1.5 seconds, slowly. The faces get larger without enlarging the heads.' },
  'mood.ch.cq.back': { sv: 'Tillbaka till 24 m', en: 'Back to 24 m' },
  'mood.why.cq.back': { sv: 'Ansiktena slocknar på vägen ut. Symbolerna står kvar enligt sina regler.', en: 'The faces go out on the way back. The symbols stay according to their rules.' },
  'mood.ch.face.far': { sv: 'Situationens avstånd, 11 m', en: 'Situation distance, 11 m' },
  'mood.why.face.far': { sv: 'Inga ansikten. Huvudet är för litet för ögon och mun.', en: 'No faces. The head is too small for eyes and mouth.' },
  'mood.ch.face.in': { sv: 'Kameran går in till 6,5 m', en: 'The camera moves in to 6.5 m' },
  'mood.why.face.in': { sv: 'Ansiktena tonas in mellan 9 och 7 m.', en: 'The faces fade in between 9 and 7 m.' },
  'mood.ch.face.content': { sv: 'Nöjd', en: 'Content' },
  'mood.why.face.content': { sv: 'Prickar till ögon och ett litet leende.', en: 'Dot eyes and a small smile.' },
  'mood.ch.face.delighted': { sv: 'Glad', en: 'Delighted' },
  'mood.why.face.delighted': { sv: 'Ögonen kniper ihop sig och munnen öppnas.', en: 'The eyes crinkle and the mouth opens.' },
  'mood.ch.face.waiting': { sv: 'Väntar', en: 'Waiting' },
  'mood.why.face.waiting': { sv: 'Blicken åt sidan och munnen rak.', en: 'Eyes to the side and a straight mouth.' },
  'mood.ch.face.impatient': { sv: 'Otålig', en: 'Impatient' },
  'mood.why.face.impatient': { sv: 'Raka bryn och en mun som drar åt sidan.', en: 'Flat brows and a mouth pulled to one side.' },
  'mood.ch.face.displeased': { sv: 'Missnöjd', en: 'Displeased' },
  'mood.why.face.displeased': { sv: 'Bryn som sluttar inåt och en mun som går nedåt.', en: 'Brows slanting inwards and a downturned mouth.' },
  'mood.ch.sym.evening': { sv: 'Alla fem lägen i kvällsljus', en: 'All five states by evening light' },
  'mood.why.sym.evening': { sv: 'Spelets kamera på 24 m. Ljusa brickor har mörk kant, mörka brickor har mässingskant.', en: 'The game camera at 24 m. Light plates have a dark rim, dark plates a brass rim.' },
  'mood.ch.sym.day': { sv: 'Alla fem lägen i dagsljus', en: 'All five states by daylight' },
  'mood.why.sym.day': { sv: 'Samma brickor. Den mörka kanten håller de ljusa brickorna mot det ljusa golvet.', en: 'The same plates. The dark rim keeps the light plates clear of the bright floor.' },
  'mood.why.gest.guest.laugh': { sv: 'Glad. Huvudet bakåt, axlarna studsar, sedan framåt.', en: 'Delighted. Head back, shoulders bouncing, then forwards.' },
  'mood.why.gest.guest.cheers': { sv: 'Glad. Glaset över huvudhöjd mot bordets mitt, ingen klunk.', en: 'Delighted. Glass above head height towards the middle of the table, no sip.' },
  'mood.why.gest.guest.leanCurious': { sv: 'Nöjd. Underarmarna mot knäna och huvudet på sned.', en: 'Content. Forearms on the knees and head tilted.' },
  'mood.why.gest.guest.nodApprove': { sv: 'Nöjd. Två långsamma nickar med öppen handflata.', en: 'Content. Two slow nods with an open palm.' },
  'mood.why.gest.guest.armsCrossed': { sv: 'Missnöjd. Bålen bakåt och blicken bort, en suck per varv.', en: 'Displeased. Leaning back and looking away, a sigh each cycle.' },
  'mood.why.gest.guest.pushPlate': { sv: 'Missnöjd. Rak arm som skjuter tallriken ifrån sig, sedan armarna i kors.', en: 'Displeased. A straight arm pushes the plate away, then the arms fold.' },
  'mood.why.gest.guest.checkWatch': { sv: 'Väntar. Klockan, sedan blicken ut efter personalen.', en: 'Waiting. The watch, then a look out for the staff.' },
  'mood.why.gest.guest.waveWaiter': { sv: 'Otålig. Armen rakt upp och halvvägs upp från sitsen.', en: 'Impatient. Arm straight up, half rising from the seat.' }
};
