// serviceModeStrings.ts — serviceläget och skärmen efter servicen. 67 nycklar, { sv, en }.
// Slås in i STRINGS i nexusStrings.ts. Alla belopp och tider är platshållare ({n}, {time}, {h}, {m}) och kommer från balance.ts och sim-lagret.
// Nycklar som återanvänds ur nexusStrings.varm.ts: hud.service, hud.day, hud.afterClose, money.kr, money.plus, money.minus, meter.guests, meter.staff, buy.item.*.

export const SERVICE_MODE_STRINGS = {
  "serviceMode.till": { sv: "Kvällskassan", en: "Tonight's till" },
  "serviceMode.stake": { sv: "Insatsen {n}", en: "Outlay {n}" },
  "serviceMode.toGo": { sv: "{n} kvar till insatsen", en: "{n} to cover the outlay" },
  "serviceMode.over": { sv: "{n} över insatsen", en: "{n} above the outlay" },
  "serviceMode.passedAt": { sv: "Insatsen passerades {time}", en: "Outlay covered at {time}" },
  "serviceMode.left": { sv: "{h} h {m} min kvar", en: "{h} h {m} min left" },
  "serviceMode.leftMin": { sv: "{m} min kvar", en: "{m} min left" },
  "serviceMode.stake.title": { sv: "Kvällens insats", en: "Tonight's outlay" },
  "serviceMode.stake.note": { sv: "Det kvällen kostade innan första gästen kom. När kassan passerar linjen går kvällen med vinst.", en: "What tonight cost before the first guest arrived. Once the till passes the line, the evening is in profit." },
  "serviceMode.stake.total": { sv: "Linjen", en: "The line" },
  "cost.food": { sv: "Råvaror", en: "Produce" },
  "cost.food.sub": { sv: "Morgonens inköp", en: "This morning's order" },
  "cost.staff": { sv: "Personal", en: "Staff" },
  "cost.staff.sub": { sv: "{n} i tjänst i kväll", en: "{n} on shift tonight" },
  "cost.dj": { sv: "DJ", en: "DJ" },
  "cost.dj.sub": { sv: "Helgens kvällar", en: "Weekend evenings" },
  "cost.skills": { sv: "Kompetens", en: "Training" },
  "cost.skills.sub": { sv: "Kursen i Måltidens hus", en: "The course at Måltidens hus" },
  "serviceMode.tab.stock": { sv: "Lagret", en: "Stock" },
  "serviceMode.tab.stream": { sv: "Kvällen", en: "Tonight" },
  "serviceMode.tab.room": { sv: "Rummet", en: "The room" },
  "serviceMode.close": { sv: "Stäng", en: "Close" },
  "serviceMode.keys": { sv: "1–3 öppnar · Esc stänger", en: "1–3 to open · Esc to close" },
  "stock.portions": { sv: "{n} portioner", en: "{n} portions" },
  "stock.glasses": { sv: "{b} flaskor och {g} glas", en: "{b} bottles and {g} glasses" },
  "stock.glassesOnly": { sv: "{g} glas", en: "{g} glasses" },
  "stock.low": { sv: "Snart slut", en: "Running low" },
  "stock.out": { sv: "Slut", en: "Sold out" },
  "stock.kitchen": { sv: "Köket", en: "Kitchen" },
  "stock.bar": { sv: "Baren", en: "Bar" },
  "stream.pay": { sv: "{place} betalade {n}", en: "{place} paid {n}" },
  "stream.order": { sv: "{place} beställde {what}", en: "{place} ordered {what}" },
  "stream.low": { sv: "{what} börjar ta slut", en: "{what} is running low" },
  "stream.rocket": { sv: "Situation: {what}", en: "Situation: {what}" },
  "stream.rocket.birthday": { sv: "födelsedagen i loungen", en: "the birthday in the lounge" },
  "place.loungeA": { sv: "Lounge A", en: "Lounge A" },
  "place.bar3": { sv: "Barstol 3", en: "Bar stool 3" },
  "place.twoB": { sv: "Småbord B", en: "Small table B" },
  "room.guests.note": { sv: "{n} gäster i rummet", en: "{n} guests in the room" },
  "room.staff.note": { sv: "Sara är långt från passet", en: "Sara is a long way from the pass" },
  "settle.kicker": { sv: "Efter servicen", en: "After service" },
  "settle.title": { sv: "Kvällens kassa", en: "Tonight's till" },
  "settle.sales": { sv: "Försäljning", en: "Sales" },
  "settle.sales.sub": { sv: "{n} notor. Dricksen går till personalen.", en: "{n} bills. Tips go to the staff." },
  "settle.food": { sv: "Råvaror", en: "Produce" },
  "settle.food.sub": { sv: "Allt som köptes i morse, också det som blev över", en: "Everything bought this morning, including what was left" },
  "settle.cm": { sv: "Täckningsbidrag", en: "Contribution margin" },
  "settle.cm.sub": { sv: "Det försäljningen lämnar när råvarorna är betalda", en: "What sales leave once the produce is paid for" },
  "settle.cmr": { sv: "Täckningsgrad", en: "Margin ratio" },
  "settle.cmr.sub": { sv: "Av varje hundralapp blev {n} kr kvar efter råvarorna.", en: "Of every SEK 100 taken, SEK {n} was left after produce." },
  "settle.rest": { sv: "Resten av insatsen", en: "The rest of the outlay" },
  "settle.result": { sv: "Kvällens resultat", en: "Tonight's result" },
  "settle.result.sub": { sv: "Täckningsbidraget minus resten av insatsen", en: "Contribution margin less the rest of the stake" },
  "settle.mentor": { sv: "Täckningsgraden visar hur mycket av varje krona som räcker till allt annat. Följ den hellre än försäljningen.", en: "The margin ratio shows how much of each krona is left for everything else. Watch it more closely than sales." },
  "settle.transfer.kicker": { sv: "Överföringen", en: "The transfer" },
  "settle.transfer.title": { sv: "Till företagskontot", en: "To the business account" },
  "settle.account": { sv: "Företagskontot", en: "Business account" },
  "settle.transfer.do": { sv: "För över {n}", en: "Transfer {n}" },
  "settle.transfer.done": { sv: "Överfört {time}", en: "Transferred at {time}" },
  "settle.transfer.note": { sv: "Råvarorna betalades från kontot i morse. Morgondagens inköp betalas härifrån.", en: "The produce was paid from the account this morning. Tomorrow's order is paid from here." },
  "settle.loss.note": { sv: "Kvällen gick med förlust. Kontot står lägre än i morse.", en: "The evening made a loss. The account is lower than this morning." },
  "settle.vsMorning": { sv: "{n} mot i morse", en: "{n} on this morning" },
  "settle.flow.in": { sv: "Kvällskassan in", en: "Tonight's till in" },
  "settle.flow.out": { sv: "Resten av insatsen", en: "The rest of the stake" },
  "settle.flow.morning": { sv: "Råvarorna, betalda i morse", en: "Produce, paid this morning" },
  "settle.flow.net": { sv: "Kvällens resultat", en: "Tonight's result" },
  "settle.next": { sv: "Till kvällens resultat", en: "On to tonight's result" },
} as const;
