// villageEveningStrings.ts — byn i kvällsljus, { sv, en }, brittisk engelska. Slås in i STRINGS.
// Samma nycklar som prototypens byKvallStrings.js (66 nycklar). Inga speltal: 1,6 och 1,25 är figurernas förstoring.
export const VILLAGE_EVENING_STRINGS: Record<string, { sv: string; en: string }> = {
  'byk.kicker': { sv: 'Underlag till 288 · byn och konkurrensen', en: 'Groundwork for 288 · the village and its rivals' },
  'byk.title': { sv: 'Byn i kvällsljus', en: 'The village in evening light' },
  'byk.level': { sv: 'Nivå', en: 'Level' },
  'byk.level.village': { sv: 'Byn', en: 'The village' },
  'byk.level.block': { sv: 'Kvarteret', en: 'The block' },
  'byk.level.street': { sv: 'Gatan', en: 'The street' },
  'byk.level.venue': { sv: 'Krogen', en: 'Your place' },
  'byk.level.hint': { sv: 'Hjulet zoomar mellan nivåerna. Dra för att vrida, högerklicka och dra för att flytta dig i byn.', en: 'Scroll to zoom between levels. Drag to turn; right-click and drag to move around the village.' },
  'byk.evening': { sv: 'Kvällen', en: 'The evening' },
  'byk.play': { sv: 'Spela', en: 'Play' },
  'byk.pause': { sv: 'Pausa', en: 'Pause' },
  'byk.phase.dusk': { sv: 'Skymningen', en: 'Dusk' },
  'byk.phase.blue': { sv: 'Blå timmen', en: 'The blue hour' },
  'byk.phase.evening': { sv: 'Kvällen', en: 'Evening' },
  'byk.phase.night': { sv: 'Natten', en: 'Night' },
  'byk.onLevel': { sv: 'På den här nivån', en: 'At this level' },
  'byk.row.guests': { sv: 'Gästerna', en: 'Guests' },
  'byk.row.party': { sv: 'Sällskapen', en: 'Parties' },
  'byk.row.truck': { sv: 'Food truckarna', en: 'Food trucks' },
  'byk.row.venue': { sv: 'Krogarna', en: 'Restaurants' },
  'byk.row.light': { sv: 'Ljuset', en: 'The light' },
  'byk.desc.village.guests': { sv: 'Hela byn: alla krogar och vagnarnas platser. Varje sällskap är en lykta på gatan, i gästtypens färg, och lyktan växer med avståndet så att den syns. Figurerna ritas inte.', en: 'The whole village: every restaurant and every truck pitch. Each party is a lantern on the street in its guest type’s colour, and the lantern grows with distance so it stays visible. Figures are not drawn.' },
  'byk.desc.village.party': { sv: 'Lyktan växer med sällskapets storlek. Lova och miljardären har sin ring runt lyktan.', en: 'The lantern grows with the size of the party. Lova and the billionaire keep their ring around it.' },
  'byk.desc.village.truck': { sv: 'Ett varmt sken där vagnen står, bara när luckan är öppen.', en: 'A warm glow where the truck stands, only while the hatch is open.' },
  'byk.desc.village.venue': { sv: 'En gloria över taket när krogen har öppet. Den växer med gästerna inne. Dörren blinkar till när ett sällskap går in.', en: 'A halo above the roof while the restaurant is open. It grows with the guests inside. The door flashes as a party goes in.' },
  'byk.desc.village.light': { sv: 'Gatlyktorna tänds en i taget i skymningen. Ett hus släcks när de boende går ut och tänds när de är hemma igen.', en: 'The street lamps come on one by one at dusk. A house goes dark when its residents go out and lights up when they are home again.' },
  'byk.desc.block.guests': { sv: 'Figurerna syns, 1,6 gånger verklig storlek, så att ryggsäcken, hatten och guldet går att läsa.', en: 'Figures appear at 1.6 times real size, so the rucksack, the hat and the gold can be read.' },
  'byk.desc.block.party': { sv: 'Medlemmarna går tätt, med en svag fläck i gästtypens färg under sig. Sällskapet läses som en enhet.', en: 'Members walk close together over a faint patch in their guest type’s colour, so the party reads as one.' },
  'byk.desc.block.truck': { sv: 'Vagnen som modell, med markis och upplyst lucka. Kön är en rad figurer.', en: 'The truck as a model with awning and lit hatch. The queue is a row of figures.' },
  'byk.desc.block.venue': { sv: 'Fönstren lyser och ljuset från dörren faller ut på gatan. Köket lyser redan innan krogen öppnar.', en: 'The windows glow and light from the door falls onto the street. The kitchen is lit before the restaurant opens.' },
  'byk.desc.block.light': { sv: 'Lyktornas ljus ligger som cirklar på gatan. Hotellets rum tänds senare på kvällen.', en: 'Lamplight lies in circles on the street. The hotel rooms light up later in the evening.' },
  'byk.desc.street.guests': { sv: '1,25 gånger verklig storlek. Gångklippen syns, och var och en går lite för sig.', en: '1.25 times real size. The walk clips show, and each person drifts a little on their own.' },
  'byk.desc.street.party': { sv: 'Fläcken är borta. Sällskapet går i den långsammastes takt och samlas vid dörren innan det går in.', en: 'The patch is gone. The party walks at the slowest member’s pace and gathers at the door before going in.' },
  'byk.desc.street.truck': { sv: 'Ljusslingan under markisen tänds. Gästerna äter stående vid luckan och går sedan hem.', en: 'The string lights under the awning come on. Guests eat standing at the hatch, then walk home.' },
  'byk.desc.street.venue': { sv: 'Skylten över dörren lyser, utan text, och lyktorna vid dörren är tända.', en: 'The sign above the door glows, without text, and the door lamps are lit.' },
  'byk.desc.street.light': { sv: 'Bilarna kör med strålkastarna på. Efter stängning lyser bara köket en stund.', en: 'Cars drive with their headlights on. After closing, only the kitchen stays lit for a while.' },
  'byk.desc.venue.guests': { sv: 'Verklig storlek, samma som i teatern. Här tar teatern över när kameran går in.', en: 'Real size, the same as in the theatre. This is where the theatre takes over as the camera goes in.' },
  'byk.desc.venue.party': { sv: 'När krogen är full ställer sig sällskapen på rummets köplatser, först på dörrmattan och sedan på trottoaren. Den som väntar för länge går hem.', en: 'When the restaurant is full, parties stand on the room’s queue spots, first on the doormat and then on the pavement. Those who wait too long go home.' },
  'byk.desc.venue.truck': { sv: 'Syns bara när en vagn står i närheten.', en: 'Only visible when a truck is parked nearby.' },
  'byk.desc.venue.venue': { sv: 'Taket lyfts och tonar ut när kameran går in. Väggarna på kamerans sida kapas, rummet lyses upp och personalen och gästerna inne syns på sina platser. Här tar teatern över.', en: 'The roof lifts and fades as the camera moves in. The walls on the camera side are cut away, the room lights up and the staff and guests inside appear in their places. This is where the theatre takes over.' },
  'byk.desc.venue.light': { sv: 'Ljuset från fönstren och dörren faller på kön.', en: 'Light from the windows and the door falls on the queue.' },
  'byk.venues': { sv: 'Krogarna i kväll', en: 'Tonight’s restaurants' },
  'byk.venues.hint': { sv: 'Namnet visar krogen. Läget öppnar eller stänger.', en: 'The name shows the restaurant. The state opens or closes it.' },
  'byk.venue.var': { sv: 'Vår krog', en: 'Our restaurant' },
  'byk.venue.torg': { sv: 'Torgkrogen', en: 'Torgkrogen' },
  'byk.venue.pizza': { sv: 'Pizzeria Grytan', en: 'Pizzeria Grytan' },
  'byk.venue.sjo': { sv: 'Sjöboden', en: 'Sjöboden' },
  'byk.venue.hotell': { sv: 'Hotellets matsal', en: 'The hotel dining room' },
  'byk.venue.grill': { sv: 'Grillvagnen', en: 'The grill truck' },
  'byk.venue.taco': { sv: 'Tacovagnen', en: 'The taco truck' },
  'byk.state.open': { sv: 'Öppet', en: 'Open' },
  'byk.state.closed': { sv: 'Stängt', en: 'Closed' },
  'byk.state.prep': { sv: 'Förbereder', en: 'Getting ready' },
  'byk.state.cleaning': { sv: 'Städar', en: 'Cleaning up' },
  'byk.state.byHand': { sv: 'för hand', en: 'set by hand' },
  'byk.resetSchedule': { sv: 'Följ kvällens gång', en: 'Follow the evening' },
  'byk.names': { sv: 'Namnen i HUD:en', en: 'Names in the HUD' },
  'byk.size': { sv: 'Skärmstorlek', en: 'Screen size' },
  'byk.light': { sv: 'Ljusnivå', en: 'Light level' },
  'byk.enter': { sv: 'Visa övergången in i krogen', en: 'Show the transition into the restaurant' },
  'byk.types': { sv: 'Gästtyperna', en: 'Guest types' },
  'byk.type.student': { sv: 'Studenten', en: 'The student' },
  'byk.type.medel': { sv: 'Medelinkomsttagaren', en: 'The middle earner' },
  'byk.type.hog': { sv: 'Höginkomsttagaren', en: 'The high earner' },
  'byk.type.social': { sv: 'Gästen med socialt kapital', en: 'The guest with social capital' },
  'byk.type.miljardar': { sv: 'Miljardären', en: 'The billionaire' }
};
