// hostShopStrings.ts — hovmästarens beslut, rivalbandet, jämförelsen efter kvällen och butiken.
// 128 nycklar, { sv, en }, brittisk engelska. Slås in i STRINGS i nexusStrings.ts.
// Återanvänder hud.*, money.* (leverans 1) och serviceMode.* (serviceläget). venue.* är samma namn som byk.venue.* och byTruckar.js.
// Inga speltal: {n}, {used}, {price}, {rank}, {medal}, {pavilion}, {company} och {place} fylls från sim-lagret och balance.ts.
export const HOST_SHOP_STRINGS: Record<string, { sv: string; en: string }> = {
  // Nålarna
  'pin.per': { sv: 'Väljer du inte, tar Per det säkra', en: 'If you don’t choose, Per plays it safe' },
  'pin.safeNote': { sv: 'Det säkra går aldrig fel, men det ger sällan mest.', en: 'The safe choice never goes wrong, but it rarely gives the most.' },
  'pin.perTag': { sv: 'Per · säkert', en: 'Per · safe' },
  'pin.keys': { sv: '1 eller 2', en: '1 or 2' },
  'pin.where.door': { sv: 'Vid dörren', en: 'At the door' },
  'pin.where.table2': { sv: 'Bord 2', en: 'Table 2' },
  'pin.where.bar': { sv: 'Baren', en: 'The bar' },
  'pin.door.q': { sv: 'Fyra vid dörren, och bara två små bord är lediga.', en: 'Four at the door, and only two small tables are free.' },
  'pin.door.a1': { sv: 'Ställ ihop de två små borden', en: 'Push the two small tables together' },
  'pin.door.a2': { sv: 'Be dem vänta i baren en stund', en: 'Ask them to wait at the bar a while' },
  'pin.door.done1': { sv: 'Per och servitören ställer ihop borden.', en: 'Per and the waiter push the tables together.' },
  'pin.door.done2': { sv: 'Per visar dem till baren.', en: 'Per shows them to the bar.' },
  'pin.wine.q': { sv: 'Bord 2 har tittat länge på vinlistan.', en: 'Table 2 has been studying the wine list for a while.' },
  'pin.wine.a1': { sv: 'Skicka sommeliern till bordet', en: 'Send the sommelier to the table' },
  'pin.wine.a2': { sv: 'Föreslå husets vin själv', en: 'Suggest the house wine yourself' },
  'pin.wine.done1': { sv: 'Sommeliern går till bord 2.', en: 'The sommelier goes to table 2.' },
  'pin.wine.done2': { sv: 'Per föreslår husets vin.', en: 'Per suggests the house wine.' },
  'pin.bar.q': { sv: 'Baren hinner inte med beställningarna.', en: 'The bar can’t keep up with the orders.' },
  'pin.bar.a1': { sv: 'Flytta servitören till baren', en: 'Move the waiter to the bar' },
  'pin.bar.a2': { sv: 'Låt baren ta det i sin takt', en: 'Let the bar work at its own pace' },
  'pin.bar.done1': { sv: 'Servitören går in bakom baren.', en: 'The waiter goes behind the bar.' },
  'pin.bar.done2': { sv: 'Bartendern tar en beställning i taget.', en: 'The bartender takes one order at a time.' },

  // Handgreppen
  'host.party': { sv: 'Sällskap på {n}', en: 'Party of {n}' },
  'host.inQueue': { sv: 'I kön', en: 'In the queue' },
  'host.seat': { sv: 'Ge bord', en: 'Seat them' },
  'host.fits': { sv: 'Passar här', en: 'Fits here' },
  'host.comp': { sv: 'Bjud', en: 'On the house' },
  'host.upsell': { sv: 'Sälj in', en: 'Suggest' },
  'host.comp.glass': { sv: 'Ett glas', en: 'A glass' },
  'host.comp.coffee': { sv: 'Kaffe', en: 'Coffee' },
  'host.upsell.dessert': { sv: 'Dessert', en: 'Pudding' },
  'host.upsell.wine': { sv: 'Ett glas till', en: 'Another glass' },
  'host.move': { sv: 'Flytta', en: 'Move' },
  'host.zone.bar': { sv: 'Till baren', en: 'To the bar' },
  'host.state.eating': { sv: 'Äter', en: 'Eating' },
  'host.place.loungeA': { sv: 'Lounge A', en: 'Lounge A' },
  'host.done.seat': { sv: 'Per visar dem till bordet.', en: 'Per shows them to the table.' },
  'host.done.verb': { sv: 'Servitören går till {place}.', en: 'The waiter goes to {place}.' },
  'host.done.move': { sv: 'Servitören går till baren.', en: 'The waiter goes to the bar.' },

  // Bandet
  'rival.title': { sv: 'Byn i kväll', en: 'The village tonight' },
  'rival.rank': { sv: '{rank} i byn', en: '{rank} in the village' },
  'rival.guests': { sv: '{n} gäster', en: '{n} guests' },
  'rival.overtake': { sv: 'Förbi {name}', en: 'Past {name}' },
  'rival.us': { sv: 'Vi', en: 'Us' },
  // Namnen är desamma som byk.venue.* och byTruckar.js. {company} är företagets namn i liggaren.
  'venue.ours': { sv: '{company}', en: '{company}' },
  'venue.torg': { sv: 'Torgkrogen', en: 'Torgkrogen' },
  'venue.pizza': { sv: 'Pizzeria Grytan', en: 'Pizzeria Grytan' },
  'venue.hotel': { sv: 'Hotellets matsal', en: 'The hotel dining room' },
  'venue.sjo': { sv: 'Sjöboden', en: 'Sjöboden' },
  'venue.grill': { sv: 'Grillvagnen', en: 'Grillvagnen' },
  'venue.taco': { sv: 'Tacovagnen', en: 'Tacovagnen' },

  // Jämförelsen efter kvällen
  'cmp.kicker': { sv: 'Efter kvällen', en: 'After the evening' },
  'cmp.title': { sv: 'Byn i kväll', en: 'The village tonight' },
  'cmp.note': { sv: 'Under kvällen räknar bandet gäster. Här syns också vad varje gäst och varje stol gav.', en: 'During the evening the band counts guests. Here you also see what each guest and each seat brought in.' },
  'cmp.guests': { sv: 'Gäster', en: 'Guests' },
  'cmp.perGuest': { sv: 'Per gäst', en: 'Per guest' },
  'cmp.perSeat': { sv: 'Per stol', en: 'Per seat' },
  'cmp.noSeats': { sv: 'Inga stolar', en: 'No seats' },
  'cmp.van': { sv: 'Vagn', en: 'Van' },
  'cmp.next': { sv: 'Till butiken', en: 'On to the shop' },

  // Butiken
  'shop.kicker': { sv: 'Mellan kvällarna', en: 'Between evenings' },
  'shop.title': { sv: 'Butiken', en: 'The shop' },
  'shop.road': { sv: 'Vägen mot stjärnan', en: 'The road to the star' },
  'shop.today': { sv: 'I dag', en: 'Today' },
  'shop.star': { sv: 'Stjärnan', en: 'The star' },
  'shop.credits': { sv: '{n} krediter', en: '{n} credits' },
  'shop.price': { sv: '{n} krediter', en: '{n} credits' },
  'shop.medals': { sv: 'Medaljerna', en: 'Medals' },
  'shop.needs': { sv: 'Kräver {medal} i {pavilion}', en: 'Needs {medal} in {pavilion}' },
  'shop.needsShort': { sv: 'Kräver {medal}', en: 'Needs {medal}' },
  'shop.inSlot': { sv: 'I facket', en: 'In tomorrow' },
  'shop.have': { sv: 'Du har {medal}', en: 'You have {medal}' },
  'shop.noMedal': { sv: 'Ingen medalj än', en: 'No medal yet' },
  'shop.tomorrow': { sv: 'I morgon', en: 'Tomorrow' },
  'shop.course': { sv: 'Kurs i Måltidens hus i morgon bitti', en: 'A course at Måltidens hus tomorrow morning' },
  'shop.buy': { sv: 'Köp för {price}', en: 'Buy for {price}' },
  'shop.short': { sv: 'Krediterna räcker inte', en: 'Not enough credits' },
  'shop.locked': { sv: 'Medaljen öppnar den', en: 'The medal opens it' },
  'shop.owned': { sv: 'Köpt', en: 'Bought' },
  'shop.toSlot': { sv: 'Lägg i facket', en: 'Add to tomorrow' },
  'shop.fromSlot': { sv: 'Ta ur facket', en: 'Leave out tomorrow' },
  'shop.slot.title': { sv: 'Med till i morgon', en: 'Into tomorrow' },
  'shop.slot.empty': { sv: 'Tom plats', en: 'Empty slot' },
  'shop.slot.full': { sv: 'Facket är fullt. Ta ur något först.', en: 'Tomorrow is full. Take something out first.' },
  'shop.slot.note': { sv: 'Köpta förmågor behålls. Bara det som ligger i facket gäller nästa kväll.', en: 'Abilities you buy are kept. Only what you add to tomorrow applies next evening.' },
  'shop.slot.star': { sv: 'Fler platser vid stjärnan', en: 'More slots at the star' },
  'shop.slot.count': { sv: '{used} av {n}', en: '{used} of {n}' },
  'shop.done': { sv: 'Till morgonen', en: 'On to the morning' },

  'medal.bronze': { sv: 'brons', en: 'bronze' },
  'medal.silver': { sv: 'silver', en: 'silver' },
  'medal.gold': { sv: 'guld', en: 'gold' },
  'medal.platinum': { sv: 'platina', en: 'platinum' },
  'pav.stensota': { sv: 'Stensöta', en: 'Stensöta' },
  'pav.method': { sv: 'Metodköket', en: 'Metodköket' },
  'pav.library': { sv: 'Måltidsbiblioteket', en: 'Måltidsbiblioteket' },
  'pav.party': { sv: 'Kalastorget', en: 'Kalastorget' },
  'pav.theatre': { sv: 'Gastronomiska Teatern', en: 'Gastronomiska Teatern' },
  'role.sommelier': { sv: 'Sommeliern', en: 'The sommelier' },
  'role.chef': { sv: 'Kocken', en: 'The chef' },
  'role.floor': { sv: 'Servitörerna och bartendern', en: 'The waiters and the bartender' },

  // Förmågorna. Ett startförslag per paviljong (Vision Owner 2026-10-02).
  'ab.sommBottle.name': { sv: 'Sommeliern säljer in en flaska', en: 'The sommelier suggests a bottle' },
  'ab.sommBottle.fx': { sv: 'Vid loungerna föreslår sommeliern en hel flaska i stället för glas, och fler säger ja.', en: 'At the lounges the sommelier suggests a whole bottle instead of glasses, and more guests say yes.' },
  'ab.wineFridge.name': { sv: 'Vinkylen', en: 'The wine fridge' },
  'ab.wineFridge.fx': { sv: 'Vitt och bubbel håller rätt temperatur hela kvällen. Inget glas kommer tillbaka för att vinet är varmt.', en: 'White and sparkling stay at the right temperature all evening. No glass comes back because the wine is warm.' },
  'ab.wineTasting.name': { sv: 'Vinprovning för personalen', en: 'Wine tasting for the staff' },
  'ab.wineTasting.fx': { sv: 'Servitörerna svarar själva på frågor om vinlistan, så sommeliern hinner till fler bord.', en: 'The waiters answer questions about the wine list themselves, so the sommelier reaches more tables.' },
  'ab.fastPass.name': { sv: 'Snabbare pass', en: 'A quicker pass' },
  'ab.fastPass.fx': { sv: 'Köket skickar varmrätterna tätare när det är fullt, och väntan på maten blir kortare.', en: 'The kitchen sends mains out closer together when it is full, and the wait for food is shorter.' },
  'ab.leftovers.name': { sv: 'Dagens rätt av gårdagens rester', en: 'Today’s dish from yesterday’s leftovers' },
  'ab.leftovers.fx': { sv: 'Det som blev över i går blir en dagens rätt. Mindre svinn och ett mindre inköp på morgonen.', en: 'What was left over yesterday becomes a dish of the day. Less waste and a smaller order in the morning.' },
  'ab.mise.name': { sv: 'Mise en place-rutin', en: 'A mise en place routine' },
  'ab.mise.fx': { sv: 'Kocken har allt framme innan dörren öppnar, och den första timmen går fortare.', en: 'The chef has everything ready before the door opens, and the first hour runs faster.' },
  'ab.menuStory.name': { sv: 'Menyns berättelse', en: 'The story of the menu' },
  'ab.menuStory.fx': { sv: 'Menyn berättar var råvarorna kommer ifrån. Gästerna läser längre och väljer oftare det som kostar mer.', en: 'The menu tells guests where the produce comes from. They read for longer and more often choose what costs more.' },
  'ab.allergen.name': { sv: 'Allergenkort', en: 'Allergen cards' },
  'ab.allergen.fx': { sv: 'Varje rätt har ett kort med allergenerna, så servitören behöver inte fråga köket.', en: 'Every dish has a card listing its allergens, so the waiter need not ask the kitchen.' },
  'ab.critic.name': { sv: 'Förvarning om recensenten', en: 'Word of the critic' },
  'ab.critic.fx': { sv: 'På morgonen får du veta om recensenten kommer i kväll, men inte när.', en: 'In the morning you learn whether the critic is coming tonight, but not when.' },
  'ab.regulars.name': { sv: 'Stamgästboken', en: 'The regulars’ book' },
  'ab.regulars.fx': { sv: 'Per känner igen stamgästerna vid dörren. De kommer tillbaka oftare och har mer tålamod i kön.', en: 'Per knows the regulars at the door. They come back more often and are more patient in the queue.' },
  'ab.birthday.name': { sv: 'Födelsedagspaket', en: 'Birthday package' },
  'ab.birthday.fx': { sv: 'Sällskap som firar kan boka tårta och bubbel i förväg, så att köket vet i tid.', en: 'Parties who are celebrating can book cake and fizz in advance, so the kitchen knows in good time.' },
  'ab.lova.name': { sv: 'Lovas nätverk', en: 'Lova’s network' },
  'ab.lova.fx': { sv: 'Lova tipsar sina vänner, och fler gäster med socialt kapital söker sig till vinbaren.', en: 'Lova tells her friends, and more guests with social capital find their way to the wine bar.' },
  'ab.chefsTable.name': { sv: 'Kockens bord', en: 'The chef’s table' },
  'ab.chefsTable.fx': { sv: 'Ett bord vid köket där kocken serverar själv. Ett sällskap per kväll kan få det.', en: 'A table by the kitchen where the chef serves in person. One party each evening can have it.' },
  'ab.signature.name': { sv: 'Signaturrätten', en: 'The signature dish' },
  'ab.signature.fx': { sv: 'En rätt som bara finns hos dig. Recensenten frågar efter den.', en: 'A dish found only at your place. The critic asks for it.' }
};
