// dinVagStrings.tillagg.ts — ändrade och nya nycklar efter granskningen av D7, 2026-10-07. { sv, en }, brittisk engelska.
// Slås in i STRINGS över dinVagStrings.ts. Inga speltal: {n} är bistroSeats() ur bistroRoom.ts.
export const DIN_VAG_STRINGS_PATCH: Record<string, { sv: string; en: string }> = {
  'asa.role': { sv: "Har nycklarna till huset vid torget", en: "Holds the keys to the building on the square" },
  'asa.line': { sv: "”Jag har pratat med den som äger huset. Vinbaren har gått bra hela sommaren, och nu kan hela huset bli ditt. Vill du ta över och göra en bistro av det?”", en: "“I’ve spoken to the owner of the building. The wine bar has done well all summer, and now the whole building could be yours. Would you like to take it over and make it a bistro?”" },
  'asa.reply.take': { sv: "”Då kommer jag i morgon med ritningarna och ägarens kontrakt.”", en: "“Then I’ll come by tomorrow with the drawings and the owner’s contract.”" },
  'refit.c.tables.v': { sv: "Loungerna och DJ:n går ut, och rummet ryms i huset. Bänken längs norra väggen får fyra bord för två. Tre bord för fyra och fyra bord för två står i salen, och vid dörren blir det en väntplats.", en: "The lounges and the DJ go, and the room fits inside the building. The banquette along the north wall gets four tables for two. Three tables for four and four tables for two stand in the dining room, and there is a waiting spot by the door." },
  'refit.c.kitchen.v': { sv: "Väggen mot köket öppnas till ett pass med värmelampor. Baren blir kortare med tre barstolar och flyttar söderut, så att passet syns från salen.", en: "The kitchen wall opens into a pass with heat lamps. The bar gets shorter, with three stools, and moves south so the pass can be seen from the dining room." },
  'fika.grade.well': { sv: "Väl grundat", en: "Well grounded" },
  'fika.grade.partly': { sv: "Delvis grundat", en: "Partly grounded" },
  'fika.grade.weak': { sv: "Svagt grundat", en: "Weakly grounded" },
  'fika.scale': { sv: "Väl, delvis eller svagt grundat", en: "Well, partly or weakly grounded" },
  'dv.why.truck': { sv: "Torget på spelets karta. Vagnen står på torgytan mellan gatan Torget (w122157681) och Prästgatan, parallell med Torget. Grillvagnen står på rivalernas nya plats på torget, söder om vagnen och väster om vinbarens hus, parallell med Prästgatan. Luckan vetter mot torget och kön står på torgytan.", en: "The square on the game map. The truck stands on the square between Torget street (w122157681) and Prästgatan, parallel to Torget. Grillvagnen is on the rivals’ new spot on the square, south of the truck and west of the wine bar’s building, parallel to Prästgatan. Its hatch faces the square and the queue stands on the square." },
  'dv.why.asa': { sv: "Kameran går in till 10 m vid dörren efter stängning. Åsa står på trottoaren med nycklarna. Hon äger inte huset, hon förmedlar ägarens erbjudande. Inte än kostar ingenting och erbjudandet står kvar.", en: "The camera moves in to 10 m at the door after closing. Åsa stands on the pavement with the keys. She doesn’t own the building; she passes on the owner’s offer. Not yet costs nothing and the offer stands." },
  'dv.why.refit': { sv: "Rummet krymper till husets mått, 14,47 × 10,05 m (streckat), medan det töms. Bistron ryms i huset med {n} platser. Fyra steg: tömma, bygga, duka och tända.", en: "The room shrinks to the building’s size, 14.47 × 10.05 m (dashed), while it is cleared. The bistro fits inside with {n} seats. Four steps: clear, build, lay and light." },
  'dv.why.fika': { sv: "Rummet efter stängning: stolarna uppe, en pendel tänd över laget. Den som frågar lyfter handen (gesture.raiseHand) och får ljuset. Tre bedömningar: väl grundat i grönt, delvis grundat i papper och svagt grundat i mörk mässing. Aldrig rött.", en: "The room after closing: chairs up, one pendant lit over the team. The one who asks raises a hand (gesture.raiseHand) and gets the light. Three assessments: well grounded in green, partly grounded in paper and weakly grounded in dark brass. Never red." },
};

/** Tas bort ur dinVagStrings.ts: dilemmakortet har inte längre rätt och fel. */
export const DIN_VAG_STRINGS_REMOVED = ['fika.right', 'fika.wrong', 'fika.held', 'fika.two'];
