// everydayStrings — vardagens koreografi (efter leverans 3, 2026-10-01). { sv, en }, brittisk engelska.
// Slås in i STRINGS i nexusStrings.ts. evd.* är prototypens etiketter, kapitlen och deras syfte;
// clip.*, prop.*, room.* och queue.* används i spelet. Inga speltal.

export const EVERYDAY_STRINGS: Record<string, { sv: string; en: string }> = { sv, en }, brittisk engelska.
// Samma nycklar som everydayStrings.ts. Inga speltal i texterna.
window.NEXUS_STR_EVD = {
  'evd.kicker': { sv: 'Efter leverans 3 · vardagens koreografi', en: 'After delivery 3 · everyday choreography' },
  'evd.title': { sv: 'Vardagens koreografi', en: 'Everyday choreography' },
  'evd.size': { sv: 'Skärmstorlek', en: 'Screen size' },
  'evd.play': { sv: 'Spela', en: 'Play' },
  'evd.pause': { sv: 'Pausa', en: 'Pause' },
  'evd.record': { sv: 'Spela in WebM', en: 'Record WebM' },
  'evd.recording': { sv: 'Spelar in …', en: 'Recording …' },
  'evd.cam': { sv: 'Kamera', en: 'Camera' },
  'evd.cam.game': { sv: 'Spelets, 24 m', en: 'Game, 24 m' },
  'evd.cam.near': { sv: 'Nära, 11–13 m', en: 'Close, 11–13 m' },
  'evd.why': { sv: 'Syfte', en: 'Purpose' },
  'evd.scene.mise': { sv: 'Mise en place', en: 'Mise en place' },
  'evd.scene.welcome': { sv: 'Värden i dörren', en: 'The host at the door' },
  'evd.scene.parties': { sv: 'Sällskap som kommer och går', en: 'Parties arriving and leaving' },
  'evd.scene.moments': { sv: 'Personalens små stunder', en: 'The staff’s small moments' },
  'evd.scene.queue': { sv: 'Kön vid dörren', en: 'The queue at the door' },

  'evd.ch.mise.board': { sv: 'Per skriver kvällens viner på tavlan', en: 'Per chalks tonight’s wines on the board' },
  'evd.why.mise.board': { sv: 'Gästerna ska se vad som finns innan de har satt sig.', en: 'Guests should see what’s on before they sit down.' },
  'evd.ch.mise.tables': { sv: 'Sara dukar småborden', en: 'Sara lays the small tables' },
  'evd.why.mise.tables': { sv: 'Två bord ska vara dukade innan dörren öppnas.', en: 'Two tables must be laid before the door opens.' },
  'evd.ch.mise.fridge': { sv: 'Elin fyller vinkylen', en: 'Elin stocks the wine fridge' },
  'evd.why.mise.fridge': { sv: 'De vita vinerna behöver tid för att bli kalla.', en: 'The whites need time to chill.' },
  'evd.ch.mise.glasses': { sv: 'Mira putsar glasen och ställer dem på rad', en: 'Mira polishes the glasses and lines them up' },
  'evd.why.mise.glasses': { sv: 'Ett glas med fläckar syns i ljuset från disken.', en: 'A smeared glass shows in the bar light.' },
  'evd.ch.mise.book': { sv: 'Per går igenom kvällens bokningar', en: 'Per goes through tonight’s bookings' },
  'evd.why.mise.book': { sv: 'Han vet vilka som kommer och var de ska sitta.', en: 'He knows who is coming and where they will sit.' },
  'evd.ch.mise.door': { sv: 'Per öppnar dörren', en: 'Per opens the door' },
  'evd.why.mise.door': { sv: 'Allt är klart. Kvällen börjar.', en: 'Everything is ready. The evening begins.' },

  'evd.ch.wel.arrive': { sv: 'Ett sällskap om tre kommer in', en: 'A party of three comes in' },
  'evd.why.wel.arrive': { sv: 'Dörren är det första de ser av kvällen.', en: 'The door is the first thing they see of the evening.' },
  'evd.ch.wel.greet': { sv: 'Per kliver fram och hälsar välkommen', en: 'Per steps forward and welcomes them' },
  'evd.why.wel.greet': { sv: 'Ingen ska behöva stå och vänta på att bli sedd.', en: 'Nobody should have to wait to be noticed.' },
  'evd.ch.wel.coats': { sv: 'Två hänger av sig vid dörren', en: 'Two hang up their coats by the door' },
  'evd.why.wel.coats': { sv: 'Sällskapet samlas innan de går in tillsammans.', en: 'The party gathers before going in together.' },
  'evd.ch.wel.menus': { sv: 'Per tar menyerna från pulten', en: 'Per takes the menus from the stand' },
  'evd.why.wel.menus': { sv: 'Menyerna följer med gästerna, inte tvärtom.', en: 'The menus go with the guests, not the other way round.' },
  'evd.ch.wel.escort': { sv: 'Per visar vägen till lounge B', en: 'Per leads the way to lounge B' },
  'evd.why.wel.escort': { sv: 'Han går före, i gästernas takt.', en: 'He walks ahead, at the guests’ pace.' },
  'evd.ch.wel.present': { sv: 'Menyerna, en i taget', en: 'The menus, one at a time' },
  'evd.why.wel.present': { sv: 'Var och en får sin meny i handen när de sitter.', en: 'Each guest gets a menu in hand once seated.' },
  'evd.ch.wel.bread': { sv: 'Kocken ställer fram brödet, Sara hämtar', en: 'The cook puts the bread up, Sara collects it' },
  'evd.why.wel.bread': { sv: 'Brödet kommer medan de läser, så att väntan känns kortare.', en: 'Bread arrives while they read, so the wait feels shorter.' },
  'evd.ch.wel.pour': { sv: 'Elin häller upp fördrinken vid disken', en: 'Elin pours the aperitifs at the bar' },
  'evd.why.wel.pour': { sv: 'Glasen är fyllda innan de bärs ut.', en: 'The glasses are filled before they are carried out.' },
  'evd.ch.wel.water': { sv: 'Sara häller upp vatten', en: 'Sara pours the water' },
  'evd.why.wel.water': { sv: 'Vatten utan att någon behöver be om det.', en: 'Water without anyone having to ask.' },
  'evd.ch.wel.aperitif': { sv: 'Elin serverar fördrinken från brickan', en: 'Elin serves the aperitifs from the tray' },
  'evd.why.wel.aperitif': { sv: 'Ett glas i taget, från höger, med brickan stilla.', en: 'One glass at a time, from the right, with the tray held steady.' },

  'evd.ch.par.solo': { sv: 'En gäst kommer ensam och får en plats i baren', en: 'A guest arrives alone and is shown to the bar' },
  'evd.why.par.solo': { sv: 'Den som kommer ensam ska snabbt få någon att prata med.', en: 'Someone who comes alone should soon have someone to talk to.' },
  'evd.ch.par.leave': { sv: 'Tre reser sig och går tillsammans', en: 'Three get up and leave together' },
  'evd.why.par.leave': { sv: 'Sällskapet går i den långsammastes takt.', en: 'The party walks at the pace of its slowest member.' },
  'evd.ch.par.clear': { sv: 'Sara dukar av lounge A', en: 'Sara clears lounge A' },
  'evd.why.par.clear': { sv: 'Bordet ska vara klart när nästa sällskap står i dörren.', en: 'The table must be ready when the next party is at the door.' },
  'evd.ch.par.decant': { sv: 'Elin dekanterar vinet vid lounge B', en: 'Elin decants the wine at lounge B' },
  'evd.why.par.decant': { sv: 'Vinet behöver luft, och bordet får se hur det görs.', en: 'The wine needs air, and the table gets to watch.' },
  'evd.ch.par.wait': { sv: 'Två väntar på dörrmattan', en: 'Two wait on the doormat' },
  'evd.why.par.wait': { sv: 'Per har hälsat, så de vet att de är sedda.', en: 'Per has greeted them, so they know they’ve been seen.' },
  'evd.ch.par.coats': { sv: 'De tre tar sina rockar, Per håller dörren', en: 'The three collect their coats, Per holds the door' },
  'evd.why.par.coats': { sv: 'Avskedet är det sista de minns.', en: 'The goodbye is the last thing they remember.' },
  'evd.ch.par.wipe': { sv: 'Sara torkar bordet och kontrollerar det', en: 'Sara wipes the table and checks it' },
  'evd.why.par.wipe': { sv: 'Ett nytt sällskap ska inte se spåren av det förra.', en: 'A new party should see no trace of the last one.' },
  'evd.ch.par.seat': { sv: 'Per tar paret till lounge A', en: 'Per takes the couple to lounge A' },
  'evd.why.par.seat': { sv: 'Bordet är klart, så de kan gå direkt in.', en: 'The table is ready, so they can go straight through.' },

  'evd.ch.mom.chat': { sv: 'Mira och Sara byter några ord över disken', en: 'Mira and Sara have a quick word across the bar' },
  'evd.why.mom.chat': { sv: 'Glaset är klart, och några ord håller ihop laget.', en: 'The glass is ready, and a quick word keeps the team together.' },
  'evd.ch.mom.water': { sv: 'Elin fyller på vatten i lounge B', en: 'Elin tops up the water in lounge B' },
  'evd.why.mom.water': { sv: 'Innan de behöver be om det.', en: 'Before they need to ask.' },
  'evd.ch.mom.wipe': { sv: 'Mira torkar disken', en: 'Mira wipes the bar' },
  'evd.why.mom.wipe': { sv: 'Där glaset stod ska det vara torrt före nästa.', en: 'Where the glass stood must be dry before the next.' },
  'evd.ch.mom.check': { sv: 'Per kontrollerar ett dukat bord', en: 'Per checks a laid table' },
  'evd.why.mom.check': { sv: 'Nästa sällskap ska få ett bord som är rätt.', en: 'The next party should get a table that is just right.' },
  'evd.ch.mom.plate': { sv: 'Kocken lägger upp, Sara bär ut', en: 'The cook plates up, Sara carries it out' },
  'evd.why.mom.plate': { sv: 'Varm mat väntar inte på passet.', en: 'Hot food doesn’t wait on the pass.' },

  'evd.ch.que.states': { sv: 'Kön vid dörren', en: 'The queue at the door' },
  'evd.why.que.states': { sv: 'Lugna på mattan, och på trottoaren lugna, otåliga och ett par på väg att gå.', en: 'Calm on the mat, and on the pavement calm, impatient and a couple about to leave.' },
  'evd.ch.que.first': { sv: 'Per pratar med de första', en: 'Per speaks to the first in line' },
  'evd.why.que.first': { sv: 'De ska veta ungefär hur länge de får vänta.', en: 'They should know roughly how long they’ll wait.' },
  'evd.ch.que.leaveTable': { sv: 'Paret vid småbord B går', en: 'The couple at small table B leave' },
  'evd.why.que.leaveTable': { sv: 'Ett bord blir ledigt.', en: 'A table comes free.' },
  'evd.ch.que.impatient': { sv: 'Per går ut till de otåliga', en: 'Per goes out to the impatient pair' },
  'evd.why.que.impatient': { sv: 'Den som syns otålig får besked först.', en: 'Whoever looks impatient hears from him first.' },
  'evd.ch.que.leaving': { sv: 'Två längre bak ger upp och går', en: 'Two further back give up and leave' },
  'evd.why.que.leaving': { sv: 'Ingen hann fram till dem i tid.', en: 'Nobody reached them in time.' },
  'evd.ch.que.clear': { sv: 'Sara gör bordet klart', en: 'Sara gets the table ready' },
  'evd.why.que.clear': { sv: 'Kön blir kortare vid bordet, inte vid dörren.', en: 'The queue gets shorter at the table, not at the door.' },
  'evd.ch.que.sign': { sv: 'Sara ger Per ett tecken', en: 'Sara signals to Per' },
  'evd.why.que.sign': { sv: 'Bordet är klart. Han behöver inte gå dit och titta.', en: 'The table is ready. He doesn’t need to go and look.' },
  'evd.ch.que.seat': { sv: 'Per tar paret från mattan till bordet', en: 'Per takes the couple from the mat to the table' },
  'evd.why.que.seat': { sv: 'Först in är först till bordet.', en: 'First in, first seated.' },
  'evd.ch.que.move': { sv: 'Kön flyttar fram', en: 'The queue moves up' },
  'evd.why.que.move': { sv: 'Nästa sällskap kliver in på mattan.', en: 'The next party steps onto the mat.' },

  'clip.host.greetDoor': { sv: 'Välkomnar i dörren', en: 'Welcomes at the door' },
  'clip.host.takeMenus': { sv: 'Tar menyerna från pulten', en: 'Takes the menus from the stand' },
  'clip.host.presentMenu': { sv: 'Räcker över menyn', en: 'Hands over the menu' },
  'clip.host.checkBook': { sv: 'Läser bokningarna', en: 'Checks the bookings' },
  'clip.waiter.setBread': { sv: 'Ställer fram brödet', en: 'Sets down the bread' },
  'clip.waiter.pourWater': { sv: 'Häller upp vatten', en: 'Pours the water' },
  'clip.waiter.serveAperitif': { sv: 'Serverar fördrinken', en: 'Serves the aperitif' },
  'clip.waiter.setTable': { sv: 'Dukar ett kuvert', en: 'Lays a place setting' },
  'clip.somm.decant': { sv: 'Dekanterar', en: 'Decants' },
  'clip.bar.polishGlass': { sv: 'Putsar glas', en: 'Polishes a glass' },
  'clip.bar.stockFridge': { sv: 'Fyller kylen', en: 'Stocks the fridge' },
  'clip.staff.carryCrate': { sv: 'Bär en back', en: 'Carries a crate' },
  'clip.staff.writeBoard': { sv: 'Skriver på tavlan', en: 'Writes on the board' },
  'clip.staff.chat': { sv: 'Byter några ord', en: 'Has a quick word' },
  'clip.staff.checkTable': { sv: 'Kontrollerar bordet', en: 'Checks the table' },
  'clip.staff.wipeTable': { sv: 'Torkar bordet', en: 'Wipes the table' },
  'clip.guest.queueCalm': { sv: 'Väntar lugnt', en: 'Waits calmly' },
  'clip.guest.queueImpatient': { sv: 'Väntar otåligt', en: 'Waits impatiently' },
  'clip.guest.queueLeaving': { sv: 'Ger upp och går', en: 'Gives up and leaves' },
  'clip.guest.hangCoat': { sv: 'Hänger av sig', en: 'Hangs up the coat' },
  'clip.guest.takeCoat': { sv: 'Tar på sig rocken', en: 'Puts the coat on' },

  'prop.breadBasket': { sv: 'Brödkorg', en: 'Bread basket' },
  'prop.decanter': { sv: 'Karaff för dekantering', en: 'Decanter' },
  'prop.flute': { sv: 'Fördrinksglas', en: 'Aperitif glass' },
  'prop.crate': { sv: 'Back med flaskor', en: 'Crate of bottles' },

  'room.host': { sv: 'Värdens plats vid pulten', en: 'The host’s place at the stand' },
  'room.queue.inside': { sv: 'Kön på dörrmattan', en: 'Queue on the doormat' },
  'room.queue.outside': { sv: 'Kön på trottoaren', en: 'Queue on the pavement' },
  'room.pavement': { sv: 'Trottoaren', en: 'Pavement' },
  'room.menuBoard': { sv: 'Tavlan', en: 'Menu board' },
  'room.barFridge': { sv: 'Vinkylen', en: 'Wine fridge' },
  'room.mise.board': { sv: 'Vid tavlan', en: 'At the board' },
  'room.mise.fridge': { sv: 'Vid kylen', en: 'At the fridge' },
  'room.mise.store': { sv: 'Vid vinförrådet', en: 'At the wine store' },
  'room.mise.polish': { sv: 'Vid glasen', en: 'At the glasses' },
  'room.mise.setTables': { sv: 'Vid småborden', en: 'At the small tables' },
  'queue.calm': { sv: 'Lugn', en: 'Calm' },
  'queue.impatient': { sv: 'Otålig', en: 'Impatient' },
  'queue.leaving': { sv: 'På väg att gå', en: 'About to leave' }
};
