// kvittStrings.ts — tillägg till D5 2026-10-05: kvitt eller dubbelt (ORDER 305 B) och veckoavräkningen. { sv, en }, brittisk engelska.
// Slås in i STRINGS. Platshållare i klamrar fylls ur balance.ts. f5.* är prototypens panel. Säkerheten (conf.*) används inte längre i raketen.
export const KVITT_STRINGS: Record<string, { sv: string; en: string }> = {
  'stake.pot': { sv: 'Potten', en: 'The pot' },
  'stake.onTable': { sv: 'Insatsen ligger på steget', en: 'Your stake is on the step' },
  'stake.doubled': { sv: 'Dubbelt + steget', en: 'Doubled + the step' },
  'stake.ifRight': { sv: 'Om rätt', en: 'If right' },
  'stake.none': { sv: 'Potten var tom', en: 'The pot was empty' },
  'stake.gone': { sv: 'Potten är borta', en: 'The pot is gone' },
  'stake.stay': { sv: 'Stanna, och ta det du har', en: 'Stop, and take what you have' },
  'stake.first': { sv: 'Stegets kredit', en: 'The step’s credit' },
  'stake.stay.sub1': { sv: '1 kredit är din', en: '1 credit is yours' },
  'stake.stay.sub': { sv: '{n} krediter är dina', en: '{n} credits are yours' },
  'stake.goOn': { sv: 'Gå vidare, med allt på spel', en: 'Go on, with everything at stake' },
  'stake.goOn.sub': { sv: '{step}: {a} → {b} om rätt, 0 om fel', en: '{step}: {a} → {b} if right, 0 if wrong' },
  'stake.timeout': { sv: 'När tiden går ut stannar du', en: 'When time runs out, you stop' },
  'stake.picked.stay': { sv: 'Du stannar. Krediterna är dina.', en: 'You stop. The credits are yours.' },
  'stake.picked.goOn': { sv: 'Du går vidare. Potten ligger kvar.', en: 'You go on. The pot stays on the table.' },
  'rocket.lesson': { sv: 'Rumstempererat tar fram alkoholen och gör vinet platt mot fisken. Chablis vill ha ungefär tio grader.', en: 'Room temperature brings out the alcohol and flattens the wine against the fish. Chablis wants about ten degrees.' },
  'rocket.lesson.kicker': { sv: 'Det här hade hållit', en: 'This would have held' },

  // ----- veckoavräkningen (tillägg 2026-10-05) -----
  'week.kicker': { sv: 'Veckoavräkningen · söndag', en: 'The weekly reckoning · Sunday' },
  'week.title': { sv: 'Vecka 2 i Vinbaren', en: 'Week 2 at the wine bar' },
  'week.sust': { sv: 'Hållbarheten i veckan', en: 'Sustainability this week' },
  'week.econ': { sv: 'Ekonomisk hållbarhet', en: 'Economic sustainability' }, 'week.econ.cause': { sv: 'Marginalen höll fem kvällar av sex', en: 'The margin held five evenings out of six' },
  'week.eco': { sv: 'Ekologisk hållbarhet', en: 'Ecological sustainability' }, 'week.eco.cause': { sv: 'Svinnet drog ned, mest röding', en: 'Waste pulled it down, mostly char' },
  'week.social': { sv: 'Social hållbarhet', en: 'Social sustainability' }, 'week.social.cause': { sv: 'Personalens ork och trivsel i veckan', en: 'Your staff’s energy and morale this week' },
  'week.social.note': { sv: 'Sara var slut tre kvällar av sex. En ledig kväll eller en kurs lyfter henne.', en: 'Sara was worn out three evenings out of six. A night off or a course would lift her.' },
  'week.of10': { sv: '{n} av 10', en: '{n} of 10' },
  'week.lastWeek': { sv: 'förra veckan {n}', en: 'last week {n}' },
  'week.next': { sv: 'Till söndagstidningen', en: 'To the Sunday paper' },
  'f5.sc.stake': { sv: '3 · Kvitt eller dubbelt', en: '3 · Double or nothing' },
  'f5.why.stake': { sv: 'Låset, väntan vid bordet, avgörandet och valet efter varje rätt steg. Potten i krediter: 1, 3, 7. 3,8 s från trycket till avgörandet, 8 s att välja.', en: 'The lock, the wait at the table, the verdict and the choice after each right step. The pot in credits: 1, 3, 7. 3.8 s from the press to the verdict, 8 s to choose.' },
  'f5.stake.step': { sv: 'Steget', en: 'Step' },
  'f5.stake.outcome': { sv: 'Svaret', en: 'The answer' }, 'f5.right': { sv: 'Rätt', en: 'Right' }, 'f5.wrong': { sv: 'Fel', en: 'Wrong' },
  'f5.sound': { sv: 'Ljudskisserna', en: 'Sound sketches' },
  'f5.ch.before': { sv: 'Svar och säkerhet valda', en: 'Answer and confidence chosen' }, 'f5.ch.slock': { sv: '1 · Låset', en: '1 · The lock' }, 'f5.ch.wait': { sv: '2 · Väntan vid bordet', en: '2 · The wait at the table' },
  'f5.ch.decide': { sv: '3 · Avgörandet', en: '3 · The verdict' }, 'f5.ch.choice': { sv: '4 · Valet mellan stegen', en: '4 · The choice between steps' }, 'f5.ch.timeout': { sv: 'Tiden ut: du stannar', en: 'Time up: you stop' },
  'f5.ch.outBack': { sv: 'Tillbaka till 24 m, förklaringen', en: 'Back to 24 m, the explanation' },
  'f5.sc.week': { sv: '9 · Veckoavräkningen', en: '9 · The weekly reckoning' },
  'f5.why.week': { sv: 'Raden för social hållbarhet: veckans ork och trivsel per person, i samma form som de andra raderna.', en: 'The social sustainability row: each person’s energy and morale over the week, in the same form as the other rows.' },
};
