// arrivalStrings.ts — ankomsten till Grythyttan. Utkast för granskning, 62 nycklar, { sv, en }.
// Följer manus/ankomsten.md. {name} är spelarens namn från biljetten, {time} nästa avgång ur tidtabellen.

export const ARRIVAL_STRINGS = {
  "arrival.ticket.sv": { sv: "Enkel biljett · Örebro–Grythyttan", en: "Enkel biljett · Örebro–Grythyttan" },
  "arrival.ticket.en": { sv: "Single ticket · Örebro–Grythyttan", en: "Single ticket · Örebro–Grythyttan" },
  "arrival.ticket.name": { sv: "Resenär", en: "Passenger" },
  "arrival.ticket.return": { sv: "Tur och retur · Örebro–Grythyttan", en: "Return ticket · Örebro–Grythyttan" },
  "arrival.noor.1": { sv: "Enkel, ser jag. Jag med. Då har vi bestämt oss, du och jag.", en: "Single, I see. Me too. So we've both made up our minds." },
  "arrival.you.1a": { sv: "Jag vet inte om jag har bestämt mig.", en: "I'm not sure I have." },
  "arrival.you.1b": { sv: "Ja. Jag tänker stanna.", en: "Yes. I mean to stay." },
  "arrival.noor.2a": { sv: "Det visste inte jag heller, första veckan på avdelningen. Det är tjugo år sedan.", en: "Neither did I, my first week on the ward. That was twenty years ago." },
  "arrival.noor.2b": { sv: "Bra. Då är vi två.", en: "Good. That makes two of us." },
  "arrival.noor.3": { sv: "Jag heter Noor. Och du?", en: "I'm Noor. And you?" },
  "arrival.noor.4": { sv: "Ingrid står alltid i dörren och tar emot. När jag presenterar dig, ska jag säga hon, han eller hen?", en: "Ingrid always meets everyone at the door. When I introduce you, should I say she, he or they?" },
  "arrival.pronoun.she": { sv: "Hon", en: "She" },
  "arrival.pronoun.he": { sv: "Han", en: "He" },
  "arrival.pronoun.they": { sv: "Hen", en: "They" },
  "arrival.pronoun.name": { sv: "Säg bara mitt namn", en: "Just use my name" },
  "arrival.noor.5": { sv: "Då säger jag det.", en: "I'll say that, then." },
  "arrival.driver": { sv: "Grythyttan. Sista hållplatsen för i kväll.", en: "Grythyttan. Last stop tonight." },
  "arrival.stop.none": { sv: "Ingen buss tillbaka i kväll.", en: "No bus back tonight." },
  "arrival.stop.next": { sv: "Nästa buss: {time}", en: "Next bus: {time}" },
  "arrival.noor.6": { sv: "Det finns bara en väg härifrån. Upp till huset.", en: "There's only one way from here. Up to the house." },
  "arrival.student.wave": { sv: "Hitåt! Huset ligger den här vägen.", en: "This way! The house is up here." },
  "arrival.lova.1": { sv: "Välkomna! Rakt fram, ni ser ljuset.", en: "Welcome! Straight on, you'll see the lights." },
  "arrival.lova.2": { sv: "Jag är Lova. Kom förbi när ni har ätit, jag vet var allt finns i byn.", en: "I'm Lova. Come by once you've eaten. I know where everything is in the village." },
  "arrival.noor.intro.she": { sv: "Ingrid, det här är {name}. Hon satt bredvid mig hela vägen.", en: "Ingrid, this is {name}. She sat next to me the whole way." },
  "arrival.noor.intro.he": { sv: "Ingrid, det här är {name}. Han satt bredvid mig hela vägen.", en: "Ingrid, this is {name}. He sat next to me the whole way." },
  "arrival.noor.intro.they": { sv: "Ingrid, det här är {name}. Hen satt bredvid mig hela vägen.", en: "Ingrid, this is {name}. They sat next to me the whole way." },
  "arrival.noor.intro.name": { sv: "Ingrid, det här är {name}. {name} satt bredvid mig hela vägen.", en: "Ingrid, this is {name}. {name} sat next to me the whole way." },
  "arrival.ingrid.1": { sv: "Välkommen, {name}. Alla som bor här skriver in sig.", en: "Welcome, {name}. Everyone who lives here signs in." },
  "arrival.ingrid.2": { sv: "Var vill du börja? Du får pröva allt, men någonstans börjar man.", en: "Where would you like to start? You'll try everything, but you have to start somewhere." },
  "arrival.station.kitchen": { sv: "Köket", en: "The kitchen" },
  "arrival.station.wine": { sv: "Vinet", en: "The wine" },
  "arrival.station.floor": { sv: "Salen", en: "The floor" },
  "arrival.ingrid.3": { sv: "Det du lär dig här skrivs in i boken och följer med dig. Skriv under, så vet huset att det är ditt.", en: "What you learn here goes into the book and stays with you. Sign, so the house knows it's yours." },
  "arrival.ledger.sign": { sv: "Skriv under", en: "Sign" },
  "arrival.ingrid.4": { sv: "Nu är du inskriven. Men du bor inte här än.", en: "Now you're signed in. But you don't live here yet." },
  "arrival.ingrid.5": { sv: "Här får den som har lagat något till bordet en nyckel. I kväll dukar vi. Det räknas.", en: "Here, whoever has made something for the table gets a key. Tonight we're laying it. That counts." },
  "arrival.q1": { sv: "Var ska kniven ligga?", en: "Where does the knife go?" },
  "arrival.a1_1": { sv: "Till höger om tallriken, eggen in mot den", en: "Right of the plate, blade facing it" },
  "arrival.a1_2": { sv: "Till höger om tallriken, eggen ut från den", en: "Right of the plate, blade facing out" },
  "arrival.a1_3": { sv: "Till vänster om tallriken, bredvid gaffeln", en: "Left of the plate, beside the fork" },
  "arrival.a1_4": { sv: "Ovanför tallriken, med skaftet åt höger", en: "Above the plate, handle to the right" },
  "arrival.why1": { sv: "Kniven ligger till höger med eggen mot tallriken. Då ligger den rätt i handen, och eggen pekar inte mot grannen.", en: "The knife goes on the right with the blade towards the plate. It sits right in the hand, and the blade doesn't point at your neighbour." },
  "arrival.q2": { sv: "Hur bär du fyra vinglas utan bricka?", en: "How do you carry four wine glasses without a tray?" },
  "arrival.a2_1": { sv: "Upp och ned, med foten mellan fingrarna", en: "Upside down, stems between your fingers" },
  "arrival.a2_2": { sv: "Två i varje hand, med ett grepp runt kupan", en: "Two in each hand, gripped by the bowl" },
  "arrival.a2_3": { sv: "Staplade i varandra, med båda händerna runt", en: "Stacked inside each other, both hands round" },
  "arrival.a2_4": { sv: "I ena handen, med ett finger i varje glas", en: "In one hand, one finger inside each glass" },
  "arrival.why2": { sv: "Glas bärs i foten, aldrig i kupan eller kanten där gästen dricker. Upp och ned mellan fingrarna går fyra glas säkert i en hand.", en: "Glasses are carried by the stem, never by the bowl or the rim the guest drinks from. Upside down between your fingers, four fit safely in one hand." },
  "arrival.q3": { sv: "En student kommer sent, och alla platser är tagna. Vad gör du?", en: "A student arrives late and every seat is taken. What do you do?" },
  "arrival.a3_1": { sv: "Ber alla flytta ihop och dukar en plats till", en: "Ask everyone to shift up and lay one more place" },
  "arrival.a3_2": { sv: "Dukar en plats vid det lilla bordet bredvid", en: "Lay a place at the small table next to it" },
  "arrival.a3_3": { sv: "Ger hen din egen plats och äter själv senare", en: "Give them your own place and eat later yourself" },
  "arrival.a3_4": { sv: "Säger till Ingrid att det saknas en plats", en: "Tell Ingrid that a place is missing" },
  "arrival.why3": { sv: "Vid långbordet får alla plats. Att flytta ihop tar en minut och gör ingen till gäst vid sidan av.", en: "Everyone fits at the long table. Shifting up takes a minute and leaves no one sitting on the side." },
  "arrival.near3_3": { sv: "Det är vänligt, men då saknas du vid bordet. Här räknas alla, också du.", en: "That's kind, but then you are missing from the table. Everyone counts here, you included." },
  "arrival.ingrid.6": { sv: "Till bordet. Det är det som håller ihop oss.", en: "To the table. It's what holds us together." },
  "arrival.ingrid.7": { sv: "Rummet ovanför köket. Nu bor du här.", en: "The room above the kitchen. Now you live here." },
  "arrival.end": { sv: "Nexus", en: "Nexus" },
  "arrival.driver.leave": { sv: "Ska du med tillbaka?", en: "Coming back with us?" },
  "arrival.you.leave": { sv: "Ja, jag åker nu.", en: "Yes, I'm leaving now." },
  "arrival.you.stay": { sv: "Nej, jag stannar.", en: "No, I'm staying." },
  "arrival.ingrid.back": { sv: "{name}. Jag visste att du skulle komma tillbaka.", en: "{name}. I knew you'd be back." },
} as const;
