// theatreStrings — text för teaterns grund: klippens, samspelens och rekvisitans namn, och
// prototypens etiketter. { sv, en }, brittisk engelska. Slås in i STRINGS i nexusStrings.ts.
// Inga speltal i texterna (från och med leverans 2): längder och tider formateras i koden.

export const THEATRE_STRINGS = {
  'theatre.title': { sv: 'Teaterns grund', en: 'The stagecraft' },
  'theatre.kicker': { sv: 'Leverans 2 · rummets kroppsspråk', en: 'Delivery 2 · the room’s body language' },
  'theatre.mode.service': { sv: 'Servering', en: 'Service' },
  'theatre.mode.rockets': { sv: 'Raketer', en: 'Rockets' },
  'theatre.mode.clips': { sv: 'Klipp', en: 'Clips' },
  'theatre.mode.props': { sv: 'Rekvisita', en: 'Props' },
  'theatre.play': { sv: 'Spela', en: 'Play' },
  'theatre.pause': { sv: 'Pausa', en: 'Pause' },
  'theatre.view.game': { sv: 'Spelets kamera', en: 'Game camera' },
  'theatre.view.near': { sv: 'Närmare', en: 'Closer' },
  'theatre.tempo': { sv: 'Tempo', en: 'Tempo' },
  'tempo.calm': { sv: 'Lugn', en: 'Calm' },
  'tempo.normal': { sv: 'Normal', en: 'Normal' },
  'tempo.stressed': { sv: 'Stressad', en: 'Stressed' },
  'theatre.tempos.note': { sv: 'Samma klipp i tre tempon: lugn till vänster, stressad till höger.', en: 'The same clip in three tempos: calm on the left, stressed on the right.' },
  'clip.length': { sv: 'Längd', en: 'Length' },
  'clip.seconds': { sv: '{s} s', en: '{s} s' },
  'clip.loop': { sv: 'Loop', en: 'Loop' },
  'clip.once': { sv: 'Engång', en: 'Once' },
  'clip.walks': { sv: 'Går', en: 'Walks' },
  'clip.stance': { sv: 'Läge', en: 'Stance' },
  'clip.holds': { sv: 'Håller', en: 'Holds' },
  'clip.events': { sv: 'Händelser', en: 'Events' },
  'clip.next': { sv: 'Kan följas av', en: 'Can be followed by' },
  'clip.nothing': { sv: 'Inget', en: 'Nothing' },
  'stance.stand': { sv: 'står', en: 'standing' },
  'stance.seated': { sv: 'sitter', en: 'seated' },
  'stance.walk': { sv: 'går', en: 'walking' },
  'stance.hurt': { sv: 'skadad', en: 'hurt' },
  'event.grab': { sv: 'tar', en: 'takes' },
  'event.release': { sv: 'ställer ned', en: 'puts down' },
  'event.give': { sv: 'räcker över', en: 'hands over' },
  'event.switch': { sv: 'byter hand', en: 'switches hands' },
  'event.stack': { sv: 'staplar', en: 'stacks' },
  'event.clink': { sv: 'klinkar', en: 'clinks' },
  'event.cork': { sv: 'korken ur', en: 'cork out' },
  'event.plated': { sv: 'upplagt', en: 'plated' },
  'event.bell': { sv: 'ringer', en: 'rings' },
  'event.pay': { sv: 'betalar', en: 'pays' },
  'event.cut': { sv: 'skär sig', en: 'cuts themselves' },

  'group.staff': { sv: 'Personal', en: 'Staff' },
  'group.waiter': { sv: 'Servitör', en: 'Waiter' },
  'group.bartender': { sv: 'Bartender', en: 'Bartender' },
  'group.sommelier': { sv: 'Sommelier', en: 'Sommelier' },
  'group.cook': { sv: 'Kock', en: 'Cook' },
  'group.dishwasher': { sv: 'Diskare', en: 'Kitchen porter' },
  'group.guest': { sv: 'Gäster', en: 'Guests' },
  'group.rocket': { sv: 'Till raketerna', en: 'For the rockets' },

  'clip.staff.idle': { sv: 'Står och håller uppsikt', en: 'Stands and keeps watch' },
  'clip.staff.walk': { sv: 'Går', en: 'Walks' },
  'clip.staff.dodge': { sv: 'Väjer i gången', en: 'Steps aside in the aisle' },
  'clip.waiter.carryPlate': { sv: 'Bär en tallrik', en: 'Carries one plate' },
  'clip.waiter.carryTwoPlates': { sv: 'Bär två tallrikar', en: 'Carries two plates' },
  'clip.waiter.carryTray': { sv: 'Bär bricka', en: 'Carries a tray' },
  'clip.waiter.pickUp': { sv: 'Tar tallriken från passet', en: 'Takes the plate from the pass' },
  'clip.waiter.serve': { sv: 'Serverar vid bordet', en: 'Serves at the table' },
  'clip.waiter.clear': { sv: 'Dukar av', en: 'Clears the table' },
  'clip.waiter.takeOrder': { sv: 'Tar beställning', en: 'Takes the order' },
  'clip.waiter.presentBill': { sv: 'Lämnar notan', en: 'Presents the bill' },
  'clip.bar.pour': { sv: 'Häller', en: 'Pours' },
  'clip.bar.setDown': { sv: 'Ställer fram', en: 'Sets it down' },
  'clip.bar.wipe': { sv: 'Torkar av disken', en: 'Wipes the counter' },
  'clip.somm.present': { sv: 'Visar flaskan', en: 'Presents the bottle' },
  'clip.somm.open': { sv: 'Öppnar', en: 'Opens the bottle' },
  'clip.somm.hostTaste': { sv: 'Låter värden smaka', en: 'Lets the host taste' },
  'clip.somm.pour': { sv: 'Häller upp', en: 'Pours for the table' },
  'clip.cook.station': { sv: 'Arbetar vid stationen', en: 'Works at the station' },
  'clip.cook.plate': { sv: 'Lägger upp', en: 'Plates up' },
  'clip.cook.toPass': { sv: 'Ställer på passet', en: 'Puts it on the pass' },
  'clip.dish.receive': { sv: 'Tar emot', en: 'Takes the dishes' },
  'clip.dish.wash': { sv: 'Diskar', en: 'Washes up' },
  'clip.guest.walk': { sv: 'Kommer in och letar', en: 'Comes in and looks around' },
  'clip.guest.sit': { sv: 'Sätter sig', en: 'Sits down' },
  'clip.guest.seatedIdle': { sv: 'Sitter', en: 'Sits' },
  'clip.guest.readMenu': { sv: 'Läser menyn', en: 'Reads the menu' },
  'clip.guest.order': { sv: 'Beställer', en: 'Orders' },
  'clip.guest.eat': { sv: 'Äter', en: 'Eats' },
  'clip.guest.toast': { sv: 'Skålar', en: 'Raises a glass' },
  'clip.guest.tasteApprove': { sv: 'Smakar och nickar', en: 'Tastes and nods' },
  'clip.guest.gesture': { sv: 'Gestikulerar', en: 'Talks with their hands' },
  'clip.guest.lean': { sv: 'Lutar sig mot den andra', en: 'Leans in' },
  'clip.guest.waveStaff': { sv: 'Vinkar till sig personalen', en: 'Waves the staff over' },
  'clip.guest.riseGreet': { sv: 'Reser sig och hälsar', en: 'Stands up and greets' },
  'clip.guest.pay': { sv: 'Betalar', en: 'Pays' },
  'clip.guest.leave': { sv: 'Reser sig och går', en: 'Gets up and leaves' },
  'clip.rocket.cutHand': { sv: 'Skär sig på en flaska', en: 'Cuts a hand on a bottle' },
  'clip.rocket.holdHand': { sv: 'Håller om handen', en: 'Holds the hand' },
  'clip.rocket.smellWine': { sv: 'Luktar på vinet och ställer ned glaset', en: 'Smells the wine and puts the glass down' },
  'clip.rocket.askPointMenu': { sv: 'Frågar och pekar i menyn', en: 'Asks and points at the menu' },
  'clip.rocket.walkToKitchen': { sv: 'Går mot köket', en: 'Heads for the kitchen' },

  'interaction.order': { sv: 'Beställningen', en: 'The order' },
  'interaction.passHandoff': { sv: 'Passet', en: 'The pass' },
  'interaction.wineService': { sv: 'Vinet', en: 'The wine' },
  'interaction.toast': { sv: 'Skålen', en: 'The toast' },
  'interaction.talk': { sv: 'Samtalet', en: 'The conversation' },
  'interaction.dodge': { sv: 'Mötet i gången', en: 'Passing in the aisle' },
  'interaction.payment': { sv: 'Notan', en: 'The bill' },
  'interaction.dishHandoff': { sv: 'Disken', en: 'The dishes' },

  'service.ch.arrive': { sv: 'Gästerna kommer in', en: 'The guests arrive' },
  'service.ch.menu': { sv: 'Menyn', en: 'The menu' },
  'service.ch.order': { sv: 'Beställningen', en: 'The order' },
  'service.ch.kitchen': { sv: 'Köket lägger upp', en: 'The kitchen plates up' },
  'service.ch.wine': { sv: 'Vinet', en: 'The wine' },
  'service.ch.pass': { sv: 'Passet', en: 'The pass' },
  'service.ch.dodge': { sv: 'Mötet i gången', en: 'Passing in the aisle' },
  'service.ch.serve': { sv: 'Serveringen', en: 'Service at the table' },
  'service.ch.toast': { sv: 'Skålen', en: 'The toast' },
  'service.ch.pay': { sv: 'Notan', en: 'The bill' },
  'service.ch.leave': { sv: 'Gästerna går', en: 'The guests leave' },

  'rocket.cut': { sv: 'Bartendern skär sig på en flaska', en: 'The bartender cuts a hand on a bottle' },
  'rocket.smell': { sv: 'Värden luktar på vinet och ställer ned glaset', en: 'The host smells the wine and puts the glass down' },
  'rocket.ask': { sv: 'Gästen vid bord 4 frågar om soppan', en: 'The guest at table 4 asks about the soup' },
  'rocket.kitchen': { sv: 'En gäst går mot köket', en: 'A guest heads for the kitchen' },

  'prop.plate': { sv: 'Tallrik', en: 'Dinner plate' },
  'prop.sidePlate': { sv: 'Assiett', en: 'Side plate' },
  'prop.soupBowl': { sv: 'Djup tallrik', en: 'Soup plate' },
  'prop.wineGlass': { sv: 'Vinglas', en: 'Wine glass' },
  'prop.waterGlass': { sv: 'Vattenglas', en: 'Water glass' },
  'prop.wineBottle': { sv: 'Vinflaska', en: 'Wine bottle' },
  'prop.waterBottle': { sv: 'Vattenflaska', en: 'Water bottle' },
  'prop.carafe': { sv: 'Karaff', en: 'Carafe' },
  'prop.tray': { sv: 'Bricka', en: 'Tray' },
  'prop.fork': { sv: 'Gaffel', en: 'Fork' },
  'prop.knife': { sv: 'Kniv', en: 'Knife' },
  'prop.spoon': { sv: 'Sked', en: 'Spoon' },
  'prop.napkin': { sv: 'Servett', en: 'Napkin' },
  'prop.cake': { sv: 'Tårta med ljus', en: 'Cake with candles' },
  'prop.menu': { sv: 'Menykort', en: 'Menu' },
  'prop.pad': { sv: 'Beställningsblock', en: 'Order pad' },
  'prop.billFolder': { sv: 'Notamapp', en: 'Bill folder' },
  'prop.size': { sv: 'Mått (b × h × d)', en: 'Size (w × h × d)' },
  'prop.grip': { sv: 'Grepp', en: 'Grip' },
  'prop.metres': { sv: '{w} × {h} × {d} m', en: '{w} × {h} × {d} m' },
  'grip.flat': { sv: 'handflatan under tallrikens bakre del', en: 'palm under the back of the plate' },
  'grip.palm': { sv: 'brickan balanserad på handflatan, i axelhöjd', en: 'tray balanced on the palm at shoulder height' },
  'grip.stem': { sv: 'om foten av kupan', en: 'at the base of the bowl' },
  'grip.tumbler': { sv: 'handen runt glaset', en: 'hand around the glass' },
  'grip.body': { sv: 'handen runt flaskans kropp', en: 'hand around the body of the bottle' },
  'grip.neck': { sv: 'om halsen', en: 'by the neck' },
  'grip.handle': { sv: 'skaftet i handen, spetsen framåt', en: 'handle in the hand, tip forward' },
  'grip.pinch': { sv: 'mellan fingrarna', en: 'between the fingers' },
  'grip.book': { sv: 'lutat upp mot den som läser', en: 'tilted up towards the reader' },
  'grip.twoHands': { sv: 'med båda händer', en: 'with both hands' }
} as const;
