// foljderStrings.ts — D5 följderna och konceptet, 2026-10-04. { sv, en }, brittisk engelska. Slås in i STRINGS.
// Spelets text: status.*, staff.*, role.*, topic.*, card.*, mood.*, party.*, group.*, rocket.*, pyr.*, focus.*, shop.*, pav.*, sup.*, eq.*, ware.*, ev.*, review.*, day.*.
// hud.* och f5.* är prototypens. Platshållare i klamrar fylls ur balance.ts och kvällen.

export const D5_STRINGS: Record<string, { sv: string; en: string }> = {
  // ----- statusläget och kortet -----
  'status.button': { sv: 'Status', en: 'Status' },
  'status.on': { sv: 'Statusläge', en: 'Status view' },
  'focus.button': { sv: 'Fokus', en: 'Focus' },
  'staff.stamina': { sv: 'Ork', en: 'Energy' },
  'staff.stamina.fresh': { sv: 'Pigg', en: 'Fresh' },
  'staff.stamina.tired': { sv: 'Trött', en: 'Tired' },
  'staff.stamina.spent': { sv: 'Slut', en: 'Worn out' },
  'staff.wellbeing': { sv: 'Trivsel', en: 'Morale' },
  'staff.wellbeing.thriving': { sv: 'Trivs', en: 'Happy' },
  'staff.wellbeing.okay': { sv: 'Lagom', en: 'All right' },
  'staff.wellbeing.low': { sv: 'Trivs inte', en: 'Unhappy' },
  'staff.tips': { sv: 'Dricks i kväll', en: 'Tips tonight' },
  'staff.topics': { sv: 'Kan', en: 'Knows' },
  'staff.missing': { sv: 'Saknas', en: 'Missing' },
  'staff.hint.spent': { sv: 'Går saktare och tvekar vid borden.', en: 'Slower on the floor, hesitates at tables.' },
  'staff.hint.tired': { sv: 'Behöver en paus före stängning.', en: 'Needs a break before closing.' },
  'staff.hint.fresh': { sv: 'Klarar en rusning till.', en: 'Can take another rush.' },
  'role.host': { sv: 'Hovmästare', en: 'Maître d’' }, 'role.sommelier': { sv: 'Sommelier', en: 'Sommelier' }, 'role.bartender': { sv: 'Bartender', en: 'Bartender' },
  'role.waiter': { sv: 'Servitör', en: 'Waiter' }, 'role.cook': { sv: 'Kock', en: 'Chef' }, 'role.dj': { sv: 'DJ', en: 'DJ' },
  'topic.wine': { sv: 'Vin', en: 'Wine' }, 'topic.cheese': { sv: 'Ost', en: 'Cheese' }, 'topic.fish': { sv: 'Fisk', en: 'Fish' }, 'topic.service': { sv: 'Service', en: 'Service' },
  'topic.spirits': { sv: 'Sprit', en: 'Spirits' }, 'topic.cigar': { sv: 'Cigarr', en: 'Cigars' }, 'topic.kitchen': { sv: 'Köket', en: 'Kitchen' }, 'topic.music': { sv: 'Musik', en: 'Music' }, 'topic.charcuterie': { sv: 'Chark', en: 'Charcuterie' },
  'card.group': { sv: 'Gästerna', en: 'Guests' },
  'card.mood': { sv: 'Stämning', en: 'Mood' },
  'card.forgives': { sv: 'Förlåter', en: 'Forgives' },
  'forgives.much': { sv: 'mycket', en: 'a lot' }, 'forgives.some': { sv: 'en del', en: 'some' }, 'forgives.little': { sv: 'lite', en: 'little' },
  'card.close': { sv: 'Stäng', en: 'Close' },
  'mood.delighted': { sv: 'Glad', en: 'Delighted' }, 'mood.content': { sv: 'Nöjd', en: 'Content' }, 'mood.waiting': { sv: 'Väntar', en: 'Waiting' }, 'mood.impatient': { sv: 'Otålig', en: 'Impatient' }, 'mood.displeased': { sv: 'Missnöjd', en: 'Displeased' },
  'party.lindqvist': { sv: 'Sällskapet Lindqvist', en: 'The Lindqvist party' }, 'party.weber': { sv: 'Familjen Weber', en: 'The Weber family' },
  'party.bar': { sv: 'Vid baren', en: 'At the bar' }, 'party.nyberg': { sv: 'Nyberg och kollegan', en: 'Nyberg and a colleague' },
  'party.olsson': { sv: 'Paret Olsson', en: 'The Olssons' }, 'party.hammar': { sv: 'Paret Hammar', en: 'The Hammars' },
  'group.student': { sv: 'Studenter', en: 'Students' }, 'group.villager': { sv: 'Bybor', en: 'Villagers' }, 'group.tourist': { sv: 'Turister', en: 'Tourists' },
  'group.gourmet': { sv: 'Gourmeter', en: 'Food lovers' }, 'group.business': { sv: 'Affärsfolk', en: 'Business guests' },
  'group.sign.student': { sv: 'ryggsäcken', en: 'the rucksack' }, 'group.sign.villager': { sv: 'kepsen', en: 'the flat cap' }, 'group.sign.tourist': { sv: 'solhatten', en: 'the sun hat' },
  'group.sign.gourmet': { sv: 'sjalen', en: 'the scarf' }, 'group.sign.business': { sv: 'den vita skjortan', en: 'the white shirt' },

  // ----- raketen och pyramidens ögonblick -----
  'rocket.kicker': { sv: 'Raket · Fisken och vinet', en: 'Rocket · The fish and the wine' },
  'rocket.q': { sv: 'Gösen kommer om fem minuter. Hur ska Elin servera Chablisen?', en: 'The pike-perch is five minutes away. How should Elin serve the Chablis?' },
  'rocket.a1': { sv: 'Kyld till ungefär tio grader', en: 'Chilled to about ten degrees' },
  'rocket.a2': { sv: 'Rumstempererad, direkt från hyllan', en: 'At room temperature, straight from the shelf' },
  'rocket.a3': { sv: 'Iskall, på isbad i karaffen', en: 'Ice cold, in a decanter on ice' },
  'pyr.episteme': { sv: 'Episteme', en: 'Episteme' }, 'pyr.techne': { sv: 'Techne', en: 'Techne' }, 'pyr.phronesis': { sv: 'Phronesis', en: 'Phronesis' },
  'pyr.step': { sv: 'Steg {n} av 3', en: 'Step {n} of 3' },
  'pyr.security': { sv: 'Säkerhet', en: 'Secured' },
  'pyr.stepTerm': { sv: 'Steg', en: 'Step' },
  'pyr.outcome': { sv: 'Kvällens utfall', en: 'Tonight’s result' },
  'pyr.mult': { sv: '×{mult}', en: '×{mult}' },

  // ----- fokusläget -----
  'focus.strip.rocket': { sv: 'Raketen', en: 'Rocket' },
  'focus.on': { sv: 'Fokusläge', en: 'Focus view' },

  // ----- butiken -----
  'shop.kicker': { sv: 'Mellan kvällarna', en: 'Between evenings' },
  'shop.title': { sv: 'Butiken', en: 'The shop' },
  'shop.tab.abilities': { sv: 'Förmågor', en: 'Skills' },
  'shop.tab.suppliers': { sv: 'Leverantörer', en: 'Suppliers' },
  'shop.tab.equipment': { sv: 'Utrustning', en: 'Equipment' },
  'shop.class': { sv: 'Krogens klass', en: 'Your venue’s class' },
  'shop.class.simple': { sv: 'Enkel', en: 'Simple' }, 'shop.class.bistro': { sv: 'Bistro', en: 'Bistro' }, 'shop.class.soigne': { sv: 'Soigné', en: 'Soigné' },
  'shop.class.note': { sv: 'Det du tar in avgör klassen, gästerna och frågorna.', en: 'What you bring in sets your class, your guests and their questions.' },
  'shop.credits': { sv: '{n} krediter', en: '{n} credits' },
  'shop.medals': { sv: 'Medaljer', en: 'Medals' },
  'shop.state.owned': { sv: 'Din', en: 'Yours' }, 'shop.state.open': { sv: 'Öppen', en: 'Available' }, 'shop.state.short': { sv: 'Krediterna räcker inte', en: 'Not enough credits' }, 'shop.state.locked': { sv: 'Låst', en: 'Locked' },
  'shop.unlock': { sv: 'Öppnas med', en: 'Unlocked with' },
  'shop.unlock.medal': { sv: '{medal}-medaljen i {pav}', en: 'the {medal} medal in {pav}' },
  'shop.unlock.credits': { sv: 'och {n} krediter', en: 'and {n} credits' },
  'shop.brings': { sv: 'Tar in', en: 'Brings in' },
  'shop.opens': { sv: 'Öppnar', en: 'Opens' },
  'shop.questions': { sv: 'Nya frågor om', en: 'New questions on' },
  'shop.pulls': { sv: 'Drar mot', en: 'Pulls towards' },
  'shop.pay.till': { sv: 'Köp för {price} ur kassan', en: 'Buy for {price} from the till' },
  'shop.pay.purchases': { sv: '{price} i veckans inköp', en: '{price} in this week’s purchasing' },
  'shop.btn.unlock': { sv: 'Öppna för {n} krediter', en: 'Unlock for {n} credits' },
  'shop.btn.buy': { sv: 'Köp för {price}', en: 'Buy for {price}' },
  'shop.btn.owned': { sv: 'Står i rummet', en: 'In the room' },
  'shop.btn.ownedSup': { sv: 'Levererar från morgon', en: 'Delivers from tomorrow' },
  'shop.btn.locked': { sv: 'Låst', en: 'Locked' },
  'shop.done': { sv: 'Klar för i kväll', en: 'Ready for tonight' },
  'pav.kitchen': { sv: 'köket', en: 'the kitchen' }, 'pav.wine': { sv: 'vinet', en: 'wine' }, 'pav.service': { sv: 'servicen', en: 'service' },
  'sup.fisherman': { sv: 'Fiskaren vid sjön', en: 'The fisherman by the lake' },
  'sup.wineMerchant': { sv: 'Vinhandlaren', en: 'The wine merchant' },
  'sup.cheeseAffineur': { sv: 'Ostaffinören', en: 'The cheese affineur' },
  'sup.charcutier': { sv: 'Charkuteristen', en: 'The charcutier' },
  'eq.wineFridge': { sv: 'Vinkylen', en: 'The wine fridge' },
  'eq.flambeCart': { sv: 'Flamberingsvagnen', en: 'The flambé trolley' },
  'eq.cheeseCart': { sv: 'Ostvagnen', en: 'The cheese trolley' },
  'eq.avecCart': { sv: 'Avecvagnen', en: 'The digestif trolley' },
  'eq.humidor': { sv: 'Humidorn', en: 'The humidor' },
  'ware.pikeperch': { sv: 'gös', en: 'pike-perch' }, 'ware.whitefish': { sv: 'sik', en: 'whitefish' }, 'ware.crayfish': { sv: 'kräftor', en: 'crayfish' },
  'ware.priorat': { sv: 'Priorat', en: 'Priorat' }, 'ware.chablis': { sv: 'Chablis', en: 'Chablis' }, 'ware.barolo': { sv: 'Barolo', en: 'Barolo' },
  'ware.brie': { sv: 'Brie de Meaux', en: 'Brie de Meaux' }, 'ware.munster': { sv: 'Munster', en: 'Munster' }, 'ware.comte': { sv: 'Comté', en: 'Comté' },
  'ware.ham': { sv: 'lufttorkad skinka', en: 'air-dried ham' }, 'ware.saucisson': { sv: 'saucisson', en: 'saucisson' }, 'ware.rillettes': { sv: 'rillettes', en: 'rillettes' },
  'ev.wine.servingTemp': { sv: 'rätt temperatur på vinet', en: 'the right wine temperature' },
  'ev.tableside.flambe': { sv: 'flambering vid bordet', en: 'flambéing at the table' },
  'ev.cheese.trolley': { sv: 'ostvagnen vid borden', en: 'the cheese trolley at the tables' },
  'ev.avec.trolley': { sv: 'avec efter kaffet', en: 'a digestif after coffee' },
  'ev.table.staysForAvec': { sv: 'bord som stannar', en: 'tables that stay on' },
  'ev.cigar.offer': { sv: 'cigarren på terrassen', en: 'a cigar on the terrace' },

  // ----- recensioner i morse -----
  'review.kicker': { sv: 'Recensioner i morse', en: 'This morning’s reviews' },
  'review.title': { sv: 'Vad byn säger om i går', en: 'What the village says about last night' },
  'review.rep': { sv: 'Ryktet', en: 'Reputation' },
  'review.classLine': { sv: 'Ryktet som {cls}', en: 'Reputation as a {cls}' },
  'review.delta.down': { sv: 'Ryktet −{n}', en: 'Reputation −{n}' },
  'review.delta.up': { sv: 'Ryktet +{n}', en: 'Reputation +{n}' },
  'review.voice.gourmet': { sv: 'En gourmet', en: 'A food lover' }, 'review.voice.village': { sv: 'Byn', en: 'The village' },
  'review.voice.tourist': { sv: 'En turist', en: 'A tourist' }, 'review.voice.student': { sv: 'En student', en: 'A student' },
  'review.q.fishWine': { sv: '”Gösen var fin, men vinet tog över.”', en: '“The pike-perch was lovely, but the wine drowned it.”' },
  'review.r.fishWine': { sv: 'Två bord fick fel vin till fisken.', en: 'Two tables got the wrong wine with the fish.' },
  'review.q.birthday': { sv: '”Hela vinbaren skålade för Karin.”', en: '“The whole bar raised a glass to Karin.”' },
  'review.r.birthday': { sv: 'Födelsedagen fick grannarna med sig.', en: 'The birthday won over the next table.' },
  'review.q.slow': { sv: '”Vi väntade länge på notan.”', en: '“We waited a long time for the bill.”' },
  'review.r.slow': { sv: 'Sara var slut efter nio.', en: 'Sara was worn out after nine.' },
  'review.q.avec': { sv: '”Vi stannade på en calvados till.”', en: '“We stayed on for another calvados.”' },
  'review.r.avec': { sv: 'Ett bord stannade för avec.', en: 'One table stayed for a digestif.' },
  'review.next': { sv: 'Till inköpen', en: 'On to purchasing' },
  'day.morning': { sv: 'Onsdag morgon', en: 'Wednesday morning' },

  // ----- HUD:en (som i hovmästaren 2026-10-02; här för prototypen) -----
  'hud.service': { sv: 'Servicen', en: 'Service' },
  'hud.left': { sv: '1 h 20 min kvar', en: '1 h 20 min left' },
  'hud.till': { sv: 'Kassan', en: 'Till' },
  'hud.toGo': { sv: '{n} kvar till insatsen', en: '{n} to the stake' },
  'hud.stake': { sv: 'Insatsen {n}', en: 'Stake {n}' },
  'hud.mood': { sv: 'Stämningen', en: 'Mood' },
  'hud.rival': { sv: 'I byn i kväll', en: 'In the village tonight' },
  'hud.rank': { sv: '2:a av 7', en: '2nd of 7' },

  // ----- prototypens panel -----
  'f5.abilities': { sv: 'Förmågorna är som i butiken från 2 oktober (hostShop.ts). De nya flikarna är Leverantörer och Utrustning.', en: 'Skills are as in the shop from 2 October (hostShop.ts). The new tabs are Suppliers and Equipment.' },
  'f5.kicker': { sv: 'D5 · följderna och konceptet', en: 'D5 · consequences and concept' },
  'f5.title': { sv: 'Följderna och konceptet', en: 'Consequences and concept' },
  'f5.play': { sv: 'Spela', en: 'Play' }, 'f5.pause': { sv: 'Pausa', en: 'Pause' },
  'f5.size': { sv: 'Skärmstorlek', en: 'Screen size' },
  'f5.distance': { sv: 'Kameran', en: 'Camera' },
  'f5.overlap': { sv: 'Överlapp i layouten', en: 'Layout overlaps' },
  'f5.overlap.none': { sv: 'Inga, i båda storlekarna och lägena', en: 'None, at both sizes and in both views' },
  'f5.keys': { sv: 'Tangenter: S statusläge, H fokusläge, Esc stänger kortet. Klicka på en figur för kortet.', en: 'Keys: S status view, H focus view, Esc closes the card. Click a figure for its card.' },
  'f5.sc.status': { sv: '1 · Statusläget', en: '1 · Status view' },
  'f5.why.status': { sv: 'Stämningen över alla bord, rollringen och orkringen vid all personal, trivseln bredvid.', en: 'Mood over every table, role ring and energy ring under all staff, morale beside it.' },
  'f5.sc.card': { sv: '2 · Kortet', en: '2 · The card' },
  'f5.why.card': { sv: 'Namn, ork, trivsel, dricks och vad de kan. För gästerna: grupp, stämning och hur mycket de förlåter.', en: 'Name, energy, morale, tips and what they know. For guests: group, mood and how much they forgive.' },
  'f5.sc.pyramid': { sv: '3 · Pyramidens ögonblick', en: '3 · The pyramid moment' },
  'f5.why.pyramid': { sv: 'Rätt svar: pyramiden stort i mitten i 1,5 s, steget tänds och raden visar säkerhet × steg → utfall.', en: 'A right answer: the pyramid large in the centre for 1.5 s, the step lights and the row shows secured × step → result.' },
  'f5.sc.focus': { sv: '4 · Fokusläget', en: '4 · Focus view' },
  'f5.why.focus': { sv: 'Under 14 m eller med H fälls panelerna till lister. Klockan, kassan och mätaren står kvar.', en: 'Below 14 m or with H the panels fold into strips. Clock, till and meter stay.' },
  'f5.sc.groups': { sv: '5 · Gästgrupperna', en: '5 · Guest groups' },
  'f5.why.groups': { sv: 'Fem grupper på 14 m, ett tecken var: ryggsäck, keps, solhatt, sjal, vit skjorta.', en: 'Five groups at 14 m, one sign each: rucksack, cap, sun hat, scarf, white shirt.' },
  'f5.sc.equip': { sv: '6 · Utrustningen i rummet', en: '6 · Equipment in the room' },
  'f5.why.equip': { sv: 'Vinkyl och humidor mot väggarna, tre vagnar i västra hörnet.', en: 'Wine fridge and humidor against the walls, three trolleys in the west corner.' },
  'f5.sc.flambe': { sv: '6a · Flambering vid bordet', en: '6a · Flambéing at the table' },
  'f5.why.flambe': { sv: 'Per skjuter vagnen, häller, lågan tar sig och gästerna lutar sig fram.', en: 'Per wheels the trolley over, pours, the flame catches and the guests lean in.' },
  'f5.sc.cheese': { sv: '6b · Ostvagnen vid borden', en: '6b · The cheese trolley at the tables' },
  'f5.why.cheese': { sv: 'Elin lyfter kupan, berättar och skär vid två bord.', en: 'Elin lifts the cloche, talks the guests through it and cuts at two tables.' },
  'f5.sc.shop': { sv: '7 · Butikens nya flikar', en: '7 · New shop tabs' },
  'f5.why.shop': { sv: 'Leverantörer och utrustning, låsta och öppna, och vad som öppnar dem. Klassen överst.', en: 'Suppliers and equipment, locked and available, and what unlocks them. The class on top.' },
  'f5.sc.morning': { sv: '8 · Recensioner i morse', en: '8 · This morning’s reviews' },
  'f5.why.morning': { sv: 'Ryktet före och efter, och fyra rader om varför.', en: 'Reputation before and after, and four lines on why.' },
  'f5.statusToggle': { sv: 'Statusläge', en: 'Status view' }, 'f5.focusToggle': { sv: 'Fokusläge', en: 'Focus view' },
  'f5.on': { sv: 'På', en: 'On' }, 'f5.off': { sv: 'Av', en: 'Off' },
  'f5.view.lineup': { sv: 'Stående', en: 'Standing' }, 'f5.view.seated': { sv: 'I rummet', en: 'In the room' },
  'f5.view.all': { sv: 'Hela rummet', en: 'Whole room' }, 'f5.view.carts': { sv: 'Vagnarna', en: 'Trolleys' }, 'f5.view.cabinets': { sv: 'Skåpen', en: 'Cabinets' },
  'f5.card.who': { sv: 'Kortet för', en: 'Card for' },
  'f5.legend': { sv: 'Orken och trivseln', en: 'Energy and morale' },
  'f5.ch.push': { sv: 'Vagnen ut', en: 'Trolley out' }, 'f5.ch.round': { sv: 'Runt vagnen', en: 'Round the trolley' }, 'f5.ch.present': { sv: 'Visar rätten', en: 'Presents the dish' },
  'f5.ch.pour': { sv: 'Häller', en: 'Pours' }, 'f5.ch.flame': { sv: 'Lågan', en: 'The flame' }, 'f5.ch.show': { sv: 'Visar', en: 'Shows' }, 'f5.ch.back': { sv: 'Ut igen', en: 'Back out' },
  'f5.ch.cloche': { sv: 'Kupan lyfts', en: 'Cloche off' }, 'f5.ch.cut': { sv: 'Skär', en: 'Cuts' }, 'f5.ch.next': { sv: 'Nästa bord', en: 'Next table' }, 'f5.ch.again': { sv: 'Tvåan B', en: 'Table B' },
  'f5.ch.lock': { sv: 'Svaret låses', en: 'Answer locked' }, 'f5.ch.lift': { sv: 'Pyramiden lyfts', en: 'Pyramid lifts' }, 'f5.ch.fill': { sv: 'Steget tänds', en: 'The step lights' }, 'f5.ch.shrink': { sv: 'Tillbaka i kortet', en: 'Back in the card' },
  'f5.ch.wide': { sv: '24 m', en: '24 m' }, 'f5.ch.cross': { sv: 'Under 14 m: panelerna fälls', en: 'Below 14 m: panels fold' }, 'f5.ch.out': { sv: 'Ut igen: panelerna tillbaka', en: 'Back out: panels return' }
};
