// dinVagStrings.ts — D7: vagnen, din väg, Åsas erbjudande, ombyggnaden, fikat och nivåerna. { sv, en }, brittisk engelska.
// Inga speltal: {cash}, {rep}, {days}, {deposit}, {delta} och {n} kommer från balance.ts eller från rummets data.
export const DIN_VAG_STRINGS: Record<string, { sv: string; en: string }> = {
  // ----- prototypens ram -----
  'ui.title': { sv: 'D7 · Vagnen och vägen', en: 'D7 · The truck and the path' },
  'ui.screens': { sv: 'Skärmar', en: 'Screens' },
  'ui.size': { sv: 'Storlek', en: 'Size' },
  'ui.lang': { sv: 'Språk', en: 'Language' },
  'ui.about': { sv: 'Om skärmen', en: 'About this screen' },
  'ui.controls': { sv: 'Styr', en: 'Controls' },
  'ui.reset': { sv: 'Börja om', en: 'Start again' },
  'sc.truck': { sv: '1 · Vagnen på Torget', en: '1 · The truck on Torget' },
  'sc.clips': { sv: '2 · Klippen vid vagnen', en: '2 · Clips at the truck' },
  'sc.path': { sv: '3 · Din väg', en: '3 · Your path' },
  'sc.asa': { sv: '4 · Åsas erbjudande', en: '4 · Åsa’s offer' },
  'sc.refit': { sv: '5 · Ombyggnaden', en: '5 · The refit' },
  'sc.fika': { sv: '6 · Fikat efter stängning', en: '6 · Coffee after closing' },
  'sc.tier': { sv: '7 · Nivåerna', en: '7 · The levels' },

  // ----- vagnen -----
  'venue.truckName': { sv: 'Hyttgrillen', en: 'Hyttgrillen' },
  'venue.name': { sv: 'Hyttan', en: 'Hyttan' },
  'venue.kind.truck': { sv: 'Svensk grill', en: 'Swedish grill' },
  'truck.clip': { sv: 'Klipp', en: 'Clip' },
  'truck.clip.auto': { sv: 'Kvällen går', en: 'The evening runs' },
  'truck.clip.grill': { sv: 'Grilla', en: 'Grilling' },
  'truck.clip.serve': { sv: 'Servera vid luckan', en: 'Serving at the hatch' },
  'truck.clip.wipe': { sv: 'Torka av bänken', en: 'Wiping the counter' },
  'truck.tempo': { sv: 'Tempo', en: 'Pace' },
  'truck.tempo.calm': { sv: 'Lugn', en: 'Calm' },
  'truck.tempo.normal': { sv: 'Normal', en: 'Normal' },
  'truck.tempo.stressed': { sv: 'Stressad', en: 'Stressed' },
  'truck.cam': { sv: 'Kameran', en: 'Camera' },
  'truck.rival': { sv: 'Grillvagnen står på torget i kväll', en: 'Grillvagnen is on the square tonight' },
  'truck.compare': { sv: 'Jämför vagnarna', en: 'Compare the trucks' },
  'truck.cmp.mine': { sv: 'Din vagn', en: 'Your truck' },
  'truck.cmp.grill': { sv: 'Grillvagnen', en: 'Grillvagnen' },
  'truck.cmp.taco': { sv: 'Tacovagnen', en: 'Tacovagnen' },
  'truck.cmp.mine.a': { sv: 'Släpvagn med runda gavlar och dragstång', en: 'Trailer with rounded ends and a drawbar' },
  'truck.cmp.mine.b': { sv: 'Dalablå, hel markis i grädde med bågad kant', en: 'Dala blue, plain cream awning with a scalloped edge' },
  'truck.cmp.mine.c': { sv: 'Rök från skorstenen, ljusslinga över ståborden', en: 'Smoke from the flue, string lights over the tables' },
  'truck.cmp.van.a': { sv: 'Skåpbil med hytt, rak i plan', en: 'Box van with a cab, square in plan' },
  'truck.cmp.grill.b': { sv: 'Rödbrun, randig markis i gult', en: 'Russet, striped yellow awning' },
  'truck.cmp.taco.b': { sv: 'Grön, randig markis i grädde', en: 'Green, striped cream awning' },
  'truck.cmp.van.c': { sv: 'Ingen rök, ingen servering, man äter i kön', en: 'No smoke, no seating; people eat in the queue' },
  'truck.served': { sv: 'Serverade i kväll', en: 'Served tonight' },

  // ----- din väg -----
  'path.title': { sv: 'Din väg', en: 'Your path' },
  'path.sub': { sv: 'Från vagnen på torget till stjärnan', en: 'From the truck on the square to the star' },
  'path.step.truck': { sv: 'Food truck', en: 'Food truck' },
  'path.step.winebar': { sv: 'Vinbar', en: 'Wine bar' },
  'path.step.bistro': { sv: 'Bistro', en: 'Bistro' },
  'path.step.brewpub': { sv: 'Ölkrog', en: 'Brewpub' },
  'path.step.restaurant': { sv: 'Restaurang', en: 'Restaurant' },
  'path.step.club': { sv: 'Nattklubb', en: 'Nightclub' },
  'path.step.inn': { sv: 'Gästgiveri', en: 'Coaching inn' },
  'path.step.star': { sv: 'Stjärnkrogen', en: 'The starred restaurant' },
  'path.here': { sv: 'Du är här', en: 'You are here' },
  'path.done': { sv: 'Klart', en: 'Done' },
  'path.later': { sv: 'Kommer senare', en: 'Coming later' },
  'path.next': { sv: 'Nästa steg', en: 'Next step' },
  'path.req.cash': { sv: 'Kassa', en: 'Cash' },
  'path.req.rep': { sv: 'Rykte', en: 'Reputation' },
  'path.req.medal': { sv: 'Medalj', en: 'Medal' },
  'path.req.of': { sv: '{have} av {need}', en: '{have} of {need}' },
  'path.req.medal.v': { sv: 'Silver i Metodköket', en: 'Silver in Metodköket' },
  'path.req.medal.have': { sv: 'Du har brons', en: 'You have bronze' },
  'path.req.met': { sv: 'Klart', en: 'Met' },
  'path.req.left': { sv: 'Inte klart', en: 'Not met yet' },
  'path.offer': { sv: 'När alla tre är klara kommer Åsa förbi med ett erbjudande.', en: 'When all three are met, Åsa comes by with an offer.' },
  'path.back': { sv: 'Tillbaka', en: 'Back' },

  // ----- Åsas erbjudande -----
  'asa.kicker': { sv: 'Ett erbjudande', en: 'An offer' },
  'asa.name': { sv: 'Åsa', en: 'Åsa' },
  'asa.role': { sv: 'Äger huset vid torget', en: 'Owns the building on the square' },
  'asa.line': { sv: '”Vinbaren har gått bra hela sommaren. Vill du ta över hela huset och göra en bistro av den?”', en: '“The wine bar has done well all summer. Would you like to take over the whole building and make it a bistro?”' },
  'asa.what': { sv: 'Det här betyder det', en: 'What it means' },
  'asa.row.closed': { sv: 'Stängt i {days} dagar medan ni bygger om', en: 'Closed for {days} days while you rebuild' },
  'asa.row.deposit': { sv: 'Kontantinsats {deposit}, resten lånar du', en: 'A deposit of {deposit}, the rest is a loan' },
  'asa.row.rep': { sv: 'Ryktet börjar om till hälften, gästerna känner inte bistron än', en: 'Reputation starts again at half; guests don’t know the bistro yet' },
  'asa.row.keep': { sv: 'Personalen och allt du kan följer med', en: 'Your staff and everything you know come with you' },
  'asa.take': { sv: 'Ta över', en: 'Take over' },
  'asa.notyet': { sv: 'Inte än', en: 'Not yet' },
  'asa.reply.take': { sv: '”Då ses vi i morgon med ritningarna.”', en: '“Then I’ll see you tomorrow with the drawings.”' },
  'asa.reply.notyet': { sv: '”Erbjudandet står kvar. Säg till när du är redo.”', en: '“The offer stands. Tell me when you’re ready.”' },
  'asa.toRefit': { sv: 'Till ombyggnaden', en: 'To the refit' },

  // ----- ombyggnaden -----
  'refit.title': { sv: 'Ombyggnaden', en: 'The refit' },
  'refit.sub': { sv: 'Från vinbar till bistro', en: 'From wine bar to bistro' },
  'refit.p0': { sv: 'Vinbaren', en: 'The wine bar' },
  'refit.p1': { sv: 'Tömt', en: 'Cleared' },
  'refit.p2': { sv: 'Byggt', en: 'Built' },
  'refit.p3': { sv: 'Dukat', en: 'Laid' },
  'refit.p4': { sv: 'Tänt', en: 'Lit' },
  'refit.play': { sv: 'Spela upp', en: 'Play' },
  'refit.seats': { sv: '{n} platser', en: '{n} seats' },
  'refit.c.tables': { sv: 'Borden', en: 'Tables' },
  'refit.c.tables.v': { sv: 'Loungerna och DJ:n går ut. In kommer en bänk längs norra väggen med fem bord för två, fyra bord för fyra i mitten och två bord för två där DJ:n stod.', en: 'The lounges and the DJ go. In come a banquette along the north wall with five tables for two, four tables for four in the middle and two tables for two where the DJ stood.' },
  'refit.c.kitchen': { sv: 'Köket', en: 'Kitchen' },
  'refit.c.kitchen.v': { sv: 'Väggen mot köket öppnas till ett pass med värmelampor. Baren blir kortare och flyttar söderut, så att passet syns från salen.', en: 'The kitchen wall opens into a pass with heat lamps. The bar gets shorter and moves south, so the pass can be seen from the room.' },
  'refit.c.laying': { sv: 'Dukningen', en: 'Laying' },
  'refit.c.laying.v': { sv: 'Vitt linne under papper, tallrik, kniv och gaffel, vattenglas och en karaff på varje bord.', en: 'White linen under paper, a plate, knife and fork, water glasses and a carafe on every table.' },
  'refit.c.light': { sv: 'Belysningen', en: 'Lighting' },
  'refit.c.light.v': { sv: 'DJ:ns spotlights och ljusen på loungeborden blir en pendel över varje bord, lampetter längs bänken och vitt ljus i passet. Ljusare, lika varmt.', en: 'The DJ’s spotlights and the lounge candles become a pendant over every table, wall lights along the banquette and white light at the pass. Brighter, just as warm.' },

  // ----- fikat -----
  'fika.kicker': { sv: 'Fikat efter stängning', en: 'Coffee after closing' },
  'fika.asker': { sv: 'Sara', en: 'Sara' },
  'fika.asker.role': { sv: 'Servitör', en: 'Waiter' },
  'fika.q': { sv: 'Per har satt mig på fredag och lördag igen. Det blir tredje helgen i rad, och jag orkar inte. Vad gör vi?', en: 'Per has put me on Friday and Saturday again. That’s the third weekend running, and I can’t keep it up. What do we do?' },
  'fika.a1': { sv: 'Jag sätter mig med Per i morgon, och vi lägger om schemat med dig.', en: 'I’ll sit down with Per tomorrow, and we’ll redo the rota with you.' },
  'fika.a2': { sv: 'Ta ledigt på lördag, så tar jag själv ditt pass den kvällen.', en: 'Take Saturday off, and I’ll work your shift myself that night.' },
  'fika.a3': { sv: 'Alla får dra lite extra nu. Det lugnar sig efter Grythyttedagarna.', en: 'Everyone has to pull a bit extra now. It eases off after Grythyttedagarna.' },
  'fika.a4': { sv: 'Det är Per som gör schemat. Ta det med honom direkt i stället.', en: 'Per does the rota. Take it up with him directly instead.' },
  'fika.right': { sv: 'Rätt', en: 'Right' },
  'fika.wrong': { sv: 'Inte den här gången', en: 'Not this time' },
  'fika.held': { sv: 'Det här hade hållit', en: 'This would have held' },
  'fika.two': { sv: 'Två svar håller här', en: 'Two answers hold here' },
  'fika.why.a1': { sv: 'Sara sa som det var, och det är det svåra. Att lägga schemat tillsammans tar hennes ork på allvar utan att gå förbi Per, och det håller fler helger än den här.', en: 'Sara said how it is, and that’s the hard part. Redoing the rota together takes her tiredness seriously without going round Per, and it holds for more weekends than this one.' },
  'fika.why.a2': { sv: 'Du tar hennes ork på allvar och visar det direkt. Det håller den här helgen. Nästa vecka behöver ni ändå lägga om schemat, annars står Sara där igen.', en: 'You take her tiredness seriously and show it straight away. It holds this weekend. Next week you’ll still need to redo the rota, or Sara will be back where she was.' },
  'fika.why.a3': { sv: 'Det låter rimligt en tung vecka, men Sara har redan sagt att hon inte orkar. Den som säger det och inte blir hörd säger det inte igen. Att lägga om schemat med henne hade hållit.', en: 'It sounds fair in a busy week, but Sara has already said she can’t keep it up. Someone who says so and isn’t heard won’t say it again. Redoing the rota with her would have held.' },
  'fika.why.a4': { sv: 'Per gör schemat, men laget är ditt ansvar, och Sara frågade dig. Att sätta dig med Per och henne hade tagit hennes ork på allvar.', en: 'Per does the rota, but the team is your responsibility, and Sara asked you. Sitting down with Per and her would have taken her tiredness seriously.' },
  'fika.fx': { sv: 'Saras trivsel {delta}', en: 'Sara’s morale {delta}' },
  'fika.night': { sv: 'Godnatt', en: 'Good night' },

  // ----- nivåerna -----
  'tier.title': { sv: 'Nivån', en: 'The level' },
  'tier.sub': { sv: 'Varukorgen avgör nivån. Steget är verksamheten, nivån är priset och gästerna.', en: 'Your basket sets the level. The step is the business; the level is the prices and the guests.' },
  'tier.simple': { sv: 'Enkel', en: 'Simple' },
  'tier.mid': { sv: 'Mellan', en: 'Mid-range' },
  'tier.fine': { sv: 'Exklusiv', en: 'Exclusive' },
  'tier.sign': { sv: 'Skylten', en: 'The sign' },
  'tier.morning': { sv: 'På morgonen', en: 'In the morning' },
  'tier.morning.day': { sv: 'Tisdag morgon', en: 'Tuesday morning' },
  'tier.changed': { sv: 'Från i dag: {tier}', en: 'From today: {tier}' },
  'tier.guests.simple': { sv: 'Studenter och bybor', en: 'Students and villagers' },
  'tier.guests.mid': { sv: 'Bybor och turister', en: 'Villagers and tourists' },
  'tier.guests.fine': { sv: 'Turister, gourmeter och affärsfolk', en: 'Tourists, gourmets and business people' },
  'tier.price.simple': { sv: 'Låga priser', en: 'Low prices' },
  'tier.price.mid': { sv: 'Mellanpriser', en: 'Mid prices' },
  'tier.price.fine': { sv: 'Höga priser', en: 'High prices' },
  'review.fx.class': { sv: 'Ryktet på nivån {tier} {delta}', en: 'Reputation at the {tier} level {delta}' },
  'review.fx.venue': { sv: 'Krogens rykte {delta}', en: 'The venue’s reputation {delta}' },
  'review.sample.q': { sv: '”Gösen var perfekt, och vinet passade.”', en: '“The pike-perch was perfect, and the wine matched.”' },

  // ----- om skärmen (sidopanelen) -----
  'dv.why.truck': { sv: 'Torget på spelets karta. Vagnen står på torgytan mellan gatan Torget (w122157681) och Prästgatan, parallell med Torget. Kön går västerut under markisen, ståborden står på trädäck öster om vagnen. Grillvagnens plats på torget ligger 5,6 m bort och används samma kväll.', en: 'Torget on the game map. The truck stands on the square between the street Torget (w122157681) and Prästgatan, parallel to Torget. The queue runs west under the awning; the standing tables sit on decking east of the truck. Grillvagnen’s pitch on the square is 5.6 m away and can be used the same evening.' },
  'dv.why.clips': { sv: '12 m. Taket är kapat som i truckPitch.ts, så att besättningen syns. Tre nya klipp: truck.grill, truck.hatchServe och truck.wipeCounter. Tempot ändrar takten.', en: '12 m. The roof is cut away as in truckPitch.ts so the crew can be seen. Three new clips: truck.grill, truck.hatchServe and truck.wipeCounter. The pace changes the timing.' },
  'dv.why.path': { sv: 'Åtta steg på en lina, samma form som ställningen mot rivalerna. Klara steg i guld, nästa steg med kraven, låsta steg med Kommer senare. Kraven fylls i från balance.ts.', en: 'Eight steps on a line, the same form as the standings against the rivals. Steps done in gold, the next step with its requirements, locked steps marked Coming later. The requirements come from balance.ts.' },
  'dv.why.asa': { sv: 'Kameran går in till 10 m vid dörren efter stängning. Åsa står på trottoaren med nycklarna. Inte än kostar ingenting och erbjudandet står kvar.', en: 'The camera moves in to 10 m at the door after closing. Åsa stands on the pavement with the keys. Not yet costs nothing, and the offer stands.' },
  'dv.why.refit': { sv: 'Rummet i sin egen ram, 15,6 × 11,8 m, dörren i öster. Fyra steg: tömma, bygga, duka och tända. Varje steg är ett tillstånd i bistroRefit.ts.', en: 'The room in its own frame, 15.6 × 11.8 m, door to the east. Four steps: clear, build, lay and light. Each step is a state in bistroRefit.ts.' },
  'dv.why.fika': { sv: 'Rummet efter stängning: stolarna uppe, en pendel tänd över laget. Den som frågar lyfter handen och får ljuset. Två försvarbara svar, båda gröna.', en: 'The room after closing: chairs up, one pendant lit over the team. The one asking raises a hand and gets the light. Two defensible answers, both green.' },
  'dv.why.tier': { sv: 'Nivån visas med knappar på skylten och i morgonens rad. Skylten byter material med nivån. Nyckeln review.fx.class får ordet nivå.', en: 'The level shows as studs on the sign and in the morning line. The sign changes material with the level. The key review.fx.class gains the word level.' }
};
