// Nycklar för den varma formen (provspel 3, 2026-09-29). Slås in i STRINGS i nexusStrings.ts.
// Namnrymderna brief.*, buy.*, rocketCard.*, step.*, conf.*, meter.*, lesson.*, paper.*, evening.* och hud.* är nya.
// money.* är oförändrade mot leveransen 2026-09-28-kassan. Engelskan är brittisk, som i tidigare leveranser.
// Siffror och klockslag formateras i koden: sv "6 870", "21.34" · en "6,870", "21:34".

export const STRINGS_VARM = {
  'hud.day': { sv: "Lördag", en: "Saturday" },
  'hud.week': { sv: "Vecka 1 av 8", en: "Week 1 of 8" },
  'hud.cash': { sv: "Kassa", en: "Cash" },
  'hud.morning': { sv: "Morgon", en: "Morning" },
  'hud.opens': { sv: "Premiär 18.00", en: "Opening night 18:00" },
  'hud.service': { sv: "Servicen", en: "Service" },
  'hud.left': { sv: "3 h 18 min kvar", en: "3 h 18 min left" },
  'hud.phase.brief': { sv: "Morgonen", en: "Morning" },
  'hud.phase.buy': { sv: "Inköpen", en: "Purchasing" },
  'hud.phase.premiere': { sv: "Premiären", en: "Opening night" },
  'hud.rocketOf': { sv: "Raket {n} av {m}", en: "Rocket {n} of {m}" },
  'hud.afterClose': { sv: "Efter stängning · {time}", en: "After closing · {time}" },
  'money.kr': { sv: "{n} kr", en: "SEK {n}" },
  'money.plus': { sv: "+{n} kr", en: "+SEK {n}" },
  'money.minus': { sv: "−{n} kr", en: "−SEK {n}" },
  'brief.mentor.name': { sv: "Ingrid Malm", en: "Ingrid Malm" },
  'brief.mentor.role': { sv: "Din mentor · krögare i trettio år", en: "Your mentor · thirty years a restaurateur" },
  'brief.greet.title': { sv: "God morgon. I kväll är det premiär.", en: "Good morning. Tonight is opening night." },
  'brief.greet.body': { sv: "Sextiofyra har bokat. Två bord är studenter från Måltidens hus, och Lova Berg kommer. Hon tar med sig halva byn om hon trivs. Köp så att det räcker, men inte mer.", en: "Sixty-four have booked. Two tables are students from Måltidens hus, and Lova Berg is coming. She brings half the village if she likes it. Buy enough, but no more." },
  'brief.greet.aside': { sv: "Hotellet ringde också. De har en ovanlig gäst i helgen.", en: "The hotel rang as well. They have an unusual guest this weekend." },
  'brief.toBuy': { sv: "Till inköpen", en: "To purchasing" },
  'brief.askLova': { sv: "Fråga om Lova", en: "Ask about Lova" },
  'brief.schedule.kicker': { sv: "Körschemat", en: "Run sheet" },
  'brief.schedule.title': { sv: "Dagen fram till premiären", en: "The day until opening night" },
  'brief.schedule.1.what': { sv: "Inköpen", en: "Purchasing" },
  'brief.schedule.1.sub': { sv: "Meny, vin och mängder för 64 gäster", en: "Menu, wine and quantities for 64 guests" },
  'brief.schedule.2.what': { sv: "Övningen i Måltidens hus", en: "Practice at Måltidens hus" },
  'brief.schedule.2.sub': { sv: "Tre frågor och krediter att stå för", en: "Three questions and credits to back" },
  'brief.schedule.3.what': { sv: "Regin", en: "Direction" },
  'brief.schedule.3.sub': { sv: "Du placerar personalen och sätter tempot", en: "You place the staff and set the tempo" },
  'brief.schedule.4.what': { sv: "Premiär", en: "Opening night" },
  'brief.schedule.4.sub': { sv: "Dörrarna öppnar. Rummet spelar själv.", en: "The doors open. The room plays itself." },
  'brief.schedule.5.what': { sv: "Stängt", en: "Closed" },
  'brief.schedule.5.sub': { sv: "Sopbilen och kvällens lärdom", en: "The bin lorry and the evening’s lesson" },
  'brief.book.kicker': { sv: "Bokningsboken", en: "Reservation book" },
  'brief.book.title': { sv: "Lördag kväll", en: "Saturday night" },
  'brief.book.1.who': { sv: "Studenter från Måltidens hus", en: "Students from Måltidens hus" },
  'brief.book.1.note': { sv: "Två bord · delar gärna förrätter", en: "Two tables · like to share starters" },
  'brief.book.2.who': { sv: "Par och familjer från byn", en: "Couples and families from the village" },
  'brief.book.2.note': { sv: "Nio bord · två barnstolar", en: "Nine tables · two high chairs" },
  'brief.book.3.who': { sv: "Bilar från Örebro och Karlstad", en: "Cars from Örebro and Karlstad" },
  'brief.book.3.note': { sv: "Fem bord · frågar efter vinlistan", en: "Five tables · ask for the wine list" },
  'brief.book.4.who': { sv: "Lova Berg och vänner", en: "Lova Berg and friends" },
  'brief.book.4.note': { sv: "Bord 9 · hälsar på alla", en: "Table 9 · greets everyone" },
  'brief.book.5.who': { sv: "Långbordet", en: "The long table" },
  'brief.book.5.note': { sv: "Bord 13 · en nötallergi", en: "Table 13 · one nut allergy" },
  'brief.book.6.who': { sv: "Utan bokning", en: "Walk-ins" },
  'brief.book.6.note': { sv: "Brukar komma efter 20.30", en: "Usually after 20:30" },
  'brief.book.stars': { sv: "Två stjärnor i söndagens tidning. Fler stjärnor ger fler bilar utifrån.", en: "Two stars in Sunday’s paper. More stars bring more cars from out of town." },
  'buy.kicker': { sv: "Kvällens meny", en: "Tonight’s menu" },
  'buy.title': { sv: "Vad köket ska ha i kväll", en: "What the kitchen needs tonight" },
  'buy.hint': { sv: "Plus köper fem portioner eller två flaskor", en: "Plus buys five portions or two bottles" },
  'buy.kitchen': { sv: "Köket", en: "Kitchen" },
  'buy.cellar': { sv: "Källaren och baren", en: "Cellar and bar" },
  'buy.item.skagen': { sv: "Toast Skagen", en: "Toast Skagen" },
  'buy.item.roding': { sv: "Röding, brynt smör", en: "Arctic char, brown butter" },
  'buy.item.oxfile': { sv: "Oxfilé, rödvinssky", en: "Beef fillet, red wine jus" },
  'buy.item.chevre': { sv: "Chèvre, honung", en: "Chèvre, honey" },
  'buy.item.brulee': { sv: "Crème brûlée", en: "Crème brûlée" },
  'buy.item.cremant': { sv: "Crémant de Loire", en: "Crémant de Loire" },
  'buy.item.chablis': { sv: "Chablis 2022", en: "Chablis 2022" },
  'buy.item.barolo': { sv: "Barolo 2018", en: "Barolo 2018" },
  'buy.item.cider': { sv: "Alkoholfri cider", en: "Alcohol-free cider" },
  'buy.dish.sub': { sv: "Inköp {c} · säljs för {p}", en: "Cost {c} · sells for {p}" },
  'buy.wine.sub': { sv: "Inköp {c} per flaska · fem glas à {p}", en: "Cost {c} per bottle · five glasses at {p}" },
  'buy.fewer': { sv: "Färre", en: "Fewer" },
  'buy.more': { sv: "Fler", en: "More" },
  'buy.delivery': { sv: "Leveransen i dag", en: "Today’s delivery" },
  'buy.mains': { sv: "Varmrätter", en: "Mains" },
  'buy.mains.of': { sv: "{n} av {m}", en: "{n} of {m}" },
  'buy.mains.short': { sv: "{n} gäster får ingen varmrätt. Köp fler röding eller oxfilé.", en: "{n} guests get no main. Buy more char or beef." },
  'buy.mains.ok': { sv: "Varmrätterna räcker till alla som har bokat.", en: "There is a main for everyone who has booked." },
  'buy.wine': { sv: "Vin", en: "Wine" },
  'buy.wine.line': { sv: "{g} glas · {pp} per gäst", en: "{g} glasses · {pp} per guest" },
  'buy.potential': { sv: "Om allt säljs", en: "If everything sells" },
  'buy.potential.in': { sv: "{n} in", en: "{n} in" },
  'buy.potential.note': { sv: "Det som blir över hämtas av sopbilen efter stängning.", en: "Whatever is left goes with the bin lorry after closing." },
  'buy.toPractice': { sv: "Till övningen i Måltidens hus", en: "To practice at Måltidens hus" },
  'rocketCard.role': { sv: "Sommeliern · lounge A", en: "Sommelier · lounge A" },
  'rocketCard.title': { sv: "Det korkade vinet", en: "The corked wine" },
  'rocketCard.stepOf': { sv: "Steg {n} av 3", en: "Step {n} of 3" },
  'rocketCard.moment': { sv: "Värden i lounge A luktar på vinet, ställer ner glaset och vinkar till sig sommeliern. ”Det här är korkat.”", en: "The host in lounge A smells the wine, puts the glass down and waves the sommelier over. “This is corked.”" },
  'rocketCard.caption': { sv: "Värden luktar på vinet och ställer ner glaset", en: "The host smells the wine and puts the glass down" },
  'step.episteme': { sv: "Episteme", en: "Episteme" },
  'step.episteme.sub': { sv: "Vad", en: "What" },
  'step.techne': { sv: "Techne", en: "Techne" },
  'step.techne.sub': { sv: "Hur", en: "How" },
  'step.phronesis': { sv: "Phronesis", en: "Phronesis" },
  'step.phronesis.sub': { sv: "När och varför", en: "When and why" },
  'rocketCard.q': { sv: "Hur tar du hand om det vid bordet?", en: "How do you deal with it at the table?" },
  'rocketCard.a1': { sv: "Dekanterar, så att vinet får luft", en: "Decants it so the wine can breathe" },
  'rocketCard.a2': { sv: "Luktar själv, bekräftar och byter flaskan", en: "Smells it yourself, confirms and replaces the bottle" },
  'rocketCard.a3': { sv: "Ber värden smaka igen om en stund", en: "Asks the host to taste again in a while" },
  'rocketCard.a4': { sv: "Häller ett nytt glas ur samma flaska", en: "Pours a new glass from the same bottle" },
  'rocketCard.yourAnswer': { sv: "Ditt svar", en: "Your answer" },
  'rocketCard.back': { sv: "Stå för ditt svar", en: "Back your answer" },
  'conf.guess': { sv: "Gissar", en: "Guessing" },
  'conf.think': { sv: "Tror det", en: "Think so" },
  'conf.know': { sv: "Vet det", en: "Know it" },
  'conf.guess.odds': { sv: "+30 om rätt · ±0 om fel", en: "+30 if right · ±0 if wrong" },
  'conf.think.odds': { sv: "+60 · −40", en: "+60 · −40" },
  'conf.know.odds': { sv: "+90 · −120", en: "+90 · −120" },
  'meter.cash': { sv: "Kassan", en: "Cash" },
  'meter.guests': { sv: "Gästerna", en: "Guests" },
  'meter.staff': { sv: "Personalen", en: "Staff" },
  'rocketCard.timer': { sv: "Ljuset brinner ned på 20 sekunder. Rummet väntar inte.", en: "The candle burns down in 20 seconds. The room won’t wait." },
  'lesson.grid.kicker': { sv: "Kvällens raketer", en: "Tonight’s rockets" },
  'lesson.grid.title': { sv: "Nio av tolv steg klarade", en: "Nine of twelve steps cleared" },
  'lesson.col.what': { sv: "Vad", en: "What" },
  'lesson.col.how': { sv: "Hur", en: "How" },
  'lesson.col.why': { sv: "Varför", en: "Why" },
  'lesson.rocket.1': { sv: "Det korkade vinet", en: "The corked wine" },
  'lesson.rocket.1.who': { sv: "Sommeliern · lounge A", en: "Sommelier · lounge A" },
  'lesson.rocket.2': { sv: "Gästen vid passet", en: "The guest at the pass" },
  'lesson.rocket.2.who': { sv: "Kocken · passet", en: "Chef · the pass" },
  'lesson.rocket.3': { sv: "Födelsedagen", en: "The birthday" },
  'lesson.rocket.3.who': { sv: "Hovmästaren · bord 13", en: "Maître d’ · table 13" },
  'lesson.rocket.4': { sv: "Gästen som vinglar", en: "The unsteady guest" },
  'lesson.rocket.4.who': { sv: "Bartendern · baren", en: "Bartender · the bar" },
  'lesson.calib.kicker': { sv: "Hur säker du var", en: "How sure you were" },
  'lesson.calib.of': { sv: "{a} av {b} rätt", en: "{a} of {b} right" },
  'lesson.calib.note': { sv: "Vet det höll i två av tre. Där tror du dig kunna lite mer än du kan.", en: "Know it held two times in three. There you think you know a little more than you do." },
  'lesson.kicker': { sv: "Lärdomen · Födelsedagen · Techne", en: "The lesson · The birthday · Techne" },
  'lesson.when': { sv: "Kl. 21.34 vid bord 13", en: "21:34 at table 13" },
  'lesson.principle': { sv: "Öppen låga i en full matsal kräver en fri väg och ett lugnt tempo.", en: "An open flame in a full dining room needs a clear path and a calm pace." },
  'lesson.story': { sv: "Sara sprang med tårtan för att ljusen inte skulle hinna brinna ned. Hon fick svänga runt en stol vid bord 12, och ett ljus föll på duken. Hovmästaren tog över.", en: "Sara ran with the cake so the candles wouldn’t burn down. She had to swerve round a chair at table 12, and a candle fell on the cloth. The maître d’ took over." },
  'lesson.yours': { sv: "Ditt svar", en: "Your answer" },
  'lesson.yours.text': { sv: "Springer, så att ljusen inte brinner ned", en: "Runs, so the candles don’t burn down" },
  'lesson.held': { sv: "Det som hade hållit", en: "What would have held" },
  'lesson.held.text': { sv: "Tänder ljusen vid passet, håller brickan lågt och går sakta i den fria gången", en: "Lights the candles at the pass, holds the tray low and walks slowly down the clear aisle" },
  'lesson.quote': { sv: "”Tårtan kommer fram även om ljusen är korta. Det gör inte en brand.”", en: "“The cake gets there even if the candles are short. A fire doesn’t.”" },
  'lesson.practice': { sv: "Öva det i morgon", en: "Practise it tomorrow" },
  'paper.date': { sv: "Söndag 5 juli", en: "Sunday 5 July" },
  'paper.season': { sv: "Säsongens vecka 2 av 8", en: "Week 2 of 8 of the season" },
  'paper.price': { sv: "Pris 25 kr", en: "Price SEK 25" },
  'paper.masthead': { sv: "Grythyttebladet", en: "Grythyttebladet" },
  'paper.review.kicker': { sv: "Recensionen · Vår krog", en: "The review · Our restaurant" },
  'paper.review.head': { sv: "Röding som får Storgatan att stanna", en: "The char that stops Storgatan in its tracks" },
  'paper.review.up': { sv: "Upp från två", en: "Up from two" },
  'paper.review.caption': { sv: "Lördagens premiär. Sextiofyra gäster och ett långbord som sjöng.", en: "Saturday’s opening night. Sixty-four guests and a long table that sang." },
  'paper.review.body': { sv: "Jag frågade om jag fick se köket. Svaret var ett vänligt nej mitt i rusningen, en smakbit på en sked och en rundtur efter servicen. Det säger mer om ett kök än någon meny.", en: "I asked if I could see the kitchen. The answer was a friendly no in the middle of the rush, a taste on a spoon and a tour after service. That says more about a kitchen than any menu." },
  'paper.village.kicker': { sv: "Byn i veckan", en: "The village this week" },
  'paper.village.title': { sv: "Så står krogarna", en: "Where the restaurants stand" },
  'paper.rest.1': { sv: "Hotellets matsal", en: "The hotel dining room" },
  'paper.rest.1.note': { sv: "Mannen i guld åt här", en: "The man in gold ate here" },
  'paper.rest.2': { sv: "Vår krog", en: "Our restaurant" },
  'paper.rest.2.note': { sv: "Upp en stjärna", en: "Up one star" },
  'paper.rest.3': { sv: "Torgkrogen", en: "Torgkrogen" },
  'paper.rest.3.note': { sv: "Fullt varje lunch", en: "Full every lunchtime" },
  'paper.rest.4': { sv: "Sjöboden", en: "Sjöboden" },
  'paper.rest.4.note': { sv: "Tom när det regnar", en: "Empty when it rains" },
  'paper.rest.5': { sv: "Pizzeria Grytan", en: "Pizzeria Grytan" },
  'paper.rest.5.note': { sv: "Studenternas", en: "The students’ favourite" },
  'paper.bank.kicker': { sv: "Banken säger", en: "The bank says" },
  'paper.bank.quote': { sv: "”Svinnet åt upp en tredjedel av vinsten. Köp för lördagen, inte för en dröm.”", en: "“Waste ate a third of the profit. Buy for Saturday, not for a dream.”" },
  'paper.bank.who': { sv: "Sparbanken Grythyttan", en: "Sparbanken Grythyttan" },
  'paper.seen.kicker': { sv: "Sett på stan", en: "Seen in town" },
  'paper.seen.title': { sv: "Mannen i guld gick längs sjön", en: "The man in gold walked by the lake" },
  'paper.seen.body': { sv: "Hela Sjövägen stannade i lördags när en hotellgäst i guld tog en promenad runt sjön. Han åt på Hotellets matsal.", en: "All of Sjövägen stopped on Saturday when a hotel guest in gold took a walk round the lake. He ate at the hotel dining room." },
  'paper.next.kicker': { sv: "Nästa högtid", en: "Next festival" },
  'paper.next.title': { sv: "Grythyttedagarna", en: "Grythyttedagarna" },
  'paper.next.body': { sv: "Vecka 3. Dubbelt så många gäster på gatorna.", en: "Week 3. Twice as many guests on the streets." },
  'evening.kicker': { sv: "Kvällens resultat", en: "Tonight’s result" },
  'evening.title': { sv: "Så gick premiären", en: "How opening night went" },
  'evening.stream': { sv: "Kvällen, i den ordning det hände", en: "The evening, in the order it happened" },
  'evening.gains': { sv: "Det kvällen gav", en: "What the evening gave" },
  'evening.event.1': { sv: "Det korkade vinet", en: "The corked wine" },
  'evening.event.1.line': { sv: "Elin bytte flaskan och bjöd på ett glas. Tre av tre steg.", en: "Elin replaced the bottle and offered a glass on the house. Three of three steps." },
  'evening.event.2': { sv: "Gästen vid passet", en: "The guest at the pass" },
  'evening.event.2.line': { sv: "Matskribenten fick en smakbit nu och en rundtur efter servicen.", en: "The food writer got a taste now and a tour after service." },
  'evening.event.3': { sv: "Gästen som vinglar", en: "The unsteady guest" },
  'evening.event.3.line': { sv: "Nekad i tid och fick vatten. Vännerna ville beställa åt honom.", en: "Refused in time and given water. His friends wanted to order for him." },
  'evening.event.4': { sv: "Födelsedagen", en: "The birthday" },
  'evening.event.4.line': { sv: "Tårtan kom ut för fort och ett ljus föll. Per tog över.", en: "The cake came out too fast and a candle fell. Per took over." },
  'evening.event.5': { sv: "Tillsynen", en: "The inspection" },
  'evening.event.5.line': { sv: "Tillståndet, egenkontrollen och anteckningen fanns på plats.", en: "The licence, the self-monitoring plan and the note were all in place." },
  'evening.event.6': { sv: "Sopbilen", en: "The bin lorry" },
  'evening.event.6.line': { sv: "Sju kilo mat blev över, mest röding.", en: "Seven kilos of food were left over, mostly char." },
  'evening.gain.money': { sv: "Pengar", en: "Money" },
  'evening.gain.money.cause': { sv: "Intäkter minus inköp och avgifter", en: "Takings minus purchases and fees" },
  'evening.gain.credits': { sv: "Krediter", en: "Credits" },
  'evening.gain.credits.cause': { sv: "Två raketer du stod för", en: "Two rockets you backed" },
  'evening.gain.reputation': { sv: "Rykte", en: "Reputation" },
  'evening.gain.reputation.cause': { sv: "Matskribenten och Lovas vänner", en: "The food writer and Lova’s friends" },
  'evening.gain.knowledge': { sv: "Kunskap", en: "Knowledge" },
  'evening.gain.knowledge.cause': { sv: "Nio av tolv steg", en: "Nine of twelve steps" },
  'evening.gain.experience': { sv: "Erfarenhet", en: "Experience" },
  'evening.gain.experience.cause': { sv: "Sara lärde sig bära ljus", en: "Sara learned to carry candles" },
  'evening.gain.eco': { sv: "Ekologisk hållbarhet", en: "Ecological sustainability" },
  'evening.gain.eco.cause': { sv: "Svinnet drog ned", en: "Waste pulled it down" },
  'evening.gain.econ': { sv: "Ekonomisk hållbarhet", en: "Economic sustainability" },
  'evening.gain.econ.cause': { sv: "Marginalen höll", en: "The margin held" },
  'evening.gain.social': { sv: "Social hållbarhet", en: "Social sustainability" },
  'evening.gain.social.cause': { sv: "Karin fick sin vers och grannbordet sitt glas", en: "Karin got her song and the next table its glass" },
  'evening.gain.waste': { sv: "Svinn", en: "Waste" },
  'evening.gain.waste.cause': { sv: "Mest röding", en: "Mostly char" },
  'evening.of10': { sv: "{n} av 10", en: "{n} of 10" },
  'evening.next': { sv: "Till söndagstidningen", en: "To the Sunday paper" },
  'unit.kg': { sv: "{n} kg", en: "{n} kg" },
  'unit.steps': { sv: "{n}/{m}", en: "{n}/{m}" },
  'proto.lang': { sv: "Språk", en: "Language" },
} as const;

export type StringKeyVarm = keyof typeof STRINGS_VARM;
