// d8Strings.ts — D8, order 306b. { sv, en }, brittisk engelska. Slås in i STRINGS. ui.*, sc.*, st.* och why.order/cost/room/icons är prototypens ram. Inga speltal: {cost} och {n} kommer från balance.ts.
export const D8_STRINGS: Record<string, { sv: string; en: string }> = {
  'ui.title': { sv: 'D8 · Situationerna i vinbaren', en: 'D8 · Situations in the wine bar' },
  'ui.screens': { sv: 'Skärmar', en: 'Screens' },
  'ui.size': { sv: 'Storlek', en: 'Size' },
  'ui.lang': { sv: 'Språk', en: 'Language' },
  'ui.state': { sv: 'Läge', en: 'State' },
  'ui.about': { sv: 'Om skärmen', en: 'About this screen' },
  'ui.reset': { sv: 'Börja om', en: 'Start again' },
  'sc.order': { sv: "1 · Ordningskorten", en: "1 · The order cards" },
  'sc.cost': { sv: "2 · Kostnaden på svaret", en: "2 · The cost on an answer" },
  'sc.room': { sv: "3 · Karaffen i rummet", en: "3 · The decanter in the room" },
  'sc.icons': { sv: 'Ikonerna', en: 'The icons' },
  'st.empty': { sv: 'Tom rad', en: 'Empty row' }, 'st.two': { sv: 'Två lagda', en: 'Two placed' }, 'st.full': { sv: 'Fyra lagda', en: 'Four placed' }, 'st.locked': { sv: 'Låst', en: 'Locked' },
  'st.right': { sv: 'Helt grepp', en: 'Full grip' }, 'st.halfExp': { sv: 'Halvt: upplevelsen', en: 'Half: the experience' }, 'st.halfAna': { sv: 'Halvt: analysen', en: 'Half: the analysis' }, 'st.wrong': { sv: 'Fel', en: 'Wrong' }, 'st.timeout': { sv: 'Tiden ute', en: 'Time up' },
  'st.coin': { sv: 'Mynt', en: 'Coin' }, 'st.short': { sv: 'Kassan räcker inte', en: 'Not enough in the till' },
  'st.present': { sv: 'Elin visar flaskan', en: 'Elin shows the bottle' }, 'st.decant': { sv: 'Över ljuset', en: 'Over the candle' }, 'st.cleared': { sv: 'Klarad', en: 'Cleared' }, 'st.wide': { sv: 'Klarad på 14 m', en: 'Cleared at 14 m' },

  // ----- HUD -----
  'hud.service': { sv: 'Servicen', en: 'Service' },
  'hud.left': { sv: '1 h 20 min kvar', en: '1 h 20 min left' },
  'hud.till': { sv: 'Kassan', en: 'The till' },

  // ----- raketkortet -----
  'pyr.episteme': { sv: 'Episteme', en: 'Episteme' }, 'pyr.techne': { sv: 'Techne', en: 'Techne' }, 'pyr.phronesis': { sv: 'Phronesis', en: 'Phronesis' },
  'pyr.step': { sv: 'Steg {n} av 3', en: 'Step {n} of 3' },
  'lock.locked': { sv: 'Låst', en: 'Locked' },
  'lock.answer': { sv: 'Lås svaret', en: 'Lock the answer' },
  'verdict.right': { sv: 'Rätt', en: 'Right' },
  'verdict.wrong': { sv: 'Inte den här gången', en: 'Not this time' },
  'held': { sv: 'Det här hade hållit', en: 'This would have held' },

  // ----- 1. ordningskorten (steg 2, techne) -----
  'order.moment': { sv: "Loungen har beställt en äldre Barolo, och Elin ska karaffera den vid bordet.", en: "The lounge has ordered an older Barolo, and Elin is to decant it at the table." },
  'order.q': { sv: 'Lägg Elins fyra handgrepp i rätt ordning.', en: "Put Elin's four moves in the right order." },
  'order.slots': { sv: 'Din ordning', en: 'Your order' },
  'order.cards': { sv: 'Handgreppen', en: 'The moves' },
  'order.hint': { sv: 'Klicka på ett kort för att lägga det på nästa plats. Klicka på en plats för att ta bort kortet.', en: 'Click a card to put it in the next place. Click a place to take the card away.' },
  'order.need': { sv: 'Lägg {n} kort till', en: 'Place {n} more' },
  'order.lock': { sv: 'Lås ordningen', en: 'Lock the order' },
  'card.show': { sv: 'Visa flaskan vid bordet', en: 'Show the bottle at the table' },
  'card.candle': { sv: 'Tänd ett ljus under flaskhalsen', en: 'Light a candle under the neck' },
  'card.pour': { sv: 'Häll försiktigt, stanna när satsen når halsen', en: 'Pour slowly, stop when the sediment reaches the neck' },
  'card.serve': { sv: 'Servera och ställ den tomma flaskan på bordet', en: 'Serve and stand the empty bottle on the table' },
  'card.hour': { sv: 'Låt karaffen stå en timme', en: 'Let the decanter stand for an hour' },
  'card.bar': { sv: 'Gör det vid baren', en: 'Do it at the bar' },
  'order.why.right': { sv: 'Gästerna ser flaskan först. Ljuset under halsen visar satsen, så att Elin vet när hon ska sluta hälla, och den tomma flaskan på bordet visar vad de dricker.', en: 'The guests see the bottle first. The candle under the neck shows the sediment, so Elin knows when to stop pouring, and the empty bottle on the table shows what they are drinking.' },

  // ----- 2–3. steg 3 (phronesis): halvt grepp och kostnaden -----
  'p3.moment': { sv: 'Karaffen står på bordet. Gästerna vill dricka nu, men vinet behöver en kvart till.', en: 'The decanter is on the table. The guests want to drink now, but the wine needs another quarter of an hour.' },
  'p3.q': { sv: 'Vad gör Elin?', en: 'What does Elin do?' },
  'p3.a1': { sv: 'Häller upp direkt, eftersom gästerna vill ha vinet nu.', en: 'Pours straight away, since the guests want the wine now.' },
  'p3.a2': { sv: 'Låter vinet andas en kvart och berättar varför.', en: 'Lets the wine breathe a quarter of an hour and says why.' },
  'p3.a3': { sv: 'Låter vinet andas och bjuder på ett glas cava under tiden.', en: 'Lets the wine breathe and offers a glass of cava meanwhile.' },
  'p3.a4': { sv: 'Byter till ett yngre vin som går att dricka direkt.', en: 'Swaps to a younger wine that can be drunk straight away.' },
  'p3.why1': { sv: 'Gästerna fick vinet när de ville, och kvällen gick vidare. Men vinet var inte klart, så det smakade mindre än det kostade.', en: 'The guests got the wine when they wanted it, and the evening moved on. But the wine was not ready, so it tasted of less than it cost.' },
  'p3.why2': { sv: 'Rätt om vinet: det behövde en kvart. Men gästerna satt med tomma glas medan de väntade.', en: 'Right about the wine: it needed a quarter of an hour. But the guests sat with empty glasses while they waited.' },
  'p3.why3': { sv: 'Vinet fick sin kvart, och gästerna hade något i glaset under tiden. Cavan kostar, men den ger båda greppen på en gång.', en: 'The wine got its quarter of an hour, and the guests had something in the glass meanwhile. The cava costs, but it gives both grips at once.' },
  'p3.why4': { sv: 'Barolon är redan karafferad, och gästerna valde den. Att byta kostar flaskan och säger att deras val var fel.', en: 'The Barolo is already decanted, and the guests chose it. Swapping costs the bottle and tells them their choice was wrong.' },
  'grip.half.analysis': { sv: 'Halvt grepp: analysen höll', en: 'Half grip: the analysis held' },
  'grip.half.experience': { sv: 'Halvt grepp: upplevelsen höll', en: 'Half grip: the experience held' },
  'grip.full': { sv: 'Helt grepp', en: 'Full grip' },

  // ----- 4. karaffen i rummet -----
  'room.present': { sv: 'Elin visar flaskan vid loungen', en: 'Elin shows the bottle at the lounge' },
  'room.decant': { sv: "Karafferingen över ljuset", en: "Decanting over the candle" },
  'room.cleared': { sv: 'Klarad: den tomma flaskan står bredvid', en: 'Cleared: the empty bottle stands beside it' },
  'room.wide': { sv: 'Klarad, på spelets avstånd', en: 'Cleared, at game distance' },
  'cam': { sv: 'kamera {m} m', en: 'camera {m} m' },

  // ----- ikonerna -----
  'icons.title': { sv: 'Handgreppens ikoner', en: 'Icons for the moves' },
  'icons.sub': { sv: '24 × 24, linje 1,6 i bläck och lågan i mässing. Fällorna är ritade på samma sätt som de rätta korten, så att ikonen inte avslöjar svaret.', en: '24 × 24, 1.6 stroke in ink with the flame in brass. The traps are drawn the same way as the right cards, so the icon does not give the answer away.' },
  'icons.right': { sv: 'Plats {n}', en: 'Place {n}' },
  'icons.trap': { sv: 'Fälla', en: 'Trap' },

  // ----- om skärmarna -----
  'why.order': { sv: "Steg 3 i Karaffen (vb40, techne). Stegen är analys (episteme), upplevelse (phronesis) och handling (techne). Det finns sex handgrepp och fyra platser. Klick på ett kort lägger det på nästa lediga plats, och klick på en plats tar bort kortet. Låset och tidsbågen är desamma som för ett vanligt svar. Raden bedöms enligt 306b: helt grepp är a→b→c→d. Halvt grepp mot analysen ges om f är med eller a saknas, och mot upplevelsen om e är med, c saknas eller c kommer före b. Fel blir det om b saknas, om d kommer först, eller om båda halvorna brister (c saknas och f är med). Halvt grepp får mässingsetiketten och är aldrig rött. Går tiden ut med färre än fyra kort tar Elin över (order 314). Prototypens tidsbåge är 20 s.", en: "Step 3 of The decanter (vb40, techne). The steps are analysis (episteme), experience (phronesis) and action (techne). There are six moves and four places. Click a card to put it in the next free place, and click a place to remove the card. The lock and the time arc are the same as for an ordinary answer. The row is judged as in 306b: a full grip is a→b→c→d. A half grip towards the analysis is given if f is in or a is missing, and towards the experience if e is in, c is missing or c comes before b. It is wrong if b is missing, if d comes first, or if both halves fail (c missing and f in). A half grip gets the brass label and is never red. If time runs out with fewer than four cards, Elin takes over (order 314). The time arc is 20 s in the prototype." },
  'why.cost': { sv: "Kostnaden på ett vanligt svar, innan spelaren väljer. Ett mynt och beloppet står längst till höger i raden, och svar utan kostnad har ingen markering. När kassan inte räcker visas svaret med streckad kant och raden Kassan räcker inte, och det går inte att välja. Exemplet är ett vanligt svar i steg 3, eftersom Karaffen har ordningskort där. Beloppen kommer från balance.ts.", en: "The cost on an ordinary answer, before the player chooses. A coin and the amount stand at the right of the row, and answers with no cost have no mark. When the till is short, the answer is shown with a dashed edge and the line Not enough in the till, and it cannot be chosen. The example is an ordinary step-3 answer, since The decanter has order cards there. The amounts come from balance.ts." },
  'why.room': { sv: "Loungebord B i vinbarens rum (wineBarHouse.ts). Medan situationen pågår står karaffen och ett tänt ljus i mässingsstake på bordet. När situationen är klarad står den tomma flaskan bredvid karaffen, med korken på ett fat. Föremålen är 1,5 gånger verklig storlek.", en: "Lounge table B in the wine bar room (wineBarHouse.ts). While the situation runs, the decanter and a lit candle in a brass holder stand on the table. When it is cleared, the empty bottle stands beside the decanter, with the cork on a saucer. The props are 1.5 times real size." },
  'why.icons': { sv: 'De sex ikonerna i kortens storlek och förstorade. Fällorna har ingen egen färg.', en: 'The six icons at card size and enlarged. The traps have no colour of their own.' },
  'sit.kicker': { sv: "Situation · Karaffen", en: "Situation · The decanter" },
  'sit.kickerExample': { sv: "Situation · Exempel", en: "Situation · Example" },
  'why.exp.hour': { sv: "Gästerna såg allt, och Elin gjorde det vackert vid bordet. Men en äldre Barolo är skör, och en timme i karaffen tar doften ifrån den.", en: "The guests saw everything, and Elin did it beautifully at the table. But an older Barolo is fragile, and an hour in the decanter takes its nose away." },
  'why.exp.candle': { sv: "Gästerna såg allt vid bordet. Men Elin hällde innan ljuset var tänt, så hon såg inte satsen, och den följde med ner i karaffen.", en: "The guests saw everything at the table. But Elin poured before the candle was lit, so she could not see the sediment, and it went into the decanter." },
  'why.ana.bar': { sv: "Vinet blev rätt: ljuset visade satsen, och den stannade i flaskan. Men vid baren såg gästerna inget av det de betalar för.", en: "The wine came out right: the candle showed the sediment, and it stayed in the bottle. But at the bar the guests saw none of what they are paying for." },
  'why.ana.show': { sv: "Vinet blev rätt, men gästerna fick aldrig se flaskan innan den öppnades. Att visa den först är en del av kvällen.", en: "The wine came out right, but the guests never saw the bottle before it was opened. Showing it first is part of the evening." },
  'why.ana.order': { sv: "Vinet blev rätt, men ordningen vid bordet höll inte för gästerna. Flaskan visas först, och den tomma flaskan ställs fram sist.", en: "The wine came out right, but the order at the table did not hold for the guests. The bottle is shown first, and the empty bottle is set down last." },
  'why.wrong.candle': { sv: "Utan ljuset under halsen ser Elin inte satsen. Då är det ingen karaffering, bara en omhällning.", en: "Without the candle under the neck, Elin cannot see the sediment. Then it is not decanting, just pouring from one vessel to another." },
  'why.wrong.serveFirst': { sv: "Att servera innan vinet är karafferat ger gästerna satsen i glaset. Flaskan visas först, och serveringen kommer sist.", en: "Serving before the wine is decanted puts the sediment in the glass. The bottle is shown first, and serving comes last." },
  'why.wrong.both': { sv: "Varken vinet eller gästernas kväll höll den här gången. Flaskan visas vid bordet, ljuset tänds och Elin häller tills satsen når halsen.", en: "Neither the wine nor the guests’ evening held this time. The bottle is shown at the table, the candle is lit, and Elin pours until the sediment reaches the neck." },
  'timeout.verdict': { sv: "Tiden ute: {name} tar över", en: "Time up: {name} takes over" },
  'timeout.lock': { sv: "Tiden ute", en: "Time up" },
  'why.timeout': { sv: "Tiden gick ut. {name} tar över och karafferar som vanligt och lägger de handgrepp som saknas. Inget grepp den här gången, men vinet och kvällen håller.", en: "Time ran out. {name} takes over and decants as usual, adding the moves that were missing. No grip this time, but the wine and the evening hold." },
  'cost.short': { sv: "Kassan räcker inte", en: "Not enough in the till" },
};
