#!/usr/bin/env node
// ORDER 024 D1 — per-district README generator.
//
// Reads reports/districts/assignment.json (from district-assign.mjs)
// and writes documentation/districts/<id>/README.md for every
// district. Uses a fixed template so future updates re-generate
// cleanly.
//
// Run: node scripts/district-readme.mjs
//
// SAFETY: existing README files are OVERWRITTEN. Human edits should
// live in adjacent files (KNOWN_ISSUES.md, TASKS.md, REVIEWS.md) —
// see the template.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const ASSIGN_PATH = 'reports/districts/assignment.json';
const WORLD_PATH = 'frontend/src/strategic/data/grythyttan-world.json';
const OUT_ROOT = 'documentation/districts';

const doc = JSON.parse(readFileSync(ASSIGN_PATH, 'utf8'));
const world = JSON.parse(readFileSync(WORLD_PATH, 'utf8'));
const buildingIndex = new Map(world.buildings.map((b) => [b.id, b]));
const landmarkIndex = new Map(world.landmarks.map((l) => [l.id, l]));
const roadIndex = new Map(world.roads.map((r) => [r.id, r]));

const HANDCRAFTED_LANDMARK_IDS_MATCH = readFileSync('frontend/src/strategic/content/world.ts', 'utf8')
  .match(/HANDCRAFTED_LANDMARK_IDS[^=]*=\s*new Set\(\[([\s\S]*?)\]\)/);
const HANDCRAFTED = new Set(HANDCRAFTED_LANDMARK_IDS_MATCH ?
  [...HANDCRAFTED_LANDMARK_IDS_MATCH[1].matchAll(/'([^']+)'/g)].map((m) => m[1]) : []);

const D2_MATCH = readFileSync('frontend/src/strategic/content/world.ts', 'utf8')
  .match(/D2_HANDCRAFTED_BUILDING_IDS\s*=\s*\[([\s\S]*?)\]/);
const D2_HANDCRAFTED_WAYS = new Set(D2_MATCH ?
  [...D2_MATCH[1].matchAll(/'([^']+)'/g)].map((m) => m[1]) : []);

for (const d of doc.districts) {
  const dId = d.id;
  const s = doc.summary[dId];
  const outDir = `${OUT_ROOT}/${dId}`;
  mkdirSync(outDir, { recursive: true });

  const namedBuildings = s.buildings
    .map((id) => buildingIndex.get(id))
    .filter((b) => b && b.name)
    .map((b) => `- \`${b.id}\` ${b.name} — kind: \`${b.kind}\``);

  const handcraftedBuildings = s.buildings.filter((id) => {
    if (D2_HANDCRAFTED_WAYS.has(id)) return true;
    const lmId = world.landmarks.find((l) =>
      l.source?.osmType === 'way' &&
      l.source?.osmId != null &&
      'w' + l.source.osmId === id &&
      HANDCRAFTED.has(l.id));
    return !!lmId;
  });

  const landmarks = s.landmarks.map((id) => {
    const l = landmarkIndex.get(id);
    if (!l) return `- \`${id}\` (missing landmark record)`;
    return `- \`${id}\` **${l.displayName}** — ${l.kind} · ${l.verification}${l.source?.osmType ? ` · OSM ${l.source.osmType}/${l.source.osmId}` : ''}`;
  });

  const namedRoads = Object.entries(s.roads.byName)
    .sort((a, b) => b[1] - a[1])
    .map(([n, c]) => `- ${n} (${c} segments)`);

  const readme = `# ${dId} · ${d.label}

**Anchor:** (${d.anchor[0].toFixed(1)}, ${d.anchor[1].toFixed(1)})   **Radius:** ${d.radius} m
**Freeze status:** ⬜ Not Started
**Last review:** —
**Confidence:** —

> Generated by \`scripts/district-readme.mjs\` from \`reports/districts/assignment.json\`.
> Do not hand-edit this file; put per-district notes in the adjacent
> \`KNOWN_ISSUES.md\`, \`TASKS.md\`, \`REVIEWS.md\` files.

## Inventory

| Category | Count |
|----------|-------|
| Buildings | ${s.buildings.length} |
| — handcrafted | ${handcraftedBuildings.length} |
| — procedural | ${s.buildings.length - handcraftedBuildings.length} |
| Roads (segments) | ${s.roads.total} |
| Landmarks | ${s.landmarks.length} |
| Water polygons | ${s.water.length} |
| Forest polygons | ${s.forest} |
| Residential zones | ${s.residential} |
| Grass polygons | ${s.grass} |
| Graveyards | ${s.graveyards} |

## Landmarks in this district
${landmarks.length ? landmarks.join('\n') : '_(none)_'}

## Named buildings
${namedBuildings.length ? namedBuildings.join('\n') : '_(none)_'}

## Named roads
${namedRoads.length ? namedRoads.slice(0, 20).join('\n') + (namedRoads.length > 20 ? `\n_...+ ${namedRoads.length - 20} more_` : '') : '_(none)_'}

## Water bodies
${s.water.length ? s.water.map((w) => `- ${w}`).join('\n') : '_(none)_'}

## Recommended camera positions
_(To be captured by Vision Owner during the first review cycle. Store as sub-headings below.)_

- Overview view
- Village view
- District (kvarteret) view
- Close street view

## Companion files

- \`KNOWN_ISSUES.md\` — defect log
- \`TASKS.md\` — outstanding work
- \`REVIEWS.md\` — Vision Owner review history

## Regeneration

Re-run \`node scripts/district-assign.mjs && node scripts/district-readme.mjs\` after any world-data change to refresh the inventory.
`;
  writeFileSync(`${outDir}/README.md`, readme);

  // Skeleton companion files (only if missing — never overwrite)
  const { existsSync } = await import('node:fs');
  for (const [name, header] of [
    ['KNOWN_ISSUES.md', '# Known issues\n\n_(Log Critical / High / Medium defects here. Every entry cites the source view or reference.)_\n'],
    ['TASKS.md', '# Outstanding tasks\n\n_(One-line per task. Prefer systemic fixes — see DEVELOPER_REVIEW_GUIDE.)_\n'],
    ['REVIEWS.md', '# Vision Owner review history\n\n_(Table of date · reviewer · verdict · linked commits.)_\n\n| Date | Reviewer | Verdict | Notes |\n|------|----------|---------|-------|\n']
  ]) {
    const path = `${outDir}/${name}`;
    if (!existsSync(path)) writeFileSync(path, header);
  }
}

console.log(`wrote ${doc.districts.length} district README + skeleton files to ${OUT_ROOT}/`);
