// luckanStrings.tillagg.ts — tillägg till D9, 2026-10-07. Slås in över luckanStrings.ts. { sv, en }, brittisk engelska. 42 nya nycklar.
// Frågorna (q.*) är exempel. Innehållet kommer från Codes frågor efter granskning, i samma form: moment, q, a1–a4, why1–why4.
// {name} i line.sender är medhjälparens namn ur personallistan.

export const LUCKAN_STRINGS_TILLAGG: Record<string, { sv: string; en: string }> = {
  'card.kicker': { sv: 'Nyfiken gäst', en: 'Curious guest' },
  'card.held': { sv: 'Det här hade hållit', en: 'This would have held' },
  'verdict.right': { sv: 'Rätt', en: 'Right' },
  'verdict.ok': { sv: 'Nästan', en: 'Almost' },
  'verdict.wrong': { sv: 'Inte den här gången', en: 'Not this time' },
  'q.sign.moment': { sv: 'Läser skylten och tittar på klockan.', en: 'Reading the sign and checking the time.' },
  'q.sign.q': { sv: 'Vad ropar du från luckan?', en: 'What do you call from the hatch?' },
  'q.sign.a1': { sv: 'Välkommen! Allt på skylten finns kvar i kväll.', en: 'Welcome! Everything on the board is still on tonight.' },
  'q.sign.a2': { sv: 'Det går fort nu, ett par minuter. Kom fram!', en: 'It\'s quick right now, a couple of minutes. Come on over!' },
  'q.sign.a3': { sv: 'Ställ dig sist i kön, så tar vi dig sen.', en: 'Join the back of the queue and we\'ll get to you.' },
  'q.sign.a4': { sv: 'Ta en hel special, den halva räcker inte långt.', en: 'Have a full special, the half won\'t go far.' },
  'q.sign.why1': { sv: 'Vänligt, men gästen tittade på klockan. Det som fattades var hur lång tid det tar.', en: 'Friendly, but they were checking the time. What they needed to hear was how long it takes.' },
  'q.sign.why2': { sv: 'Gästen tittade på klockan, och du svarade på det gästen undrade: hur lång tid det tar.', en: 'They were checking the time, and you answered what they were wondering: how long it takes.' },
  'q.sign.why3': { sv: 'Det stämmer, men det låter som att du vill bli av med gästen. Säg hellre hur lång tid det tar.', en: 'It is true, but it sounds like a brush-off. Better to say how long it takes.' },
  'q.sign.why4': { sv: 'Att sälja in innan gästen har bestämt sig skrämmer bort. Svara först på det gästen undrar.', en: 'Upselling before they\'ve decided puts people off. First answer what they\'re wondering.' },
  'q.smell.moment': { sv: 'Luktar på röken och pekar mot grillen.', en: 'Sniffing the smoke and pointing at the grill.' },
  'q.smell.q': { sv: 'Vad säger du från luckan?', en: 'What do you say from the hatch?' },
  'q.smell.a1': { sv: 'Röken är inte farlig, den går bort om en stund.', en: 'The smoke\'s harmless, it\'ll clear in a moment.' },
  'q.smell.a2': { sv: 'Det är grillad korv, den säljer bäst av allt.', en: 'That\'s grilled sausage, our best seller by far.' },
  'q.smell.a3': { sv: 'Korv från Bergslagen, grillad nyss. Vill du smaka?', en: 'Bergslagen sausage, just off the grill. Want a taste?' },
  'q.smell.a4': { sv: 'Det är bara korv, men den är billig i alla fall.', en: 'It\'s only sausage, but at least it\'s cheap.' },
  'q.smell.why1': { sv: 'Gästen gillade doften. Att be om ursäkt för röken tar bort det som lockade.', en: 'They liked the smell. Apologising for the smoke takes away what drew them in.' },
  'q.smell.why2': { sv: 'Sant och vänligt, men en smakbit hade gjort mer än ett säljargument.', en: 'True and friendly, but a taste would have done more than a sales line.' },
  'q.smell.why3': { sv: 'Doften lockade, och en smakbit låter gästen bestämma med munnen. Det är svårt att gå vidare efter det.', en: 'The smell drew them in, and a taste lets them decide with their mouth. Hard to walk on after that.' },
  'q.smell.why4': { sv: 'Att göra maten mindre värd säljer inte. Berätta hellre vad det är.', en: 'Making the food sound less worth it doesn\'t sell. Say what it is instead.' },
  'q.cold.moment': { sv: 'Står med armarna i kors vid skylten. Det är kallt.', en: 'Standing by the sign with arms crossed. It\'s cold.' },
  'q.cold.q': { sv: 'Vad ropar du från luckan?', en: 'What do you call from the hatch?' },
  'q.cold.a1': { sv: 'Värmaren är tänd vid borden, och kaffet är varmt.', en: 'The heater\'s on by the tables, and the coffee\'s hot.' },
  'q.cold.a2': { sv: 'Bestäm dig snart, vi stänger grillen om en stund.', en: 'Decide soon, we\'re shutting the grill shortly.' },
  'q.cold.a3': { sv: 'Korven kommer direkt från grillen, rykande varm.', en: 'The sausage comes straight off the grill, piping hot.' },
  'q.cold.a4': { sv: 'Ta med maten hem, det är för kallt att stå här.', en: 'Take it home with you, it\'s too cold to stand here.' },
  'q.cold.why1': { sv: 'Gästen frös. Värme och kaffe svarar på det, och borden blir en plats att stanna på.', en: 'They were cold. Warmth and coffee answer that, and the tables become a place to stay.' },
  'q.cold.why2': { sv: 'Att skynda på en gäst som tvekar gör att gästen går. Svara hellre på kylan.', en: 'Rushing someone who is hesitating makes them leave. Answer the cold instead.' },
  'q.cold.why3': { sv: 'Varmt låter bra, men gästen frös om händerna. Värmaren hade svarat på det.', en: 'Hot sounds good, but their hands were cold. The heater would have answered that.' },
  'q.cold.why4': { sv: 'Omtänksamt menat, men du skickar bort gästen och tömmer däcket. Bjud hellre in till värmen.', en: 'Kindly meant, but you send them away and empty the deck. Invite them to the warmth instead.' },
  'line.sender': { sv: '{name}, medhjälpare', en: '{name}, assistant' },
  'line.1': { sv: 'Kom fram, den är alldeles nygrillad!', en: 'Come on over, it\'s fresh off the grill!' },
  'line.2': { sv: 'Välkommen! Det tar bara ett par minuter.', en: 'Welcome! It only takes a couple of minutes.' },
  'line.3': { sv: 'Kom hit och smaka, senapen är hemgjord.', en: 'Come and have a taste, the mustard\'s homemade.' },
  'line.4': { sv: 'Hej! Ställ dig här, så fixar vi det.', en: 'Hi! Step up here and we\'ll sort you out.' },
  'torch.lighting': { sv: 'medhjälparen tänder', en: 'the assistant is lighting them' },
  'torch.wait': { sv: 'lång kö, medhjälparen väntar', en: 'long queue, the assistant waits' }
};
