// asaStrings.ts — D6, Intendent Åsa: namnet, pratbubblan och prototypens etiketter. { sv, en }, brittisk engelska.
export const ASA_STRINGS: Record<string, { sv: string; en: string }> = {
  'asa.name': { sv: 'Intendent Åsa', en: 'Curator Åsa' },
  'asa.from': { sv: 'Campus', en: 'Campus' },
  'asa.next': { sv: 'Vidare', en: 'Continue' },
  'asa.line.welcome': { sv: 'Välkommen till Grythyttan. Jag kommer från Campus och följer dig i dag. Banken lånar inte ut något förrän den har sett vad du kan, så vi börjar med att öva. Öppna Måltidens hus och öva i Stensöta, där sommelierna håller till. Inget står på spel.', en: 'Welcome to Grythyttan. I’m from Campus and I’ll be with you today. The bank won’t lend you anything until it has seen what you can do, so we start by practising. Open Måltidens hus and practise in Stensöta, where the sommeliers are. Nothing is at stake.' },
  'asa.line.unlock': { sv: 'Nu har du visat vad du kan. Banken lyssnar, och du kan börja satsa.', en: 'Now you’ve shown what you can do. The bank is listening, and you can start to invest.' },
  'opening.mentor': { sv: 'Intendent Åsa, din mentor', en: 'Curator Åsa, your mentor' },

  'ui.title': { sv: 'Intendent Åsa', en: 'Curator Åsa' },
  'ui.sub': { sv: 'Modellen, porträttet, pratbubblan och tre klipp', en: 'The model, the portrait, the speech bubble and three clips' },
  'ui.view': { sv: 'Kameran', en: 'Camera' },
  'ui.view.near': { sv: 'Nära, 4 m', en: 'Close, 4 m' },
  'ui.view.game': { sv: 'Spelets kamera, 24 m', en: 'Game camera, 24 m' },
  'ui.view.top': { sv: 'Uppifrån', en: 'From above' },
  'ui.clip': { sv: 'Klippet', en: 'Clip' },
  'ui.clip.greet': { sv: 'Hälsar', en: 'Greets' },
  'ui.clip.point': { sv: 'Pekar', en: 'Points' },
  'ui.clip.nod': { sv: 'Nickar gillande', en: 'Nods approvingly' },
  'ui.clip.idle': { sv: 'Står', en: 'Stands' },
  'ui.tempo': { sv: 'Tempo', en: 'Tempo' },
  'ui.tempo.calm': { sv: 'Lugnt', en: 'Calm' },
  'ui.tempo.normal': { sv: 'Normalt', en: 'Normal' },
  'ui.tempo.stressed': { sv: 'Stressat', en: 'Stressed' },
  'ui.line': { sv: 'Repliken', en: 'Line' },
  'ui.line.welcome': { sv: 'Första morgonen', en: 'First morning' },
  'ui.line.unlock': { sv: 'Efter första provet', en: 'After the first test' },
  'ui.bubble': { sv: 'Pratbubblan', en: 'Speech bubble' },
  'ui.on': { sv: 'Visa', en: 'Show' },
  'ui.off': { sv: 'Dölj', en: 'Hide' },
  'ui.loading': { sv: 'Laddar modellen …', en: 'Loading the model …' },
  'ui.about': { sv: 'Om skärmen', en: 'About this screen' },
  'ui.why.near': { sv: 'Hatten med brett brätte i djupblått och vit kant, vit kulle med blått band. Klänningen har blått liv, vit krage, vitt skärp och klockkjol med vit fåll. Mörk page. Ansiktet tänds på nära håll som för alla figurer (figureFace.ts).', en: 'The wide-brimmed hat in deep blue with a white edge, a white crown with a blue band. The dress has a blue bodice, white collar, white belt and a bell skirt with a white hem. A dark bob. The face appears at close range, as on every figure (figureFace.ts).' },
  'ui.why.game': { sv: 'Från 24 m läses hatten: en blå skiva med vit ring och vit mitt. Turistens solhatt är mindre och kräm. Per och en gäst står bredvid för jämförelsen.', en: 'From 24 m the hat reads: a blue disc with a white ring and a white centre. The tourist’s sun hat is smaller and cream. Per and a guest stand alongside for comparison.' },
  'ui.why.top': { sv: 'Rakt uppifrån. Brättet är 0,66 m brett och täcker axlarna. Klippen syns som brättets rörelse: handen till brättet, brättet vrids och brättet gungar.', en: 'Straight from above. The brim is 0.66 m across and covers the shoulders. The clips read as the brim’s movement: the hand to the brim, the brim turns, the brim bobs.' }
};
