// Nya nycklar för M1–K1. Slås in i STRINGS i nexusStrings.ts (leverans
// 2026-09-28). Befintliga nycklar 'hud.clock.*' ersätts av 'clock.*' nedan.

export const STRINGS_KASSAN = {
  // ── Klockan (K1) — ersätter hud.clock.* ─────────────────────
  'clock.time': { sv: '{h}.{mm}', en: '{h}:{mm}' },
  'clock.left': { sv: '{h} h {mm} min kvar', en: '{h} h {mm} min left' },
  'clock.leftMin': { sv: '{m} min kvar', en: '{m} min left' },
  'clock.label.service': { sv: 'Servicen', en: 'Service' },
  'clock.label.rush': { sv: 'Rusning', en: 'Rush' },
  'clock.label.lastOrders': { sv: 'Sista beställning', en: 'Last orders' },
  'clock.label.closed': { sv: 'Stängt', en: 'Closed' },
  'clock.label.morning': { sv: 'Morgon', en: 'Morning' },
  'clock.doorsAt': { sv: 'Dörrarna öppnar 18.00', en: 'Doors open 18:00' },
  'clock.pickup': { sv: 'Sopbilen hämtar', en: 'Bin lorry collecting' },

  // ── Pengar ───────────────────────────────────────────────────
  'money.kr': { sv: '{n} kr', en: 'SEK {n}' },
  'money.plus': { sv: '+{n} kr', en: '+SEK {n}' },
  'money.minus': { sv: '−{n} kr', en: '−SEK {n}' },

  // ── M1 Morgonen ──────────────────────────────────────────────
  'morning.phase': { sv: 'Morgonen', en: 'Morning' },
  'morning.menu': { sv: 'Meny', en: 'Menu' },
  'morning.menu.step': { sv: '+ köper 5 portioner', en: '+ buys 5 portions' },
  'morning.wine': { sv: 'Dryckeslista', en: 'Wine list' },
  'morning.wine.step': { sv: '+ köper 2 flaskor', en: '+ buys 2 bottles' },
  'morning.dish.sub': { sv: 'Inköp {cost} kr · säljs för {price} kr', en: 'Cost SEK {cost} · sells for SEK {price}' },
  'morning.wine.sub': { sv: 'Inköp {cost} kr/fl · 5 glas à {price} kr', en: 'Cost SEK {cost}/btl · 5 glasses at SEK {price}' },
  'morning.dish.sum': { sv: '{n} portioner · {kr} i inköp', en: '{n} portions · {kr} spent' },
  'morning.wine.sum': { sv: '{n} flaskor · {kr} i inköp', en: '{n} bottles · {kr} spent' },
  'morning.spent': { sv: 'Inköp i dag', en: 'Bought today' },
  'morning.mains': { sv: 'Huvudrätter', en: 'Mains' },
  'morning.mains.cover': { sv: '{n} av {booked} gäster', en: '{n} of {booked} guests' },
  'morning.booked': { sv: '{n} gäster bokade i kväll', en: '{n} guests booked tonight' },
  'morning.wine.cover': { sv: '{n} glas · {per} per gäst', en: '{n} glasses · {per} per guest' },
  'morning.potential': { sv: 'Om allt säljs', en: 'If everything sells' },
  'morning.potential.note': { sv: 'Det som inte säljs blir svinn när sopbilen kommer.', en: 'Whatever doesn’t sell is waste when the bin lorry comes.' },
  'morning.open': { sv: 'Öppna dörrarna 18.00', en: 'Open the doors 18:00' },
  'unit.portion': { sv: 'port', en: 'ptn' },
  'unit.bottle': { sv: 'fl', en: 'btl' },
  'unit.glass': { sv: 'glas', en: 'glass' },

  // ── L1 Lagret ────────────────────────────────────────────────
  'stock.kitchen': { sv: 'Lagret · kök', en: 'Stock · kitchen' },
  'stock.kitchen.sub': { sv: 'Portioner kvar', en: 'Portions left' },
  'stock.bar': { sv: 'Lagret · bar', en: 'Stock · bar' },
  'stock.bar.sub': { sv: 'Flaskor och glas i öppen flaska · 5 glas per flaska', en: 'Bottles and glasses in the open bottle · 5 per bottle' },
  'stock.of': { sv: 'av {n} portioner', en: 'of {n} portions' },
  'stock.open': { sv: '{g} glas i öppen · av {n} fl', en: '{g} in open bottle · of {n} btl' },
  'stock.ok': { sv: 'I lager', en: 'In stock' },
  'stock.low': { sv: 'Snart slut', en: 'Running low' },
  'stock.out': { sv: 'Slut', en: 'Sold out' },
  'stock.warnings': { sv: 'Varningar', en: 'Warnings' },
  'stock.none': { sv: 'Inget har tagit slut än.', en: 'Nothing has run out yet.' },
  'stock.warn.low': { sv: '{item} snart slut · {n} {unit} kvar', en: '{item} running low · {n} {unit} left' },
  'stock.warn.out': { sv: '{item} slut · stryks från menyn', en: '{item} sold out · off the menu' },

  // ── H1 Händelser ─────────────────────────────────────────────
  'feed.title': { sv: 'Händelser', en: 'Events' },
  'feed.key.ordered': { sv: 'Beställt', en: 'Ordered' },
  'feed.key.paid': { sv: 'Betalt', en: 'Paid' },
  'feed.key.tip': { sv: 'Dricks', en: 'Tips' },
  'feed.order': { sv: 'Bord {t} · {lines}', en: 'Table {t} · {lines}' },
  'feed.line.portion': { sv: '{n} × {item}', en: '{n} × {item}' },
  'feed.line.glass': { sv: '{n} glas {item}', en: '{n} glasses {item}' },
  'feed.line.bottle': { sv: '1 fl {item}', en: '1 btl {item}' },
  'feed.miss': { sv: 'Bord {t} ville ha {item} · slut', en: 'Table {t} wanted {item} · sold out' },
  'feed.pay': { sv: 'Bord {t} betalar', en: 'Table {t} pays' },
  'feed.tip': { sv: 'Dricks bord {t} · till personalen', en: 'Tip table {t} · to the staff' },
  'feed.open': { sv: 'Dörrarna öppnar · servicen börjar', en: 'Doors open · service begins' },
  'feed.close': { sv: 'Stängt 23.00 · sopbilen kommer 23.40', en: 'Closed 23:00 · bin lorry at 23:40' },
  'tonight.title': { sv: 'I kväll', en: 'Tonight' },
  'tonight.paid': { sv: 'Betalt', en: 'Paid' },
  'tonight.tips': { sv: 'Dricks till personalen', en: 'Tips to the staff' },
  'tonight.tabs': { sv: 'Öppna notor', en: 'Open tabs' },
  'tonight.tabs.value': { sv: '{n} bord · {kr}', en: '{n} tables · {kr}' },
  'tonight.tabs.none': { sv: 'Inga', en: 'None' },

  // ── B1 Back your knowledge ────────────────────────────────
  // Ordlista: aldrig "betting", "satsa", "jackpott", "spel", "odds" i UI:t.
  'back.title': { sv: 'Stå för ditt svar', en: 'Back your knowledge' },
  'back.kicker': { sv: 'Stå för ditt svar · {role} · {place}', en: 'Back your knowledge · {role} · {place}' },
  'back.steps': { sv: 'Tre steg', en: 'Three steps' },
  'back.step': { sv: 'Steg {n} av 3', en: 'Step {n} of 3' },
  'back.intro.title': { sv: 'Tre frågor. Du bestämmer hur mycket du står för varje svar.', en: 'Three questions. You decide how firmly you back each answer.' },
  'back.intro.body': { sv: 'Efter varje svar väljer du hur säker du är. Ju säkrare du är, desto mer vinner du om det stämmer och desto mer förlorar du om det inte gör det. Steget du har kommit till multiplicerar vinsten.', en: 'After each answer, choose how sure you are. The surer you are, the more you gain if you’re right and the more you lose if you’re not. The step you’ve reached multiplies the gain.' },
  'back.intro.source': { sv: 'Krediterna har du tjänat på proven i Måltidens hus och på raketerna i servicen. De kan inte köpas och växlas aldrig mot kassan.', en: 'You earned your credits in the House of Meals exams and the service rockets. They can’t be bought and never convert to cash.' },
  'back.start': { sv: 'Starta raketen', en: 'Launch the rocket' },
  'back.track': { sv: 'Raketen', en: 'The rocket' },
  'back.track.sub': { sv: 'Varje rätt steg lyfter den', en: 'Each right step lifts it' },
  'back.track.goal': { sv: 'Mål', en: 'Goal' },
  'back.track.done': { sv: 'Hela raketen klar', en: 'Rocket complete' },
  'back.howSure': { sv: 'Hur säker är du?', en: 'How sure are you?' },
  'back.odds': { sv: '+{win} om rätt · {loss} om fel', en: '+{win} if right · {loss} if wrong' },
  'back.lock': { sv: 'Stå för svaret', en: 'Back it' },
  'back.yourAnswer': { sv: 'Ditt svar', en: 'Your answer' },
  'back.correct': { sv: 'Rätt svar', en: 'Correct' },
  'back.correctYours': { sv: 'Rätt · ditt svar', en: 'Correct · yours' },
  'back.box.credits': { sv: 'Krediter', en: 'Credits' },
  'back.box.wrong': { sv: '{level} · fel', en: '{level} · wrong' },
  'back.wrongNoMult': { sv: 'Steget multiplicerar bara rätt svar.', en: 'The step only multiplies right answers.' },
  'back.next': { sv: 'Nästa steg · {step}', en: 'Next step · {step}' },
  'back.again': { sv: 'Ny raket', en: 'New rocket' },
  'confidence.guess': { sv: 'Gissar', en: 'Guessing' },
  'confidence.think': { sv: 'Tror det', en: 'Think so' },
  'confidence.know': { sv: 'Vet det', en: 'Know it' },
  'back.band.right.guess': { sv: 'Rätt, men du gissade. Nästa gång kan du stå för det.', en: 'Right, but you guessed. Next time, back it.' },
  'back.band.right.think': { sv: 'Rätt. Du trodde det, och det stämde.', en: 'Right. You thought so, and you were.' },
  'back.band.right.know': { sv: 'Du visste, och du stod för det.', en: 'You knew it, and you backed it.' },
  'back.band.wrong.guess': { sv: 'Fel, men en gissning kostar inget. Nu vet du svaret. Raketen slutar här.', en: 'Wrong, but a guess costs nothing. Now you know. The rocket ends here.' },
  'back.band.wrong.think': { sv: 'Du trodde det, men det stämde inte. Raketen slutar här.', en: 'You thought so, but it wasn’t. The rocket ends here.' },
  'back.band.wrong.know': { sv: 'Du var säker, men det stämde inte. Det är värt att veta. Raketen slutar här.', en: 'You were sure, and you were wrong. That’s worth knowing. The rocket ends here.' },
  'calib.title': { sv: 'Hur säker du var', en: 'How sure you were' },
  'calib.tonight': { sv: 'I kväll', en: 'Tonight' },
  'calib.row': { sv: '{r} av {n} rätt', en: '{r} of {n} right' },
  'calib.overconfident': { sv: 'Vet det höll i {r} av {n}. Här tror du dig kunna mer än du kan.', en: 'Know it held {r} of {n} times. Here you think you know more than you do.' },
  'calib.underconfident': { sv: 'Dina gissningar stämmer oftare än du tror. Stå för dem.', en: 'Your guesses are right more often than you think. Back them.' },
  'calib.default': { sv: 'Stå för så mycket som du kan. Då mäter krediterna vad du vet.', en: 'Back what you know. Then your credits measure what you know.' },
  'hud.credits': { sv: 'Krediter', en: 'Credits' },

  // ── S1 Sopbilen ──────────────────────────────────────────────
  'waste.phase': { sv: 'Efter stängning', en: 'After closing' },
  'waste.kicker': { sv: 'Sopbilen · 23.40', en: 'Bin lorry · 23:40' },
  'waste.title': { sv: 'Det som blev över', en: 'What was left' },
  'waste.replay': { sv: 'Spela igen', en: 'Replay' },
  'waste.hauler': { sv: 'Stensöta renhållning', en: 'Stensöta Waste' },
  'waste.col.fraction': { sv: 'Fraktion', en: 'Fraction' },
  'waste.col.what': { sv: 'Vad', en: 'What' },
  'waste.col.kg': { sv: 'Vikt', en: 'Weight' },
  'waste.col.value': { sv: 'Inköpspris', en: 'Cost price' },
  'waste.unsold': { sv: 'Matsvinn · osålt', en: 'Food waste · unsold' },
  'waste.unsold.none': { sv: 'Allt såldes', en: 'Everything sold' },
  'waste.plates': { sv: 'Tallrikssvinn', en: 'Plate waste' },
  'waste.plates.detail': { sv: 'Rester från {n} tallrikar', en: 'Leftovers from {n} plates' },
  'waste.glass': { sv: 'Glas', en: 'Glass' },
  'waste.glass.detail': { sv: '{n} tomma flaskor', en: '{n} empty bottles' },
  'waste.cardboard': { sv: 'Kartong och papper', en: 'Cardboard and paper' },
  'waste.cardboard.detail': { sv: 'Morgonens leveranser', en: 'This morning’s deliveries' },
  'waste.total': { sv: 'Totalt', en: 'Total' },
  'waste.value': { sv: 'Svinn', en: 'Waste' },
  'waste.value.note': { sv: 'Betalt redan i morse. Nu ligger det i soporna.', en: 'Paid for this morning. Now it’s in the bin.' },
  'waste.fee': { sv: 'Miljöavgift', en: 'Environmental fee' },
  'waste.fee.line': { sv: '{kg} kg × 2,90 kr + hämtning 420 kr', en: '{kg} kg × SEK 2.90 + SEK 420 collection' },
  'waste.advice.kicker': { sv: 'I morgon bitti', en: 'Tomorrow morning' },
  'waste.advice': { sv: 'Köp {n} färre {item} i morgon. Det sparar {kr} i inköp.', en: 'Buy {n} fewer {item} tomorrow. It saves {kr}.' },
  'waste.advice.none': { sv: 'Nästan inget blev över. Köp samma mängder i morgon.', en: 'Almost nothing was left. Buy the same tomorrow.' },

  // ── Artiklar (provmeny) ──────────────────────────────────────
  'item.skagen': { sv: 'Toast Skagen', en: 'Toast Skagen' }, 'item.skagen.short': { sv: 'Skagen', en: 'Skagen' },
  'item.roding': { sv: 'Röding, brynt smör', en: 'Arctic char, brown butter' }, 'item.roding.short': { sv: 'Röding', en: 'Char' },
  'item.oxfile': { sv: 'Oxfilé, rödvinssky', en: 'Beef fillet, red wine jus' }, 'item.oxfile.short': { sv: 'Oxfilé', en: 'Fillet' },
  'item.chevre': { sv: 'Chèvre, honung', en: 'Chèvre, honey' }, 'item.chevre.short': { sv: 'Chèvre', en: 'Chèvre' },
  'item.brulee': { sv: 'Crème brûlée', en: 'Crème brûlée' }, 'item.brulee.short': { sv: 'Brûlée', en: 'Brûlée' },
  'item.cremant': { sv: 'Crémant de Loire', en: 'Crémant de Loire' }, 'item.cremant.short': { sv: 'Crémant', en: 'Crémant' },
  'item.chablis': { sv: 'Chablis 2022', en: 'Chablis 2022' }, 'item.chablis.short': { sv: 'Chablis', en: 'Chablis' },
  'item.barolo': { sv: 'Barolo 2018', en: 'Barolo 2018' }, 'item.barolo.short': { sv: 'Barolo', en: 'Barolo' },
  'item.cider': { sv: 'Alkoholfri cider', en: 'Alcohol-free cider' }, 'item.cider.short': { sv: 'Cider', en: 'Cider' },
} as const;
